### ISSUE TITLE
storage question

### ISSUE THREAD

**Issue by kfox1111** [Yubico/libfido2#102]
Not sure if this is the right forum for this but:
I'm trying to understand how storage works with fido2/webauthn.

Various sites mention that during registration, a keypair is created. And during authentication, the private key generated during registration is used.

Is a private key really generated per site? If so, where is it stored? If on the key, is there a way to determine how many are stored / capacity of the key? If not, does registration become bound to the machine used to register thats storing the private key?

Maybe the documentation really means, a unique public key utilizing the single private key in the device?

**Comment by martelletto** [comment]
Hi,

For U2F (CTAP1) and FIDO2 (CTAP2) non-resident keys, this is more or less documented here:

https://developers.yubico.com/U2F/Protocol_details/Key_generation.html

FIDO2 resident keys are stored on the device. libfido2 has an API (fido_credman) to retrieve information about resident keys from devices that support this functionality. Alternatively, fido2-token can be used from the command line:

https://developers.yubico.com/libfido2/Manuals/fido2-token.html

My e-mail address is all over the git repo; feel free to reach out if you have further questions.

**Comment by kfox1111** [comment]
Ah, ok. Thanks for the info.
