### ISSUE TITLE
seed

### ISSUE THREAD

**Issue by kfox1111** [Yubico/libfido2#104]
I'm not sure if this is an issue on the libfido2 side or the ssh side. Filing here first.

When using libfido2 with openssh, you generate a key via:
ssh-keygen -t ecdsa-sk

Each time you run it, it gives a different key pair. (Randomly seeming).

A differently generated key pair is not valid with the first's public key.

All good so far, but you run into a problem if:
* You generate a keypair (A).
* You register your public key for (A) on a bunch of ssh servers.
* You take your fido2 key to a second client machine and try and login to your servers.

It kind of defeats the purpose of being able to have a portable keyfob.

If there was a way to seed the generation phase manually, then the same seed can be used on each client machine so that the ssh pub/private key doesn't have to be transferred along with the u2f keyfob?

**Comment by martelletto** [comment]
Hi,

Your question would be better addressed to [openssh-unix-dev](https://lists.mindrot.org/mailman/listinfo/openssh-unix-dev).

As far as the CTAP protocol is concerned, there are two ways to implement what you are asking:

1) Have the server send the client a list of key handles associated with the user's account. This requires some form of pre-authentication, and is typically the approach followed by existing U2F implementations.
2) Use resident keys. This is only possible on FIDO2 authenticators.

libfido2 implements both approaches; it is up to the application which one to use.

-p.
