### ISSUE TITLE
AuthData generated from C library was rejected with 'Wrong length' from python-fido2 server

### ISSUE THREAD

**Issue by malateshk** [Yubico/libfido2#107]
We have setup of python fido2 server running with minor customization.
With Fido C library as client, generated attestation object. We get an error with Authenticator data, python server is throwing back with the error 'Wrong length'.

However python client works perfect with same server.
Reference code as below:
#        USER_PRESENT = 0x01
#        USER_VERIFIED = 0x04
#        ATTESTED = 0x40
#        EXTENSION_DATA = 0x80
{{{
        self.rp_id_hash = self[:32]
        self.flags = six.indexbytes(self, 32)
        self.counter = struct.unpack('>I', self[33:33+4])[0]
        rest = self[37:]
        if self.flags & AuthenticatorData.FLAG.ATTESTED:
            self.credential_data, rest = \
                AttestedCredentialData.unpack_from(self[37:])
        else:
            self.credential_data = None
 
        if self.flags & AuthenticatorData.FLAG.EXTENSION_DATA:
            self.extensions, rest = cbor.decode_from(rest)
        else:
            self.extensions = None

        if rest:
            raise ValueError('Wrong length')
}}}

>> self.flags = six.indexbytes(self, 32)
In case of python client value will be around 64/65, but with C library flag value is around 151.

Also we have observed that for python code, below line of code gets triggered (from above code snippet)
if self.flags & AuthenticatorData.FLAG.ATTESTED:
            self.credential_data, rest = \
                AttestedCredentialData.unpack_from(self[37:])

For C library the below code will be triggered:
if self.flags & AuthenticatorData.FLAG.EXTENSION_DATA:
            self.extensions, rest = cbor.decode_from(rest)

What could be the possible reason for the issue?

Regards
Malatesh

**Comment by martelletto** [comment]
Hi Malatesh,

To help me diagnose what you are seeing, could you try to:

- Dump authdata as returned by libfido2;
- Dump authdata as seen by `AuthenticatorData.__init__`;
- Isolate the parsing done in your implementation of `AuthenticatorData.__init__` in a standalone Python snippet?

Thank you,

-p.

**Comment by martelletto** [comment]
It would also be interesting to know if the client is speaking FIDO2 or U2F to the authenticator, and the architecture the C client is running on.

**Comment by malateshk** [comment]
Hi Pedro

> It would also be interesting to know if the client is speaking FIDO2 or U2F to the authenticator, and the architecture the C client is running on.

It's FIDO2 and the architecture is Intel-x86 and Ubuntu-16 as OS.

**Comment by malateshk** [comment]
> Hi Malatesh,
> 
> To help me diagnose what you are seeing, could you try to:
> 
>     * Dump authdata as returned by libfido2;
> 
>     * Dump authdata as seen by `AuthenticatorData.__init__`;
> 
>     * Isolate the parsing done in your implementation of `AuthenticatorData.__init__` in a standalone Python snippet?
> 
> 
> Thank you,
> 
> -p.

I have attached my client side data and the custom server code.
[client_data.zip](https://github.com/Yubico/libfido2/files/4016649/client_data.zip)
[custom_server.zip](https://github.com/Yubico/libfido2/files/4016650/custom_server.zip)

Thank you
Malatesh

**Comment by martelletto** [comment]
Hi Malatesh,

Thank you for the detailed information.

`AuthenticatorData.__init__` expects authdata in its raw/binary form, and you are passing it a CBOR-encoded blob. You are missing a cbor_load() (or equivalent) either on the client side (as python-fido2's client seems to do) or on the server side. Please see below.

-p.

```
tha:~> python3
Python 3.7.5 (default, Dec 23 2019, 06:44:42) 
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64
>>> import cbor
>>> authdata_b64 = "WMRJlg3liA6MaHQ0Fw9kdmBbj+SuuaKGMseZXPO6gx2XY0EAAALk+iuZ3J45QlePkkow0jxBGABAX+DgV+43R4BjAHFaXQYYLAkaGbN2KOFaBXp3q9T9F3tZZGl+8ZWRAtgWcekWqtPW4q2m5kIpXa739c5WaIIP1KUBAgMmIAEhWCAK8gibW1CQsq1TlvZxMtqi+vri36iAXCN5mtyFp3cqPyJYIBLEH/tzE4Gx1C1fHBwTGRYCZaK46rmr3QQHsNGPOpDY"
>>> authdata_cbor = base64.b64decode(authdata_b64)
>>> len(authdata_cbor)
198
>>> authdata_cbor[32]
151
>>> 
zsh: suspended  python3
tha:~> printf "%x\n" 151
97
tha:~> fg
[1]  + continued  python3
>>> authdata = cbor.loads(authdata_cbor)
>>> len(authdata)
196
>>> authdata[32]
65
>>> 
zsh: suspended  python3
tha:~> printf "%x\n" 65 
41
```
