### ISSUE TITLE
Assertion Signature generated in library doesn't accepts in authentication process on webauthn python server

### ISSUE THREAD

**Issue by malateshk** [Yubico/libfido2#110]
Invalid signature returned when the assertion signature passed for authentication complete to webauthn python server.

```
def _ecdsa_sig_verify(backend, public_key, signature, data):
    res = backend._lib.ECDSA_verify(
        0, data, len(data), signature, len(signature), public_key._ec_key
    )
    if res != 1:
        backend._consume_errors()
        raise InvalidSignature
```
We customized the python server(attached server and library dump).
[Auth_Client_data.zip](https://github.com/Yubico/libfido2/files/4041346/Auth_Client_data.zip)
[custom_server.zip](https://github.com/Yubico/libfido2/files/4041347/custom_server.zip)

Regards
Malatesh

**Comment by martelletto** [comment]
Hi Malatesh, I will try to have a look over the weekend.

-p.

**Comment by malateshk** [comment]
Hi Pedro,

Thank you, your input is appreciated. Currently I have struck at that point.

Regards
Malatesh

**Comment by martelletto** [comment]
Hi Malatesh,

The client data hash passed to the authenticator was `2b7e8533f6458a7230a3640d89a1cd1bdcfdd8f094ca5f577d963178fe8d1e61`, which seems to be the SHA256 of the challenge:

```
% echo 'E9bLKj7pNdTWiXyMOjnV+Ed4P9PNi3fuxIqY1cSP3xY=' | base64 -d | openssl sha256
(stdin)= 2b7e8533f6458a7230a3640d89a1cd1bdcfdd8f094ca5f577d963178fe8d1e61
```

If you are running a WebAuthn-compatible server, then this is wrong. The client data hash passed to the authenticator needs to match the hash of `clientDataJSON`. From your logs:

```
ClientDataJSON(RAW): {"challenge":"E9bLKj7pNdTWiXyMOjnV+Ed4P9PNi3fuxIqY1cSP3xY=","clientExtensions":{},"origin":"https://localhost:443","type":"webauthn.get"}
```

I suggest taking a look at [python-fido2's ClientData class](https://github.com/Yubico/python-fido2/blob/master/fido2/client.py#L51).

-p.
