### ISSUE TITLE
How to get event for new device insertion.

### ISSUE THREAD

**Issue by iradization** [Yubico/libfido2#113]
Hi, 

I wish to implement UI which displays all fido2 connected devices which updates on realtime. 

For that I need notifications for device connection and device disconnection. 

In order to get event for update device that got disconnected I simply use the following method which is blocking : 

`int fido_dev_get_assert(fido_dev_t *, fido_assert_t *, const char *);`

when this function returns which result that doesn't match FIDO_OK, I try check the device existence by trying to re-open the device. 

However, I wish to have the reverse logic for detecting devices that got connected. is there any API for notify new fido2 device insertion ? 

one solution that cam up my mind is using loop that constantly check number of connected devices in separated thread using the following API : 
`int fido_dev_info_manifest(fido_dev_info_t *, size_t, size_t *);`

and wait for changes in the number of devices. But I'm looking for something which is event driven. 

thanks !

**Comment by martelletto** [comment]
Hi,

I am afraid there is no such API in libfido2. However, as long as "event driven" does not imply "not using concurrent threads", you can build on your suggestion and have the thread calling fido_dev_info_manifest() trigger an event on a different thread through your favourite event-abstraction API.

-p.
