### ISSUE TITLE
getting FIDO_ERR_TX when trying to connect fido2 device during loginwindow

### ISSUE THREAD

**Issue by iradization** [Yubico/libfido2#114]
Hi, 

I tried to run code that attempts to connects fido2 device during loginwindow stage on macOS Mojave where no user is currently active. 

However, unlike in active user mode (after logging in successfully), the command `fido_dev_get_assert` returns error -1 (FIDO_ERR_TX) , although the fido2 device is opened successfully and the method that enumerate fido2 devices also works fine.

any idea what can lead to this problem (is it permission issue) ? 

I've seen than in windows 10 +1903 there's an issue that require administrator privileges and I wonder if it's similar problem here (although it does work on non privileged account while active user is on) 

here's the link to the windows issue :
https://groups.google.com/a/fidoalliance.org/forum/#!topic/fido-dev/8A3NmsUEOvM

Deeper examination of the problem showed that the usb open command is failed. here's the relevant log from libfido2.dylib

```
**fido_hid_open: IOHIDDeviceOpen**
fido_dev_open_tx: dev->io.open
fido_tx: d=0x7fa55f2ca670, cmd=0x83, buf=0x7fa55f381b42, count=136
  00 02 07 00 00 00 81 ff ff ff ff ff ff ff ff ff
  ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
  ff ff ff ff ff ff ff 9a c4 c6 d5 ae 4a 4b 57 72
  89 5f 39 ee 08 4e 17 ee e6 07 36 fc fd f3 83 be
  29 77 fd 2e 0e 37 22 40 6c 3f f6 8e 23 a0 80 57
  7c a6 94 b4 cb 1b e9 a6 1b a8 8b 70 bb c1 2b 4f
  a0 a6 99 14 07 d1 55 ab d4 05 1f 59 d8 1f 12 16
  d2 d8 36 8f cc 7d ed 0a 23 2e 57 30 47 7b d2 8f
  0e 8c b5 16 b0 42 8c 3e
fido_tx: invalid argument (0x0, 136)
key_lookup: fido_tx
u2f_authenticate_single: key_lookup
u2f_authenticate: u2f_authenticate_single
```

thanks,

**Comment by martelletto** [comment]
It indeed looks like a permission issue. Can you try to save the return value of IOHIDDeviceOpen() and pass it to fido_log_debug()?

**Comment by iradization** [comment]
It seems like processes that runs under the non-privileged user _securityagent (id=92), are subject to fail on usb connection method IOHIDDeviceOpen.

**Comment by martelletto** [comment]
Thanks for confirming. Is there anything we can do differently in libfido2? An alternative USB connection method, perhaps?

**Comment by martelletto** [comment]
Closing as not actionable (in the context of libfido2). Feel free to reopen should that change.
