### ISSUE TITLE
Openssh Portable and libfido2

### ISSUE THREAD

**Issue by gmarano** [Yubico/libfido2#116]
Hi, i've compiled latest openssh-portable (https://github.com/openssh/openssh-portable ) and latest libfido2.

When i launch this command for a key generation onboard to my fido device i catch this error, this is the trace:

./ssh-keygen -vvvv -t ecdsa-sk -w /usr/lib/x86_64-linux-gnu/libsk-libfido2.so

Generating public/private ecdsa-sk key pair.
You may need to touch your security key to authorize key generation.
debug3: start_helper: started pid=16942
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/local/libexec/ssh-sk-helper
debug1: sshsk_enroll: provider "/usr/lib/x86_64-linux-gnu/libsk-libfido2.so", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0
debug1: sshsk_enroll: using random challenge
debug1: sshsk_open: provider /usr/lib/x86_64-linux-gnu/libsk-libfido2.so implements version 0x00020000
Security key provider "/usr/lib/x86_64-linux-gnu/libsk-libfido2.so" implements unsupported version 0x00020000 (supported: 0x00040000)
debug1: ssh-sk-helper: Enrollment failed: invalid format
debug1: ssh-sk-helper: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -4
debug3: reap_helper: pid=16942
Key enrollment failed: invalid format

How can i fix the UNSUPPORTED VERSION error ?

Thanks
Giancarlo

**Comment by martelletto** [comment]
Hi,

The middleware functionality has been moved to OpenSSH itself, and its development reached a point where the expected API version no longer matches that of the middleware shipped with libfido2 1.3.0.

To enable the middleware functionality in OpenSSH, you will need to build OpenSSH with --with-security-key-builtin. You can then omit the -w option to ssh-keygen.

Apologies for the confusion.

-p.
