### ISSUE TITLE
Multiple packaging issues

### ISSUE THREAD

**Issue by nbraud** [Yubico/libfido2#122]
Dear upstream,

I found several issues in the packaging present in the repository, while preparing to package `libfido2` in Debian, including (but not limited to):
- the OpenSSH helper (`libsk-libfido2.so`) was shipped under `/usr/lib/${arch_triplet}` by `libfido2-dev`;
- not all documentation is installed (even after the fix in 337b42849558f7241d428265a81ab7052b6659bb) ;
- `debian/copyright` is out of date (some files were moved around).

I do not think I will prepare a PR for this, but you can find the version I uploaded to Debian [in NEW] or [on Salsa].

[in NEW]: https://ftp-master.debian.org/new/libfido2_1.3.0-1.html
[on Salsa]: https://salsa.debian.org/auth-team/libfido2

**Comment by martelletto** [comment]
Hi,

Thank you for packaging libfido2 for Debian, and apologies for the mistakes. I agree there is no need for a PR. To avoid duplication and obsolete bits of Debian packaging lying around, would you object if we were to drop `debian/` from libfido2?

A side note: I noticed that https://salsa.debian.org/auth-team/libfido2/blob/debian/sid/debian/watch is currently watching for yubico-piv-tool releases.

-p.

**Comment by martelletto** [comment]
No response in nearly two months; closing.

**Comment by martelletto** [comment]
Outdated debianization removed in 1c2e008.
