### ISSUE TITLE
Pre-built libfido2 1.3.0 for macOS statically linked to lib in Pedro's home

### ISSUE THREAD

**Issue by roger-dodger** [Yubico/libfido2#123]
I tried to install openssh 8.2p1 using brew on macOS. This version of SSH has support for U2F/FIDO keys but requires libfido2 to communicate with the Yubikey.

The pre-compiled version for macOS that can be found on the Yubico website [1] contains the necessary libraries _libsk-libfido2.so_ and _libcrypto.1.1.dylib_ the path for it is statically compiled into the binary.

_ssh-keygen_ checks directory _/usr/local/lib/_ and _/usr/lib/_ for those shared objects, however the path for _libsk-libfido2.so_ can also be set via environment variable with name _SSH_SK_PROVIDER_.

When I set the environment variable to the correct path for _libsk-libfido2.so_, I get another error that _libcrypto.1.1.dylib_ can't be found - see my example below:

```
$ export SSH_SK_PROVIDER=/Users/<myusername>/Downloads/libfido2-1.3.0-darwin-x86_64/lib/libsk-libfido2.so
$ ssh-keygen -t ed25519-sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
Provider "/Users/<myusername>/Downloads/libfido2-1.3.0-darwin-x86_64/lib/libsk-libfido2.so" dlopen failed: dlopen(/Users/<myusername>/Downloads/libfido2-1.3.0-darwin-x86_64/lib/libsk-libfido2.so, 2): Library not loaded: **/Users/pedro/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib**
  Referenced from: /Users/<myusername>/Downloads/libfido2-1.3.0-darwin-x86_64/lib/libsk-libfido2.so
  Reason: image not found
Key enrollment failed: invalid format
```
As you can see, the shared object _libsk-libfido2.so_ is looking for _libcrypto.1.1.dylib_ in directory /Users/pedro/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib

I would appreciate if you can have a look at this an re-build the library without and absolute paths.

Thanks,
Roger

[1] https://developers.yubico.com/libfido2/Releases/

**Comment by kongeo** [comment]
Hi,
thanks for reporting this! The sk middle-ware has been moved from libfido2 and as a result it will not be part of the upcoming libfido2 release. Would you please use the openssh one instead?

Thanks!

**Comment by roger-dodger** [comment]
Thanks for letting me know. I can confirm that it works when I build _openssh_ with the _--with-security-key-builtin_ flag. Issue will be closed.
