### ISSUE TITLE
Request to bring libfido over to MSYS

### ISSUE THREAD

**Issue by cw789** [Yubico/libfido2#132]
Would it be possible for anyone to bring libfido over to [MSYS2](https://github.com/msys2/MSYS2-packages).

I think a lot of people are using OpenSSH on Windows via "Git for Windows".
With having libfido2 within MSYS it would be currently the easiest way for using the new OpenSSH FIDO/U2F support.

Related Issue: https://github.com/git-for-windows/git/issues/2525

**Comment by riedel** [comment]
I had no problem actually compiling it with mingw on msys.  Also there is a cygwin package. So it would be up to the msys folks to simply package it. Or did you have any issues?

**Comment by tavrez** [comment]
@riedel could you please explain your build steps? I can't build it using msys

**Comment by riedel** [comment]
`cmake -G "Unix Makefiles" ..` works for me in the mingw64 shell.

The library (not the tools) itself also build under MSYS natively if you disable the -Wall and pedantic check (no clue what is the problem with string.h here) in the cmake Makefile
with `CMAKE_LEGACY_CYGWIN_WIN32=1 cmake ..` 

But don't you simply post your errors here?

**Comment by riedel** [comment]
As said there is a cygwin packages with a patch to CMakeLists.txt that theoretically could be merged into the source here

**Comment by tavrez** [comment]
@riedel Thank you, the problem was with -std=c99, it is now working.

**Comment by martelletto** [comment]
Fixed in 5a9be2f0 by @riedel.
