### ISSUE TITLE
Wrong EdDSA public key parsing

### ISSUE THREAD

**Issue by andrewkozlik** [Yubico/libfido2#136]
COSE uses an uncommon method of encoding EdDSA public keys, because it encodes the x-coordinate of the EC point as the public key, see https://tools.ietf.org/html/rfc8152#section-13.2. The standard encoding of EdDSA public keys as defined in https://tools.ietf.org/html/rfc8032#section-5.1.2 encodes the y-coordinate and the sign of the x-coordinate as the public key. This is the encoding used in OpenSSL, see
https://github.com/openssl/openssl/blob/e7fb44e7c3f7a37ff83a6b69ba51a738e549bf5c/crypto/ec/curve25519.c#L1857.

In the function `eddsa_pk_to_EVP_PKEY()` the public key needs to be converted to the standard format before passing it to the OpenSSL function `EVP_PKEY_new_raw_public_key()`. Similarly in `eddsa_pk_from_EVP_PKEY()` the x-coordinate needs to be computed from the standard format.

**Comment by andrewkozlik** [comment]
This is going to be a big problem for developers implementing COSE with EdDSA in general, because the conversion involves multi-precision modular arithmetic and I don't think there is currently any library which would provide a function to do the conversion for you. It seems pretty clear that the authors of COSE hadn't thought this through, because as far as I see there is no way to determine the sign of the y-coordinate from knowing only the x-coordinate. So when verifying a signature, one would have to try both signs for the y-coordinate. I think this is probably worth discussing changing the COSE specification. The key type of EdDSA keys should be changed to EC2 and the x parameter of EC2 keys should be allowed to encode only the sign of the x-coordinate.

**Comment by andrewkozlik** [comment]
Posted my concerns to the COSE mailing list: https://mailarchive.ietf.org/arch/msg/cose/V9GXBGZ14xOdzml4GI2yF4McKkA/

**Comment by andrewkozlik** [comment]
Based on the discussion in the COSE mailing list, it's becoming quite clear that the definition of the OKP key type which is currently given in RFC 8152 (COSE) is completely wrong. Apparently the intention was for the 'x' parameter to contain the standard encoding of EdDSA public keys as defined in RFC 8032. So assuming that this will be fixed accordingly in the COSE specification, we can close the issue here.

**Comment by martelletto** [comment]
Thank you for looking into this.
