### ISSUE TITLE
Bug: Wrong EdDSA attestation signature verification

### ISSUE THREAD

**Issue by andrewkozlik** [Yubico/libfido2#139]
RFC 8032 https://tools.ietf.org/html/rfc8032#section-5 defines two variants of EdDSA: PureEdDSA and HashEdDSA. According to https://tools.ietf.org/html/rfc8152#section-8.2:

> For use with COSE, only the pure EdDSA version is used.

The function `fido_cred_verify_self()` https://github.com/Yubico/libfido2/blob/93aa154d2280cbe9a8dd7fc1747b91d353f8d907/src/cred.c#L462 uses a mutilated form of HashEdDSA when it should be using PureEdDSA. In other words it's verifying the SHA-256 digest of `cdh` and `authdata_cbor`, when it should be verifying the (undigested) concatenation of these two byte strings.

**Comment by andrewkozlik** [comment]
In `fido_assert_verify()` the verification is done correctly, because this function calls `get_signed_hash()` which has special handling of EdDSA signatures: https://github.com/Yubico/libfido2/blob/93aa154d2280cbe9a8dd7fc1747b91d353f8d907/src/assert.c#L386-L405
So it skips hashing in case of EdDSA, making the function name a misnomer. It looks to me like `get_signed_hash_packed()` should be replaced with `get_signed_hash()`. These two functions are just a duplication of code with the difference that the second one has the bug fixed.

**Comment by martelletto** [comment]
Fixed in 95126ee by @andrewkozlik.
