### ISSUE TITLE
Is there a way to use fido2-assert with mutiple resideny key credentials?

### ISSUE THREAD

**Issue by sbweeden** [Yubico/libfido2#14]
I have a token that has been issued with two resident key credentials for the same RP (different users).

When calling fido2-assert to obtain a resident key credential assertion, the current behaviour is to return an indication that there is more than one credential available:

fido2-assert: fido_assert_count: 2

Is there any way (or planned way) for the command-line tools to proceed forward from this point to identify and then choose to utilise one of these, or is that simply beyond the scope of what is intended for these tools?

**Comment by martelletto** [comment]
that's currently beyond the scope of fido2-assert, but it shouldn't 
be too much work to adapt it for this specific use case.

PRs welcome :)

-p.

**Comment by martelletto** [comment]
implemented in 18efc7c8, and will be in the next version of libfido2.
