### ISSUE TITLE
ed25519 problem with libressl 

### ISSUE THREAD

**Issue by prusnak** [Yubico/libfido2#144]
Interesting and rather non-trivial issue. :-)

I was testing OpenSSH 8.2p1 with libfido2 support and hit the following issue with Trezor Model T:

* openssh 8.2p1 + libfido2 (commit 0a44eff9c209765222056971b0793b35705b7a91) linked against **libressl 3.0.2**: `ssh-keygen -t ed25519-sk` does not work, after confirming on the device I end up with `Key enrollment failed: invalid format`

* openssh 8.2p1 + libfido2 (commit 0a44eff9c209765222056971b0793b35705b7a91) linked against **openssl-1.1.1d**: `ssh-keygen -t ed25519-sk` works

* `ssh-keygen -t ecdsa-sk` works in both configurations

Can you please try out whether you see the same problem with ed25519 enabled Yubikey? I don't have one to test.

**Comment by prusnak** [comment]
I found the culprit: https://github.com/Yubico/libfido2/blob/master/src/eddsa.c#L16-L51

It seems that with LibreSSL and OpenSSL < 1.1.1 you just define empty stubs for some functions.

This seems just plain wrong, especially when README says that libfido2 depends on LibreSSL and _alternatively_ OpenSSL may be used.

**Comment by prusnak** [comment]
For the record, with the following setup:

* openssh 8.2p1 + libfido2 (commit 0a44eff) linked against **openssl-1.0.2**

neither `ssh-keygen -t ed25519-sk`, nor `ssh-keygen -t ecdsa-sk` work - both end up with the `Key enrollment failed: invalid format` error.

**Comment by martelletto** [comment]
Hi,

The purpose of these stubs is to allow a build of libfido2 to produce a working library to the extent supported by the flavour and version of OpenSSL against which it was linked.

Disclaimer: I tested with examples/cred and examples/assert (with a PIN, to exercise the ECDH, AES, and HMAC paths).

- With LibreSSL 3.0.2, ECDSA and RSA work. EDDSA does not, as LibreSSL does not abstract ed25519 through its EVP_PKEY API. Perhaps there is a way to do EDDSA in LibreSSL 3.0.2. On a quick look, there does not seem to be;
- With OpenSSL 1.0.2u, ECDSA and RSA work. EDDSA does not, as OpenSSL 1.0.2u does not implement it. I don't know why ssh + ECDSA is not working for you. Perhaps the middleware assumes OpenSSL 1.1 when built with WITH_OPENSSL.

The only issue here seems to be the README.md recommendation of LibreSSL over OpenSSL, when LibreSSL does not seem to support EDDSA. I will take a look at amending README.md over the weekend.

-p.

**Comment by prusnak** [comment]
Can we maybe add at least `fido_log_debug("%s: this feature is not support with currently used version of LibreSSL/OpenSSL", __func__);` or something similar to the stub functions? I assume this might help to save several hours of debugging for someone else in the future.

**Comment by martelletto** [comment]
Sure, of course. I will do that when I amend README.md.

**Comment by martelletto** [comment]
Addressed in 69d9119bc9, 25477d8a46. Thank you!
