### ISSUE TITLE
please include release notes in release itself

### ISSUE THREAD

**Issue by roycewilliams** [Yubico/libfido2#158]
Congrats on the new release! For future releases, please consider including the release notes in the release tag description itself, e.g.:

* Version 1.4.0 (2020-04-15)
 ** hid_hidapi: hidapi backend; enable with -DUSE_HIDAPI=1.
 ** Fall back to U2F if the key claims to, but does not support FIDO2.
 ** FIDO2 credential protection (credprot) support.
 ** New API calls:
  - fido_cbor_info_fwversion;
  - fido_cred_prot;
  - fido_cred_set_prot;
  - fido_dev_set_transport_functions;
  - fido_set_log_handler.
 ** Support for FreeBSD.
 ** Support for C++.
 ** Support for MSYS.
 ** Fixed EdDSA and RSA self-attestation.

Keep up the good work!

**Comment by kongeo** [comment]
Thanks for the kind words! We will do consider this on the releases to follow.
