### ISSUE TITLE
Yubico apt repository include 1.4.x?

### ISSUE THREAD

**Issue by gabriel** [Yubico/libfido2#162]
Would it be possible to update the yubico apt repository to include the new 1.4 build?
https://launchpad.net/~yubico/+archive/ubuntu/stable

Thanks!

**Comment by martelletto** [comment]
Hi,

Just a quick note to say this is being worked on. The packages need to be notarised by Yubico, so it will take some time. A realistic ETA would be ~a week from today. Apologies for the inconvenience.

-p.

**Comment by martelletto** [comment]
Hi,

1.4.0 packages for Focal, Bionic, and Xenial have been published at https://launchpad.net/~yubico/+archive/ubuntu/stable. Shout out to @kongeo for his time and help.

-p.
