### ISSUE TITLE
Error using fido2-token on clean install

### ISSUE THREAD

**Issue by Peter98** [Yubico/libfido2#163]
**What version of libfido2 are you using?** Current git master

**What operating system are you running?** Ubuntu 20.04 LTS

**What application are you using in conjunction with libfido2?** None

**How does the problem manifest itself?** When running fido2-token I get the following error: fido2-token: symbol lookup error: fido2-token: undefined symbol: fido_cbor_info_fwversion

**Is the problem reproducible?** Yes on a clean VM Ubuntu install using the following install commands:
git clone https://github.com/Yubico/libfido2.git
cd libfido2
sudo apt install -y cmake libcbor-dev libssl-dev libudev-dev
(rm -rf build && mkdir build && cd build && cmake ..)
make -C build
sudo make -C build install 

**What are the steps that lead to the problem?** I can create credentials and make assertions following document examples but I cannot use the fido2-token command.

**Does the problem happen with different authenticators?**

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L

</pre>
</details>
fido2-token: symbol lookup error: fido2-token: undefined symbol: fido_cbor_info_fwversion
<br>
**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;

</pre>
</details>
fido2-token: symbol lookup error: fido2-token: undefined symbol: fido_cbor_info_fwversion

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ &lt;command1&gt;
$ &lt;command2&gt;
(...)
$ &lt;commandn&gt;

</pre>
</details>

**Comment by martelletto** [comment]
Hi Peter,

You need to run `ldconfig`, as root, to rebuild its cache.

-p.

**Comment by Peter98** [comment]
Thank you that worked.
