### ISSUE TITLE
Archlinux libfido2 FIDO_ERR_PIN_BLOCKED

### ISSUE THREAD

**Issue by NgoHuy** [Yubico/libfido2#170]
Hi team, I have problem with yubico 5 NFC

**What version of libfido2 are you using?**
1.4.0-1

**What operating system are you running?**
Archlinux

**What application are you using in conjunction with libfido2?**
openssh 8.2p1-3

**How does the problem manifest itself?**
I cannot create ssh key type: `ecdsa-sk`

**Please include the output of `fido2-token -L`.**
```
fido2-token -L
/dev/hidraw5: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
```
I have tried reset the pin included admin pin, but no luck. the key always refuses with `BLOCKED` error
<img width="950" alt="image" src="https://user-images.githubusercontent.com/1238112/81257409-65a6a600-905d-11ea-84cd-d53ca1800840.png">

**Comment by martelletto** [comment]
Hi,

Try using `fido2-token -R <path>` to reset the FIDO2 application on your Yubikey, but please note that:

- You will lose FIDO2 credentials configured on the device;
- There is a 5-second window after power-up during which a reset can be issued;
- You will need to confirm the reset by touching your Yubikey.

If plugging the Yubikey and running `fido2-token -R` within 5 seconds is not an option, you could use something along the lines of:

```
$ cat attach
#!/bin/sh -eu

DEV=""

while [ -z "${DEV}" ]; do
        DEV="$(fido2-token -L | sed 's/^\(.*\): .*$/\1/;q')"
        sleep .5
done

echo "${DEV}"
$ cat reset
#!/bin/sh -eu

read DEV

fido2-token -R "${DEV}"
$ ./attach | ./reset
```

**Comment by NgoHuy** [comment]
Does It mean that I need reconfigure all sites with previous fido2 token and all data included pgp will be lost?

**Comment by martelletto** [comment]
Hi,

FIDO2, PIV, and PGP are distinct subsystems. If you reset the FIDO2 application on your Yubikey, you will lose your FIDO2 credentials; PIV and PGP won't be affected.

-p.

**Comment by NgoHuy** [comment]
thank you very much. I will try it now.

**Comment by dagheyman** [comment]
Note that all U2F credentials will be lost as well.

**Comment by NgoHuy** [comment]
Additional, I never set pin for FIDO2, I only touch the flash light, if it requested the pin again, was there default value for it?

**Comment by martelletto** [comment]
There isn't a default FIDO2 PIN. If a FIDO2 PIN was set, then it must have been configured at some point.

You can set a FIDO2 PIN with `fido2-token -S`, and change it with `fido2-token -C`.
