### ISSUE TITLE
Allow for reliable credProtect feature detection

### ISSUE THREAD

**Issue by FabianHenneke** [Yubico/libfido2#175]
**Describe the feature you would like.**
While libfido2 already allows to set the credProtect level for a new credential via `fido_cred_set_prot`, it does not offer a way to perform reliable [feature detection as per the CTAP 2.1 spec](https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#credProtectFeatureDetection).

**Describe the impact to existing functionality.**
None, this would simply require adding two new functions to the public API.

**Describe how you are willing to help.**
I have submitted #174 which adds the required `fido_cbor_info_{maxcredcntlst,maxcredidlen}` functions.

**Comment by martelletto** [comment]
Merged. Thanks!
