### ISSUE TITLE
Release zip for libfido2-1.2.0-win64.zip is corrupt

### ISSUE THREAD

**Issue by homoSapiensSapiens** [Yubico/libfido2#176]
**What version of libfido2 are you using?**
1.2.0

**What operating system are you running?**
Irrelevant

**What application are you using in conjunction with libfido2?**
Irrelevant

**How does the problem manifest itself?**
When I download the release from the URL https://developers.yubico.com/libfido2/Releases/libfido2-1.2.0-win64.zip, the download cannot be opened like a zip file.

**Is the problem reproducible?**
Yes

**What are the steps that lead to the problem?**
Got to "Releases" page
Click on the link to download libfido2-1.2.0-win64.zip
Try to extract the zip.

**Does the problem happen with different authenticators?**
It happens before the zip could be opened

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L

</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;

</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ &lt;command1&gt;
$ &lt;command2&gt;
(...)
$ &lt;commandn&gt;

</pre>
</details>

**Comment by nevun** [comment]
Thank you for reporting this! We are looking into it. Note that the newer releases are not affected.

**Comment by nevun** [comment]
This has now been fixed. Thanks again for reporting it.
