### ISSUE TITLE
packed attestation

### ISSUE THREAD

**Issue by shimritd** [Yubico/libfido2#18]
Hi,
I have two questions:
1. does the lib support self attestation? it see,s not since the verification is failed when x5c is missing.
2. does it support type rs256? can't see it in verify_sig

Thanks

**Comment by martelletto** [comment]
Hi,

>1. does the lib support self attestation? it see,s not since the verification is failed when x5c is missing.

There is no explicit support for self-attestation; there is however 
implicit support for "none attestation", in that the client can opt 
not to pass attestation information to the server.

>2. does it support type rs256? can't see it in verify_sig

For packed attestations, only ES256 is currently supported.

-p.

**Comment by shimritd** [comment]
thanks!
is there a plan to support RS256 anytime soon?

**Comment by martelletto** [comment]
Hi,

>is there a plan to support RS256 anytime soon?

I haven't come across an authenticator programmed with a RS256 
attestation key. Does the following diff work for you?

-p.

diff --git src/cbor.c src/cbor.c
index 8078a37..410f4df 100644
--- src/cbor.c
+++ src/cbor.c
@@ -1089,14 +1089,7 @@ decode_attstmt_entry(const cbor_item_t *key, const cbor_item_t *val, void *arg)
 	if (cbor_string_copy(key, &name) < 0)
 		goto fail;
 
-	if (!strcmp(name, "alg")) {
-		if (cbor_isa_negint(val) == false ||
-		    cbor_int_get_width(val) != CBOR_INT_8 ||
-		    cbor_get_uint8(val) != -COSE_ES256 - 1) {
-			log_debug("%s: alg", __func__);
-			goto fail;
-		}
-	} else if (!strcmp(name, "sig")) {
+	if (!strcmp(name, "sig")) {
 		if (cbor_bytestring_copy(val, &attstmt->sig.ptr,
 		    &attstmt->sig.len) < 0) {
 			log_debug("%s: sig", __func__);
diff --git src/cred.c src/cred.c
index 3e9d402..08bf214 100644
--- src/cred.c
+++ src/cred.c
@@ -6,6 +6,7 @@
 
 #include <openssl/ec.h>
 #include <openssl/evp.h>
+#include <openssl/rsa.h>
 #include <openssl/sha.h>
 #include <openssl/x509.h>
 
@@ -293,6 +294,7 @@ verify_sig(const fido_blob_t *dgst, const fido_blob_t *x5c,
 	X509		*cert = NULL;
 	EVP_PKEY	*pkey = NULL;
 	EC_KEY		*ec;
+	RSA		*rsa;
 	int		 ok = -1;
 
 	/* openssl needs ints */
@@ -305,19 +307,29 @@ verify_sig(const fido_blob_t *dgst, const fido_blob_t *x5c,
 	/* fetch key from x509 */
 	if ((rawcert = BIO_new_mem_buf(x5c->ptr, (int)x5c->len)) == NULL ||
 	    (cert = d2i_X509_bio(rawcert, NULL)) == NULL ||
-	    (pkey = X509_get_pubkey(cert)) == NULL ||
-	    (ec = EVP_PKEY_get0_EC_KEY(pkey)) == NULL) {
+	    (pkey = X509_get_pubkey(cert)) == NULL) {
 		log_debug("%s: x509 key", __func__);
 		goto fail;
 	}
 
-	if (ECDSA_verify(0, dgst->ptr, (int)dgst->len, sig->ptr,
-	    (int)sig->len, ec) != 1) {
-		log_debug("%s: ECDSA_verify", __func__);
-		goto fail;
+	if ((ec = EVP_PKEY_get0_EC_KEY(pkey)) != NULL) {
+		if (ECDSA_verify(0, dgst->ptr, (int)dgst->len, sig->ptr,
+		    (int)sig->len, ec) != 1) {
+			log_debug("%s: ECDSA_verify", __func__);
+			goto fail;
+		}
+
+		ok = 0;
+	} else if ((rsa = EVP_PKEY_get0_RSA(pkey)) != NULL) {
+		if (RSA_verify(NID_sha256, dgst->ptr, (unsigned int)dgst->len,
+		    sig->ptr, (unsigned int)sig->len, rsa) != 1) {
+			log_debug("%s: RSA_verify", __func__);
+			goto fail;
+		}
+
+		ok = 0;
 	}
 
-	ok = 0;
 fail:
 	if (rawcert != NULL)
 		BIO_free(rawcert);

**Comment by shimritd** [comment]
does the library downloads and verifies metadata statement?

**Comment by martelletto** [comment]
i am afraid i don't understand your question. i will assume you are 
talking about the verification of the attestation certificate's 
chain of trust.

the library does not download anything, ever. what 
fido_cred_verify() does it to "verify whether the client data hash, 
relying party ID, credential ID, type, and resident key and user 
verification attributes of the credential have been attested by the 
holder of the private counterpart of the public key contained in the 
credential's attestation certificate. Please note that the 
attestation certificate itself is not verified." (adapted from [1]).

[1] https://developers.yubico.com/libfido2/Manuals/fido_cred_verify.html 

-p.

**Comment by shimritd** [comment]
ok, so when i get the attestation object, how do I know if it is FULL or SELF attestation?

**Comment by martelletto** [comment]
the attestation format is defined by the "fmt" attribute of the 
attestation object. in libfido2, this value can be set/retrieved 
through fido_cred_set_fmt() and fido_cred_fmt(). please see 
examples/cred.c for a complete client/server example.

-p.

**Comment by shimritd** [comment]
thanks. 
i know well the cred example, maybe i'm missing something but the fmt value is "packed" as it should be, but there is self packed attestation and full packed attestation and i'm not sure how to identify between the two.

**Comment by martelletto** [comment]
i see. i was talking about attestation formats, whereas your 
question concerned attestation types. given a packed attestation, 
the type is implicitly defined by the contents of the response; if a 
x5c is present, the attestation is of the type "basic"; otherwise, 
the attestation is a self-attestation.

please note that libfido2 has only been tested with packed and 
fido-u2f basic attestations. that said, it would be interesting to 
support self-attestation as well.

-p.

**Comment by shimritd** [comment]
Yes, i was talking about the type, sorry about the confusion...
This is what i'm doing now, i'm checking if the x5c is present but i'm missing cases where it is a full packed attestation and the x5c is missing, in that case, the server should return an error.

**Comment by martelletto** [comment]
ok, glad we are on the same page.is there anything that can objectively be done in libfido2 to help your use case? otherwise i suggest we close this issue. feel free to contact me in private if you want to discuss details of your use case, thoughts, ideas, etc. i am more than happy to help :)
