### ISSUE TITLE
Linker error on tools in Windows

### ISSUE THREAD

**Issue by FabianHenneke** [Yubico/libfido2#181]
**What version of libfido2 are you using?**
Current master (https://github.com/Yubico/libfido2/commit/6f08ddf8b9c4fb9ff1d2f0c2f47b7447aca2eb06)

**What operating system are you running?**
Windows

**What application are you using in conjunction with libfido2?**
None

**How does the problem manifest itself?**
After building libfido2, the tools (e.g., fido2-token) are not functional and produce a linker error when run.

**Is the problem reproducible?**
Yes (at least on my machine)

**What are the steps that lead to the problem?**

Running the following in Powershell (with or without admin rights) will produce no output, not even the usual usage information:

```powershell
git clone https://github.com/Yubico/libfido2
cd libfido2
.\windows\build.ps1
.\output\32\bin\fido2-token.exe
.\output\64\bin\fido2-token.exe
```
Running any of the last commands in `cmd` produces a system error saying that `fido2.dll` was not found.

Note that the examples (e.g. `.\build\32\examples\Release\info.exe`) run fine.

**Does the problem happen with different authenticators?**
n/a

**Comment by martelletto** [comment]
IIRC, build.ps1 copies the required dependencies to ${OUTPUT}/pkg. If you try to run fido2-token.exe from ${OUTPUT}/pkg, what happens?

-p.

**Comment by FabianHenneke** [comment]
Thanks, that works perfectly. Guess I started testing with the examples and then wondered why `fido2-token` behaved differently, but I should have just read the script better.
