### ISSUE TITLE
fido2-token returns FIDO_ERR_UNSUPPORTED_ALGORITHM on a ExcelSecu FIDO2 key

### ISSUE THREAD

**Issue by LockRing** [Yubico/libfido2#185]
**What version of libfido2 are you using?**
1.4.0-3
**What operating system are you running?**
Arch Linux
**What application are you using in conjunction with libfido2?**
fido2-token
**How does the problem manifest itself?**
fido2-token: fido_credman_get_dev_metadata: FIDO_ERR_UNSUPPORTED_ALGORITHM
fido2-token: fido_dev_set_pin: FIDO_ERR_UNSUPPORTED_ALGORITHM ...etc
Every PIN required options fail with FIDO_ERR_UNSUPPORTED_ALGORITHM.
**Is the problem reproducible?**
Run fido2-token with PIN required option.
**What are the steps that lead to the problem?**
Run fido2-token with options like `-C`, `-D`, `-I -c`, `-S`...
**Does the problem happen with different authenticators?**
I don't know, only have ExcelSecu FIDO2 device.

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L
/dev/hidraw5: vendor=0x1ea8, product=0xfc25 (ExcelSecu FIDO2 Security Key)
</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I /dev/hidraw5
proto: 0x02
major: 0x02
minor: 0x00
build: 0x01
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0
extension strings: hmac-secret
aaguid: cdbdaea2c415507350f7c04e968640b6
options: rk, up, noplat, clientPin
maxmsgsiz: 4096
fwversion: 0x0
pin protocols: 1
pin retries: 8
</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ fido2-token -S /dev/hidraw5
fido_tx: d=0x55b1f4cc52a0, cmd=0x06, buf=0x55b1f4cc52a0, count=8
0000: a5 6b 31 c7 98 24 59 f7
fido_rx: d=0x55b1f4cc52a0, cmd=0x06, buf=0x55b1f4cc52a8, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffdec114150
0000: ff ff ff ff 86 00 11 a5 6b 31 c7 98 24 59 f7 00
0016: 00 00 15 02 02 00 01 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x55b1f4cc52a8, len=17
0000: a5 6b 31 c7 98 24 59 f7 00 00 00 15 02 02 00 01
0016: 05
fido_dev_get_cbor_info_tx: dev=0x55b1f4cc52a0
fido_tx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x7ffdec1141b7, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x55b1f4cc52a0, ci=0x55b1f4cc5330, ms=-1
fido_rx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x7ffdec113cc0, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffdec113c30
0000: 00 00 00 15 90 00 56 00 a6 01 82 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 02 81 6b 68 6d
0032: 61 63 2d 73 65 63 72 65 74 03 50 cd bd ae a2 c4
0048: 15 50 73 50 f7 c0 4e 96 86 40 b6 04 a4 62 72 6b
rx: payload_len=86
rx: continuation frame at 0x7ffdec113c30
0000: 00 00 00 15 00 f5 62 75 70 f5 64 70 6c 61 74 f4
0016: 69 63 6c 69 65 6e 74 50 69 6e f5 05 19 10 00 06
0032: 81 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffdec113cc0, len=86
0000: 00 a6 01 82 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 02 81 6b 68 6d 61 63 2d 73 65 63 72
0032: 65 74 03 50 cd bd ae a2 c4 15 50 73 50 f7 c0 4e
0048: 96 86 40 b6 04 a4 62 72 6b f5 62 75 70 f5 64 70
0064: 6c 61 74 f4 69 63 6c 69 65 6e 74 50 69 6e f5 05
0080: 19 10 00 06 81 01
fido_dev_open_rx: FIDO_MAXMSG=1200, maxmsgsiz=4096
Enter new PIN for /dev/hidraw5: 
Enter the same PIN again: 
fido_dev_authkey_tx: dev=0x55b1f4cc52a0
fido_tx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x55b1f4cc6af0, count=6
0000: 06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0x55b1f4cc52a0, authkey=0x55b1f4cc8050, ms=-1
fido_rx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x7ffdec113be0, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffdec113b50
0000: 00 00 00 15 90 00 51 00 a1 01 a5 01 02 03 38 18
0016: 20 01 21 58 20 10 15 7b 78 68 e8 4a 45 e7 cd c7
0032: d7 36 e4 f0 a6 8e 17 9b 6e 26 ba 15 8b 78 5b 51
0048: 0e 6b 8f 36 57 22 58 20 00 66 7d 9f f0 ea d2 72
rx: payload_len=81
rx: continuation frame at 0x7ffdec113b50
0000: 00 00 00 15 00 19 7e 21 78 d6 30 ff f9 55 89 aa
0016: 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c 10 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffdec113be0, len=81
0000: 00 a1 01 a5 01 02 03 38 18 20 01 21 58 20 10 15
0016: 7b 78 68 e8 4a 45 e7 cd c7 d7 36 e4 f0 a6 8e 17
0032: 9b 6e 26 ba 15 8b 78 5b 51 0e 6b 8f 36 57 22 58
0048: 20 00 66 7d 9f f0 ea d2 72 19 7e 21 78 d6 30 ff
0064: f9 55 89 aa 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c
0080: 10
fido_tx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x55b1f4cc8730, count=169
0000: 06 a5 01 01 02 03 03 a5 01 02 03 26 20 01 21 58
0016: 20 66 cd f6 a1 53 f5 64 59 aa 51 2a 72 f0 81 80
0032: d6 29 73 1f 7e 81 4e 7b 4d 93 9d f3 ba 44 99 39
0048: 76 22 58 20 85 28 f0 74 70 bb f7 9c 4b ee d1 0f
0064: 80 4d 91 5b da 86 d3 29 fd d6 2d bc 72 64 38 61
0080: 31 f6 72 67 04 50 a2 07 26 43 b9 ff 94 dc 32 5f
0096: 08 eb f3 05 d2 79 05 58 40 b0 3b 0c 2c 28 3a cd
0112: 21 2f fb 50 d6 c1 ff f0 be 78 56 ab ee 9b fc d6
0128: dc 53 9e 4a 0b a8 15 6d 10 b8 38 2f 1a 9b fb 82
0144: fe 2f 3e 8d d0 b3 19 58 7d aa 0a 90 b0 b7 51 a1
0160: c3 5b 11 95 55 cb 53 e9 51
fido_rx: d=0x55b1f4cc52a0, cmd=0x10, buf=0x7ffdec113cc0, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffdec113c30
0000: 00 00 00 15 90 00 01 26 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0x7ffdec113cc0, len=1
0000: 26
fido_dev_set_pin_wait: fido_rx_cbor_status
fido2-token: fido_dev_set_pin: FIDO_ERR_UNSUPPORTED_ALGORITHM
$ fido2-token -C /dev/hidraw5
fido_tx: d=0x55d3fbc862a0, cmd=0x06, buf=0x55d3fbc862a0, count=8
0000: da 57 d1 96 a2 7c e3 04
fido_rx: d=0x55d3fbc862a0, cmd=0x06, buf=0x55d3fbc862a8, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffe8d92df00
0000: ff ff ff ff 86 00 11 da 57 d1 96 a2 7c e3 04 00
0016: 00 00 16 02 02 00 01 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x55d3fbc862a8, len=17
0000: da 57 d1 96 a2 7c e3 04 00 00 00 16 02 02 00 01
0016: 05
fido_dev_get_cbor_info_tx: dev=0x55d3fbc862a0
fido_tx: d=0x55d3fbc862a0, cmd=0x10, buf=0x7ffe8d92df67, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x55d3fbc862a0, ci=0x55d3fbc86330, ms=-1
fido_rx: d=0x55d3fbc862a0, cmd=0x10, buf=0x7ffe8d92da70, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffe8d92d9e0
0000: 00 00 00 16 90 00 56 00 a6 01 82 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 02 81 6b 68 6d
0032: 61 63 2d 73 65 63 72 65 74 03 50 cd bd ae a2 c4
0048: 15 50 73 50 f7 c0 4e 96 86 40 b6 04 a4 62 72 6b
rx: payload_len=86
rx: continuation frame at 0x7ffe8d92d9e0
0000: 00 00 00 16 00 f5 62 75 70 f5 64 70 6c 61 74 f4
0016: 69 63 6c 69 65 6e 74 50 69 6e f5 05 19 10 00 06
0032: 81 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffe8d92da70, len=86
0000: 00 a6 01 82 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 02 81 6b 68 6d 61 63 2d 73 65 63 72
0032: 65 74 03 50 cd bd ae a2 c4 15 50 73 50 f7 c0 4e
0048: 96 86 40 b6 04 a4 62 72 6b f5 62 75 70 f5 64 70
0064: 6c 61 74 f4 69 63 6c 69 65 6e 74 50 69 6e f5 05
0080: 19 10 00 06 81 01
fido_dev_open_rx: FIDO_MAXMSG=1200, maxmsgsiz=4096
Enter current PIN for /dev/hidraw5: 
Enter new PIN for /dev/hidraw5: 
Enter the same PIN again: 
fido_dev_authkey_tx: dev=0x55d3fbc862a0
fido_tx: d=0x55d3fbc862a0, cmd=0x10, buf=0x55d3fbc87b30, count=6
0000: 06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0x55d3fbc862a0, authkey=0x55d3fbc89090, ms=-1
fido_rx: d=0x55d3fbc862a0, cmd=0x10, buf=0x7ffe8d92d990, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffe8d92d900
0000: 00 00 00 16 90 00 51 00 a1 01 a5 01 02 03 38 18
0016: 20 01 21 58 20 10 15 7b 78 68 e8 4a 45 e7 cd c7
0032: d7 36 e4 f0 a6 8e 17 9b 6e 26 ba 15 8b 78 5b 51
0048: 0e 6b 8f 36 57 22 58 20 00 66 7d 9f f0 ea d2 72
rx: payload_len=81
rx: continuation frame at 0x7ffe8d92d900
0000: 00 00 00 16 00 19 7e 21 78 d6 30 ff f9 55 89 aa
0016: 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c 10 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffe8d92d990, len=81
0000: 00 a1 01 a5 01 02 03 38 18 20 01 21 58 20 10 15
0016: 7b 78 68 e8 4a 45 e7 cd c7 d7 36 e4 f0 a6 8e 17
0032: 9b 6e 26 ba 15 8b 78 5b 51 0e 6b 8f 36 57 22 58
0048: 20 00 66 7d 9f f0 ea d2 72 19 7e 21 78 d6 30 ff
0064: f9 55 89 aa 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c
0080: 10
fido_tx: d=0x55d3fbc862a0, cmd=0x10, buf=0x55d3fbc897b0, count=187
0000: 06 a6 01 01 02 04 03 a5 01 02 03 26 20 01 21 58
0016: 20 f2 b6 a7 42 3b 16 cf 4f 0a 3b 18 78 d7 6a 24
0032: 37 f8 ec 8e d5 99 80 1f 24 b6 20 80 11 44 6c af
0048: ea 22 58 20 a3 cc 4c 89 a2 35 7d ff 3e 6f 1d 78
0064: 98 95 fd d0 4b ab b6 1c b4 95 ad a3 8f dc a2 a6
0080: ac 9a 51 c1 04 50 ab d7 f4 29 35 a1 8d 5b 40 6b
0096: 42 d1 d3 8e 09 34 05 58 40 14 ab 7f a9 8c a3 d9
0112: c2 17 66 62 00 39 56 c7 6c 3a 69 89 67 96 29 60
0128: ce 95 82 2b 11 b3 2e 1e d0 c7 29 f7 88 30 43 b9
0144: b3 15 a4 58 ed ba a6 21 ec e1 49 bb 26 65 fa af
0160: 30 1f c2 a8 e2 ab fd 96 92 06 50 26 5c 82 9c db
0176: 09 2a 51 b9 57 8e 21 b5 e1 17 c5
fido_rx: d=0x55d3fbc862a0, cmd=0x10, buf=0x7ffe8d92da70, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffe8d92d9e0
0000: 00 00 00 16 90 00 01 26 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0x7ffe8d92da70, len=1
0000: 26
fido_dev_set_pin_wait: fido_rx_cbor_status
fido2-token: fido_dev_set_pin: FIDO_ERR_UNSUPPORTED_ALGORITHM
$ fido2-token -I -c /dev/hidraw5
fido_tx: d=0x55563fbe72a0, cmd=0x06, buf=0x55563fbe72a0, count=8
0000: d2 f6 de 9f 1a af d1 62
fido_rx: d=0x55563fbe72a0, cmd=0x06, buf=0x55563fbe72a8, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffd681254e0
0000: ff ff ff ff 86 00 11 d2 f6 de 9f 1a af d1 62 00
0016: 00 00 18 02 02 00 01 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x55563fbe72a8, len=17
0000: d2 f6 de 9f 1a af d1 62 00 00 00 18 02 02 00 01
0016: 05
fido_dev_get_cbor_info_tx: dev=0x55563fbe72a0
fido_tx: d=0x55563fbe72a0, cmd=0x10, buf=0x7ffd68125547, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x55563fbe72a0, ci=0x55563fbe7330, ms=-1
fido_rx: d=0x55563fbe72a0, cmd=0x10, buf=0x7ffd68125050, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffd68124fc0
0000: 00 00 00 18 90 00 56 00 a6 01 82 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 02 81 6b 68 6d
0032: 61 63 2d 73 65 63 72 65 74 03 50 cd bd ae a2 c4
0048: 15 50 73 50 f7 c0 4e 96 86 40 b6 04 a4 62 72 6b
rx: payload_len=86
rx: continuation frame at 0x7ffd68124fc0
0000: 00 00 00 18 00 f5 62 75 70 f5 64 70 6c 61 74 f4
0016: 69 63 6c 69 65 6e 74 50 69 6e f5 05 19 10 00 06
0032: 81 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffd68125050, len=86
0000: 00 a6 01 82 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 02 81 6b 68 6d 61 63 2d 73 65 63 72
0032: 65 74 03 50 cd bd ae a2 c4 15 50 73 50 f7 c0 4e
0048: 96 86 40 b6 04 a4 62 72 6b f5 62 75 70 f5 64 70
0064: 6c 61 74 f4 69 63 6c 69 65 6e 74 50 69 6e f5 05
0080: 19 10 00 06 81 01
fido_dev_open_rx: FIDO_MAXMSG=1200, maxmsgsiz=4096
Enter PIN for /dev/hidraw5: 
fido_dev_authkey_tx: dev=0x55563fbe72a0
fido_tx: d=0x55563fbe72a0, cmd=0x10, buf=0x55563fbe8ac0, count=6
0000: 06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0x55563fbe72a0, authkey=0x55563fbea020, ms=-1
fido_rx: d=0x55563fbe72a0, cmd=0x10, buf=0x7ffd68124ae0, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffd68124a50
0000: 00 00 00 18 90 00 51 00 a1 01 a5 01 02 03 38 18
0016: 20 01 21 58 20 10 15 7b 78 68 e8 4a 45 e7 cd c7
0032: d7 36 e4 f0 a6 8e 17 9b 6e 26 ba 15 8b 78 5b 51
0048: 0e 6b 8f 36 57 22 58 20 00 66 7d 9f f0 ea d2 72
rx: payload_len=81
rx: continuation frame at 0x7ffd68124a50
0000: 00 00 00 18 00 19 7e 21 78 d6 30 ff f9 55 89 aa
0016: 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c 10 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffd68124ae0, len=81
0000: 00 a1 01 a5 01 02 03 38 18 20 01 21 58 20 10 15
0016: 7b 78 68 e8 4a 45 e7 cd c7 d7 36 e4 f0 a6 8e 17
0032: 9b 6e 26 ba 15 8b 78 5b 51 0e 6b 8f 36 57 22 58
0048: 20 00 66 7d 9f f0 ea d2 72 19 7e 21 78 d6 30 ff
0064: f9 55 89 aa 05 b2 68 5a 32 9f 5e 07 86 d2 1c 6c
0080: 10
fido_tx: d=0x55563fbe72a0, cmd=0x10, buf=0x55563fbe73e0, count=102
0000: 06 a4 01 01 02 05 03 a5 01 02 03 26 20 01 21 58
0016: 20 92 74 b6 12 76 79 81 0c 6d d6 38 52 1e 92 34
0032: eb 0f 7e 82 83 b6 44 7e 6f 54 9a a3 1c 24 34 cd
0048: 66 22 58 20 97 f5 f6 5c 8c 2f ae 63 fe 61 af d8
0064: dc f9 07 f1 82 a8 e3 c1 dd 5a 99 8d 08 34 dc 39
0080: 6b a0 95 cf 06 50 8a 22 61 bd a6 11 c5 ff f2 bd
0096: ab e7 e1 2f 11 db
fido_rx: d=0x55563fbe72a0, cmd=0x10, buf=0x7ffd68124a80, count=1200, ms=-1
rx_preamble: initiation frame at 0x7ffd681249e0
0000: 00 00 00 18 90 00 01 26 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0x7ffd68124a80, len=1
0000: 26
cbor_parse_reply: blob[0]=0x26
fido_dev_get_pin_token_rx: parse_pintoken
cbor_add_pin_params: fido_dev_get_pin_token
credman_tx: cbor_add_pin_params
fido2-token: fido_credman_get_dev_metadata: FIDO_ERR_UNSUPPORTED_ALGORITHM

</pre>
</details>

`-R`,`-I`,`-L` options work as expected. In Chromium it could set PIN and register without problem.

**Comment by martelletto** [comment]
Hi,

This looks like https://github.com/Yubico/libfido2/issues/154, which 
was fixed in d7ca3225.

-p.

**Comment by LockRing** [comment]
Thank you for answering,
I tested it with the master branch, the key setup and change worked fine. Now other options(like `-L -r`, `-L -k`) return FIDO_ERR_INVALID_COMMAND, it just my device doesn't support that command I think.

Sorry to have bothered you. I'll close this issue.

**Comment by martelletto** [comment]
No worries, and thank you for the comprehensive bug report.

Yes, your authenticator does not seem to support credential 
management.

-p.
