### ISSUE TITLE
undefined reference to `fido_dev_new_with_info'

### ISSUE THREAD

**Issue by tarun14110** [Yubico/libfido2#186]
I am using the static library `libfido2.a` for my project. `manifest.cpp` is running great. I am getting an error while running cred.cpp

> undefined reference to `fido_dev_new_with_info'

> undefined reference to `fido_dev_open_with_info'

I think the header "fido.h" is working fine, as other functions are accessible. Is there another header that is required for these functions?

cred.cpp
```
#include "fido.h"
#include "cred.h"
static fido_dev_t * open_from_manifest(const fido_dev_info_t *dev_infos, size_t len, const char *path) {}
void fido2_cred() {}
```

cred.h
```
#ifndef CRED_H_
#define CRED_H_
#ifdef __cplusplus
extern "C" {
#endif
void fido2_cred();
#ifdef __cplusplus
}
#endif
#endif /* CRED_H_ */
```

**Comment by martelletto** [comment]
Hi,

fido.h should be enough to get the functions prototyped. The problem 
you describe appears linking related. How are you building and 
linking cred.cpp?

-p.

**Comment by tarun14110** [comment]
I am getting the same error while compiling the cred.c from example. I am using this command `gcc cred.c -L../src -lfido2`. I'm surely missing something here.

**Comment by martelletto** [comment]
It looks like you are linking against the shared library, where 
fido_dev_new_with_info() and fido_dev_open_with_info() are not 
marked as exported symbols.

To link against the static library, pass cc the path to the .a as 
you would pass the path of an object to be linked, and omit -lfido2:

$ cc foo.o bar.o -o a.out /path/to/libfido2.a -lcbor -lcrypto -ludev

Alternatively, you can link against the static versions of libcbor, 
libcrypto, and libudev.

-p.

**Comment by tarun14110** [comment]
Thanks for the quick reply. It makes much more sense. I'm getting a different set of linking error now.
`gcc cred.c -o cred ../build/src/libfido2.a -lcbor -lcrypto -ludev`

```
/usr/local/bin/ld: ../build/src/libfido2.a(es256.c.o): in function `es256_sk_create':
es256.c:(.text+0x8fd): undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/bin/ld: ../build/src/libfido2.a(assert.c.o): in function `fido_verify_sig_es256':
assert.c:(.text+0x1291): undefined reference to `EVP_PKEY_get0_EC_KEY'
/usr/local/bin/ld: ../build/src/libfido2.a(assert.c.o): in function `fido_verify_sig_rs256':
assert.c:(.text+0x13ff): undefined reference to `EVP_PKEY_get0_RSA'
/usr/local/bin/ld: ../build/src/libfido2.a(assert.c.o): in function `fido_verify_sig_eddsa':
assert.c:(.text+0x157f): undefined reference to `EVP_MD_CTX_new'
/usr/local/bin/ld: assert.c:(.text+0x1615): undefined reference to `EVP_DigestVerify'
/usr/local/bin/ld: assert.c:(.text+0x164e): undefined reference to `EVP_MD_CTX_free'
/usr/local/bin/ld: ../build/src/libfido2.a(cbor.c.o): in function `cbor_encode_change_pin_auth':
cbor.c:(.text+0x1d4e): undefined reference to `HMAC_CTX_new'
/usr/local/bin/ld: cbor.c:(.text+0x1ea1): undefined reference to `HMAC_CTX_free'
/usr/local/bin/ld: ../build/src/libfido2.a(eddsa.c.o): in function `eddsa_pk_to_EVP_PKEY':
eddsa.c:(.text+0x341): undefined reference to `EVP_PKEY_new_raw_public_key'
/usr/local/bin/ld: ../build/src/libfido2.a(eddsa.c.o): in function `eddsa_pk_from_EVP_PKEY':
eddsa.c:(.text+0x3ba): undefined reference to `EVP_PKEY_get_raw_public_key'
/usr/local/bin/ld: eddsa.c:(.text+0x3e7): undefined reference to `EVP_PKEY_get_raw_public_key'
/usr/local/bin/ld: ../build/src/libfido2.a(rs256.c.o): in function `rs256_pk_to_EVP_PKEY':
rs256.c:(.text+0x41b): undefined reference to `RSA_set0_key'
/usr/local/bin/ld: ../build/src/libfido2.a(rs256.c.o): in function `rs256_pk_from_RSA':
rs256.c:(.text+0x555): undefined reference to `RSA_bits'
/usr/local/bin/ld: rs256.c:(.text+0x596): undefined reference to `RSA_get0_key'
collect2: error: ld returned 1 exit status
```

**Comment by martelletto** [comment]
It looks like you are linking against a different version of 
libcrypto than that indicated by OPENSSL_VERSION_NUMBER or 
LIBRESSL_VERSION_NUMBER.

I suggest you compare the output of:

$ ldconfig -p | grep libcrypto

with the output of

$ echo '#include <openssl/opensslv.h>' | cc -dM -E - | grep OPENSSL_VERSION_NUMBER

-p.

**Comment by tarun14110** [comment]
```
$ ldconfig -p | grep libcrypto
libcrypto.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
libcrypto.so.1.0.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
libcrypto.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcrypto.so

$ echo '#include <openssl/opensslv.h>' | cc -dM -E - | grep OPENSSL_VERSION_NUMBER
#define OPENSSL_VERSION_NUMBER 0x100020efL
```

**Comment by martelletto** [comment]
ok, libfido2 was linked against OpenSSL 1.1 and cred.o is being 
linked against OpenSSL 1.0. You can replace -lcrypto with 
-l:libcrypto.so.1.1. If it links, make sure to check with ldd cred 
that libcrypto.so.1.1 is being picked up by ld.so, or you might have 
problems executing the binary.

-p.

**Comment by sb230132** [comment]
Hi,
Iam getting same error where iam linking against dynamic library.

/opt/rh/devtoolset-9/root/usr/bin/gcc -fno-omit-frame-pointer -ftls-model=initial-exec  -Wall -Wextra -Werror -Wshadow -Wwrite-strings -Wmissing-prototypes -Wbad-function-cast -pedantic -pedantic-errors -fstack-protector-all -std=c99 -Wno-unused-result -Wcast-qual -DSAFE_MUTEX -DENABLED_DEBUG_SYNC -g -g2 -fno-omit-frame-pointer  -fuse-ld=gold -Wl,--gc-sections  -Wl,-z,noexecstack -Wl,-z,relro,-z,now CMakeFiles/cred.dir/cred.c.o CMakeFiles/cred.dir/util.c.o CMakeFiles/cred.dir/__/openbsd-compat/clock_gettime.c.o CMakeFiles/cred.dir/__/openbsd-compat/getopt_long.c.o CMakeFiles/cred.dir/__/openbsd-compat/strlcat.c.o CMakeFiles/cred.dir/__/openbsd-compat/strlcpy.c.o  -o cred  -L/export/home/tmp/bhsatish/trunk_fido/build/extra/libcbor -Wl,-rpath,/export/home/tmp/bhsatish/trunk_fido/build/extra/libcbor:/export/home/tmp/bhsatish/trunk_fido/build/extra/libfido2/src -lpthread **../src/libfido2.so.1.5.0** ../../libcbor/src/libcbor.a -lpthread -lcrypto -ludev -lrt 
/export/home/tmp/bhsatish/trunk_fido/extra/libfido2/examples/cred.c:148: error: undefined reference to 'fido_dev_new_with_info'
/export/home/tmp/bhsatish/trunk_fido/extra/libfido2/examples/cred.c:149: error: undefined reference to 'fido_dev_open_with_info'

Any specific reason we are not exporting the above symbols ?

Thanks.

**Comment by martelletto** [comment]
Hi,

These functions are not yet part of the official public API. If you need them, please link statically.

-p.

**Comment by sb230132** [comment]
Hi,
Yes, i can see that the issues is resolved if i link statically. Just curious to know if there is any technical reason for not exposing these 2 APIs ?

To integrate fido library, i need to know how stable it is. Thats the reason iam asking.

**Comment by martelletto** [comment]
No problem; feel free to ask. The main reason is that they are not documented. They certainly won't disappear in a future release, and their long-term existence can be relied on.

**Comment by sb230132** [comment]
Is there any problem if i expose them and link dynamically with my application ?

**Comment by martelletto** [comment]
If you are building and packaging libfido2 yourself, there is no risk.

**Comment by sb230132** [comment]
Great, thanks.
