### ISSUE TITLE
Generate attestation object 

### ISSUE THREAD

**Issue by tarun14110** [Yubico/libfido2#187]
Is there an API to create the whole attestation object along with the CBOR canonical encoding? I'm able to get the individual parts like authData, signature. I'm trying to create my attestation object, but due to inexperience in C ends up in some issues due to encodings or incorrect formation.   

I have a javascript module that relays communication between server and this library. So, I want to create the complete PublicKeyCredential object for the webserver and send it to my js module. If there is no straight forward way, one alternate I can think of is sending individual parts like authData to js module and create the PublicKeyCredential object over there.

**Comment by martelletto** [comment]
Hi,

The closest you will find in libfido2 is code to do the reverse 
operation, i.e. decode an attestation object:

https://github.com/Yubico/libfido2/blob/fe0d820/src/cred.c#L16-L40

To create a new attestation object, you could use something like 
this:

cbor_item_t *attestation_statement, *x5c_array;
struct cbor_pair alg, sig, x5c;

/* alg */
alg.key = cbor_build_string("alg");
alg.value = cbor_build_negint8(-COSE_ES256 -1);

/* sig */
sig.key = cbor_build_string("sig");
sig.value = cbor_build_bytestring(sig_ptr, sig_len);

/* x5c */
x5c_array = cbor_new_definite_array(1);
cbor_array_push(x5c_array, cbor_build_bytestring(x5c_ptr, x5c_len));
x5c.key = cbor_build_string("x5c");
x5c.value = x5c_array;

/* attestation statement */
attestation_statement = cbor_new_definite_map(3);

cbor_map_add(attestation_statement, alg);
cbor_map_add(attestation_statement, sig);
cbor_map_add(attestation_statement, x5c);

(...)

cbor_item_t *attestation_object;

struct cbor_pair fmt;
struct cbor_pair authdata;
struct cbor_pair statement;

/* fmt */
fmt.key = cbor_build_uint8(1);
fmt.value = cbor_build_string("packed");

/* authdata */
authdata.key = cbor_build_uint8(2);
authdata.value = cbor_build_bytestring(authdata_ptr, authdata_len);

/* attestation statement */
statement.key = cbor_build_uint8(3);
statement.value = attestation_statement;

/* attestation object */
attestation_object = cbor_new_definite_map(3);

cbor_map_add(attestation_object, fmt);
cbor_map_add(attestation_object, authdata);
cbor_map_add(attestation_object, station_statement)

(...)

unsigned char *cbor;
size_t cbor_len, cbor_alloc_len;

cbor_len = cbor_serialize_alloc(attestation_object, &cbor, 
    &cbor_alloc_len);

Please make sure to add proper error checking and resource 
deallocation.

In the future, feel free to reach out directly to me (my e-mail 
address is all over git history); I am always willing to help. This 
helps ensure we keep noise at a minimum for the folks watching the 
repo.

-p.

**Comment by tarun14110** [comment]
Thanks a lot. I'll ping you over email to follow up on this one :)

**Comment by martelletto** [comment]
For reference, an implementation of a basic WebAuthn client using libfido2 (including code to generate an attestation object) can be found at https://git.sr.ht/~pedro/fido2-webauthn-client.
