### ISSUE TITLE
Time for a new tag - so other package managers like homebrew for macOS can pickup important fixes?

### ISSUE THREAD

**Issue by stohn** [Yubico/libfido2#191]
I have a FIDO2 usb security key which is not working with the currently tagged 1.4 version of libfido2.

However there was a commit d7ca32255e7052dedbbf96c46b20f84418247b19 some time ago which fixes the issue and everything seems to work fine when I manually compile libfido2 from current master branch).

Since most users use package managers to install software (e.g. on macOS: `brew install openssh`) which most of the time use releases (tagged versions) a new tag for libfido2 with the fix would be nice and convenient.

Thanks

**Comment by martelletto** [comment]
Hi,

The next release of libfido2 is scheduled for September. Apologies 
for the inconvenience.

-p.

**Comment by stohn** [comment]
Just saw version 1.5.0 came out. Closing this one. Thanks.
