### ISSUE TITLE
fido2-cred: fido_dev_make_cred: FIDO_ERR_RX error

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#195]
Hello all,

Device details:
./manifest
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/Yubikey 4 OTP+U2F+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice
: vendor=0x1050
, product=0x0407
 (Yubico 
 Yubikey 4 OTP+U2F+CCID)

./tools/fido2-token -V
1.5.0

Iam stuck with below issue when running fido2-cred program.

client data hash:
  61 2e ef 12 ca 69 87 b3 16 c0 61 8b 3a 24 21 a4 
  3c 7e 59 8c 8a 99 2f 3a 44 e1 85 3c 3f 7d 02 71 
relying party id: MySql_server
user name: satish
user id:
  a9 94 44 67 72 9b 89 63 df fe 71 d9 1a 33 56 b0 
  45 3a a3 1f 44 41 69 2f 0c 6d c3 31 50 d3 97 58 
fido_tx: d=0x10040d4f0, cmd=0x06, buf=0x10040d4f0, count=8
0000: b1 67 4c a8 1e d0 5b b3
fido_rx: d=0x10040d4f0, cmd=0x06, buf=0x10040d4f8, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffeefbfef98
0000: ff ff ff ff 86 00 11 b1 67 4c a8 1e d0 5b b3 00
0016: 0e 00 05 02 04 04 05 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x10040d4f8, len=17
0000: b1 67 4c a8 1e d0 5b b3 00 0e 00 05 02 04 04 05
0016: 05
fido_dev_get_cbor_info_tx: dev=0x10040d4f0
fido_tx: d=0x10040d4f0, cmd=0x10, buf=0x7ffeefbfeff7, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x10040d4f0, ci=0x100704cd0, ms=-1
fido_rx: d=0x10040d4f0, cmd=0x10, buf=0x7ffeefbfe7f0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffeefbfe708
0000: 00 0e 00 05 bf 00 01 01 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx_preamble: cid (0x5000e00, 0x5000e00), cmd (0xbf, 0x10)
rx: rx_preamble
fido_dev_get_cbor_info_rx: fido_rx
fido_dev_open_rx: falling back to u2f
fido_tx: d=0x10040d4f0, cmd=0x03, buf=0x10050ad12, count=73
0000: 00 01 00 00 00 00 40 61 2e ef 12 ca 69 87 b3 16
0016: c0 61 8b 3a 24 21 a4 3c 7e 59 8c 8a 99 2f 3a 44
0032: e1 85 3c 3f 7d 02 71 0d 31 a3 90 f6 b3 03 1e 95
0048: 71 4d af 5d 73 95 5d b1 b1 c3 57 17 c3 3b 0f b5
0064: 78 e9 21 07 9a 1c 6a 00 00
fido_rx: d=0x10040d4f0, cmd=0x03, buf=0x7ffeefbfe8e0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffeefbfe7c8
0000: 00 0e 00 05 83 00 02 63 c0 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=2
fido_rx: buf=0x7ffeefbfe8e0, len=2
0000: 63 c0
parse_register_reply: unexpected sw
u2f_register: parse_register_reply
fido2-cred: fido_dev_make_cred: FIDO_ERR_RX

Also where can i find details about what these calls are doing
fido_tx, fido_rx etc..

**Comment by martelletto** [comment]
Hi,

You appear to be using a FIPS device with a U2F PIN set; please see https://support.yubico.com/support/solutions/articles/15000011059-yubikey-fips-series-technical-manual#2.5.2_Placing_the_U2F_Sub-Module_in_FIPS_Approved_Modevt1k5.

-p.

**Comment by sb230132** [comment]
Hi,
Thanks for your quick reply.
I dont get what you mean.
I have reset the device using Yubico Authenticator.

~Thanks

**Comment by martelletto** [comment]
The issue is unrelated to Yubico Authenticator. The U2F module of your FIPS key is protected by a PIN. You will need to use YubiKey Manager's CLI (ykman) and the PIN to unlock the key before you are able to do a U2F registration with fido2-cred. The steps are described in the document linked to above. If that doesn't help, please open a support ticket at https://support.yubico.com/support/tickets/new.

**Comment by sb230132** [comment]
Ok.
I downloaded yubikey manager and in Applications menu i see OTP and PIV enabled, FIDO2 is disabled which i think should not be an issue. Now i clicked PIV and then did a reset PIV. Attaching a screen shot.

![Screenshot 2020-07-28 at 5 48 11 PM](https://user-images.githubusercontent.com/6995422/88664372-9c3f0a80-d0fa-11ea-8eff-072f69e6762c.png)

What i noticed is the response from the device does not seem to be correct.
fido_rx: buf=0x7ffeefbfe860, len=2
0000: 63 c0
This i think is a 16bit Status word (
#define SW_CONDITIONS_NOT_SATISFIED	0x6985
#define SW_WRONG_DATA			0x6a80
#define SW_NO_ERROR			0x9000

https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#u2f-response-message-framing
In this link i see that
Each implementation may define any other vendor-specific status codes...
Does this mean that libfido2 is adding its own status words ?

Anything else i can do to further proceed on this. Your help is much appreciated.

**Comment by martelletto** [comment]
PIV is a different application/module than U2F. You can install YubiKey Manager CLI on macOS with:

``` $ brew install ykman``` 

Once that is done, you can unlock the key using the Admin PIN:

```$ ykman fido unlock -P <Admin PIN>``` 

If you do not power-cycle the key, you should now be able to perform a U2F registration using fido2-cred or a browser.

Please note that this is completely outside the scope of this forum. For help understanding your key and what it can do, please contact Yubico Support.

-p.

**Comment by sb230132** [comment]
Ok, thanks for your time. I will close the issue.
