### ISSUE TITLE
build on openbsd

### ISSUE THREAD

**Issue by edgarpettijohn** [Yubico/libfido2#2]
I'm attempting to build on OpenBSD 6.3 and I'm getting the following error.

CMake Error at /usr/local/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'hidapi' found

However, hidapi is installed as well as cbor.

laptop$ ls /usr/local/lib | grep hidapi
libhidapi.a
libhidapi.la
libhidapi.so.0.0

laptop$ ls /usr/local/lib | grep cbor
libcbor.a
libcbor.so.0.0

Unfortunantly I'm not well versed in cmake, so I'm not sure where to look to make changes to how it determines that it isn't installed.  Any help appreciated.

**Comment by martelletto** [comment]
Hi,

Is devel/pkgconfig (from ports) installed? If so, what is the output 
of pkg-config --list-all | grep hidapi?

-p.

**Comment by edgarpettijohn** [comment]
hidapi's makefile installed the hidapi.pc file to the "wrong" location.

**Comment by martelletto** [comment]
thanks for the info. i was able to replicate your results (with the 
difference that i used the libhidapi port from openbsd -current 
[1]). libfido2 builds, but does not work. i am unable to list or 
talk to tokens. does that work for you?

-p.

[1] http://ports.su/comms/libhidapi

**Comment by edgarpettijohn** [comment]
Unfortunately I can't test yet. I ordered a yubikey so I'm just getting prepared to play with it.
