### ISSUE TITLE
cred.exe run failed

### ISSUE THREAD

**Issue by PhoenixBaymax** [Yubico/libfido2#20]
I run windows/build.bat, and create vs2017 project and get cred.exe,but it crash.I found the reason is fclose(fp) in example/util.c,if I comment the statement,it run good,but it run good on Ubuntu.

**Comment by martelletto** [comment]
Hi,

Which version of libfido2 are you running? There were a few changes 
in that area between the last released version (0.4.0) and HEAD.

-p.

**Comment by PhoenixBaymax** [comment]
I tried again that use the latest version code.If I choose debug model, it work good,but if choose release model,the probelm occur that the libcbor and libress both are release lib.

**Comment by martelletto** [comment]
Hi,

Thanks for testing. Just to confirm my understanding:

- The crash you were seeing is gone with HEAD;
- You are now experiencing a different problem when you set 
  CMAKE_BUILD_TYPE to 'Release'.

If these statements are correct, what is the problem you see when 
you set CMAKE_BUILD_TYPE to 'Release'?

-p.

**Comment by PhoenixBaymax** [comment]
I git clone code in 2019/03/19,describe my problem with some pictures.
The picture of code:
![code](https://user-images.githubusercontent.com/5435863/54741266-ece64f80-4bf8-11e9-9752-ada8a31c2ba3.JPG)
debug .exe run in cmd:
![debug_model_run](https://user-images.githubusercontent.com/5435863/54741341-25862900-4bf9-11e9-90a7-66254a7b83c1.JPG)
release .exe run in cmd:
![release_model_run](https://user-images.githubusercontent.com/5435863/54741361-3171eb00-4bf9-11e9-98b7-2320725d2e4a.JPG)

By compairing the last pictures,you maybe unstander my problem!

**Comment by martelletto** [comment]
Hi,

Thank you for the screenshots. I will try to reproduce the problem 
locally. Which version of Windows are you running?

-p.

**Comment by PhoenixBaymax** [comment]
OS: Windows10 v1809 17763.379.
If u need my project built,I can send u.

**Comment by martelletto** [comment]
Sure, that would be appreciated!

-p.

**Comment by PhoenixBaymax** [comment]
what`s your email address?

**Comment by martelletto** [comment]
pedro at yubico dot com

-p.

**Comment by PhoenixBaymax** [comment]
I had sent email to u.

**Comment by martelletto** [comment]
Hi,

I cannot reproduce the problem. As an extra data point, what happens 
if you comment the calls to fclose()? Do 'cred.exe' and 'assert.exe' 
work as expected? Is the pubkey file written successfully?

-p.

**Comment by PhoenixBaymax** [comment]
Sorry, please see pics below:
![debug](https://user-images.githubusercontent.com/5435863/54804459-86236d80-4cae-11e9-87c8-8ac255b6fc40.JPG)
![release](https://user-images.githubusercontent.com/5435863/54804463-89b6f480-4cae-11e9-92be-9db8aa428a8f.JPG)

**Comment by martelletto** [comment]
Thank you for the detailed screenshots. I was able to reproduce the 
problem; I will investigate it and get back to you shortly.

-p.

**Comment by PhoenixBaymax** [comment]
I found another problem about assert.exe in release model, please see pics blow!
![1_debug](https://user-images.githubusercontent.com/5435863/54814725-45861d00-4ccb-11e9-849f-df9e40e499fa.JPG)
![1_release](https://user-images.githubusercontent.com/5435863/54814727-45861d00-4ccb-11e9-8337-d0aba46673ff.JPG)

**Comment by martelletto** [comment]
Thank you. I think I know what the problem is. On release builds, we 
are linking against MSVCRTD (Microsoft's debug C runtime) when we 
should be linking against MSVCRT (the release run time).

To be continued...

-p.

**Comment by martelletto** [comment]
Note to self: the problem is a corruption of the heap inside fclose(), which happens when we (libfido2) link against Microsoft's release C runtime. Both libcbor and LibreSSL are linked against the same runtime (when built with --config Release).

**Comment by PhoenixBaymax** [comment]
I had tried again.I executed statement below to build libcbor, libressl and libfido2 in release:

①about libressl
cmake .. -G "Visual Studio 15 2017"  -DCMAKE_INSTALL_PREFIX=E:\FIDO2_Space\includes_libs\release\libressl-2.8.3 -DBUILD_SHARED_LIBS=ON
cmake --build . --config Release
cmake --build . --config Release --target install
②about libcbor
cmake .. -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=E:\FIDO2_Space\includes_libs\release\libcbor-0.5.0
cmake --build .
cmake --build . --target install
③about libfido2
cmake .. -G "Visual Studio 15 2017" -DCBOR_INCLUDE_DIRS=E:\FIDO2_Space\includes_libs\release\libcbor-0.5.0\include -DCBOR_LIBRARY_DIRS=E:\FIDO2_Space\includes_libs\release\libcbor-0.5.0\lib -DCRYPTO_INCLUDE_DIRS=E:\FIDO2_Space\includes_libs\release\libressl-2.8.3\include -DCRYPTO_LIBRARY_DIRS=E:\FIDO2_Space\includes_libs\release\libressl-2.8.3\lib -DCMAKE_INSTALL_PREFIX=E:\FIDO2_Space\includes_libs\release\libfido2
cmake --build . --config Release
cmake --build . --config Release --target install

I run them as before, but now it run ok!
I send the new project and libs to u, u can verify whether the problem is solved!
Thank u very much!

**Comment by martelletto** [comment]
Glad you got it working! I would like to dig deeper and understand 
the nature of the problem, though. The same object code linked 
against different C runtimes should not result in crashes or other 
odd behaviour, particularly in such an elementary task (filesystem 
I/O). There is definitely something fishy going on.

I will keep this issue open and investigate further as I find the 
time. If you find out more info, please let me know. Thank you!

-p.

**Comment by borrrden** [comment]
Windows is more sensitive about the way it links to runtime libraries.  The way you have your project set up is to compile your deps out of band and then link them manually.  This results in the dependencies not being influenced by your overall build so if you build debug deps, and a release program you will be linking improperly.  Conversely, if you build release deps and make a debug program you will also be linking improperly.  

The more standard way to do this is to make your two deps subdirectories of your CMake project so that they get compiled all at once.

**Comment by martelletto** [comment]
As pointed out by @borrrden, cbor.dll and crypto-44.dll need to be placed in the same directory as the examples. I have adjusted @borrrden's fine .ps1 script accordingly, switched AppVeyor to it, and retired build.bat. Thank you @borrrden for your enlightenment on this.

**Comment by borrrden** [comment]
I havent found a need for cbor.dll to be there. I think it might be linking with the static library but I haven’t looked into it.

**Comment by martelletto** [comment]
Thanks; I've updated my comment accordingly.
