### ISSUE TITLE
u2f_register call returns FIDO_ERR_UNSUPPORTED_OPTION

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#200]
Hi,
I run fido2-cred program with following options: -M -d -u -v -i client_hash
What i notice is if i remove -v (user verification option) the program runs perfectly fine.
My yubikey (not FIDO2 enabled) has a PIN and i want to test with the pin when creating credentials.

Why U2F does not support PIN entry and only FIDO2 supports it ?

Here is the debug output:
rx_preamble: cid (0x2002400, 0x2002400), cmd (0xbf, 0x10)
rx: rx_preamble
fido_dev_get_cbor_info_rx: fido_rx
fido_dev_open_rx: falling back to u2f
u2f_register: rk=1, uv=2
fido2-cred: fido_dev_make_cred: FIDO_ERR_UNSUPPORTED_OPTION

**Comment by martelletto** [comment]
Hi!

U2F does not have the concept of PIN (or user verification of any sort).

-p.

**Comment by sb230132** [comment]
Hi,
Thanks, does U2F check for user presence ?
Like during registration or authentication with my yubikey device, do i need to touch the device ?
What is the default timeout value if i dont do gesture action. Will the program wait for ever or can i set a timeout value ?

**Comment by martelletto** [comment]
> Hi,
> Thanks, does U2F protocol check for user presence ?

Yes.

> Like during registration or authentication with my yubikey device, do i need to touch the device ?

Yes. That is non-optional in U2F.

> What is the default timeout value if i dont do gesture action. Will the program wait for ever or can i set a timeout value ?

libfido2's API is synchronous; the default behaviour is to wait 
until the user touches the authenticator, or until the authenticator 
times out. In U2F, the authenticator will never time out. If you are 
in a UNIX-like platform, you can use signals to enforce a timeout. 
This is implemented in examples/cred.c and examples/assert.c (option 
-T).

-p.

**Comment by sb230132** [comment]
Thanks for the clarification.
