### ISSUE TITLE
How to identify a device uniquely

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#201]
Hi,
Assume i have 2 yubikey devices attached to my laptop. To perform registration or assertion against a device i need to know the path of the device so that i can open that device by calling fido_dev_open() giving it the path.
Will this path always remain same even if i re-insert the device into a different slots ?
In short will path change ?  
Because after registration i intend to save the path in my application, so that during authentication, i will open the same device with the path which i have.

**Comment by martelletto** [comment]
Hi,

The path is platform-dependent and not guaranteed to be constant.

The approach usually taken in U2F is to try all authenticators until 
you find one that understands the credential. Please note that only 
the correct authenticator needs to be touched.

-p.

**Comment by sb230132** [comment]
Hi,
If i have 2 devices, during authentication:
I iterate through each device, give the device key handle or credential ID, if it understands it then fine, else go with next device.
Am i correct ??

**Comment by martelletto** [comment]
>Hi,
>If i have 2 devices, during authentication:
>I iterate through each device, give the device key handle or credential ID, if it understands it then fine, else go with next device.
>Am i correct ??

Yes. This logic is implemented here: 

https://github.com/openssh/openssh-portable/blob/master/sk-usbhid.c#L163-L204

-p.

**Comment by sb230132** [comment]
Thanks again for your quick response.
