### ISSUE TITLE
U2F as passwordless authentication.

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#203]
Hi,
From end user point of view i see that registration and authentication steps using either U2F or UAF protocol is the same.

I have a simple client server application, where i do following:
1. create a user and connect to server using a password.
2. register yubikey device against the above created user and the server.

Now user is authenticated with password + yubikey.

In my server application i have provision to drop password authentication, once i do this next time when user connects,
all he is needed is to enter username and insert the yubikey, which in a way achieves password-less authentication.

So iam using U2F protocol to achieve passwordless authentication. Why i do this is because i don't have FIDO2 enabled device.

Can we do this ?

**Comment by martelletto** [comment]
U2F is a single factor of authentication. Without passwords or an earlier authentication step to protect the credential, the security of U2F is reduced to the physical possession of the security key.

**Comment by sb230132** [comment]
Unless we setup a PIN to the device, which U2F protocol does not seem to support.
Is it that none of the implementations of U2F protocol support PIN ?

**Comment by martelletto** [comment]
U2F doesn't have the concept of PIN or user verification in its design. User verification is one of the cornerstones of FIDO2.

**Comment by sb230132** [comment]
Ok. Thank you.
