### ISSUE TITLE
does access to fido device need root access ?

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#207]
If i have my application on linux, so does this mean that my application should be run as root inorder to access fido device ?

What does below mean ?

On Linux, you will need to add a udev rule to be able to access the FIDO device, or run as root. For example, the udev rule may contain the following:

#udev rule for allowing HID access to Yubico devices for FIDO support.

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", \
  MODE="0664", GROUP="plugdev", ATTRS{idVendor}=="1050"

**Comment by martelletto** [comment]
udev is a device manager for Linux. Depending on udev's configuration, non-root users may be able to access devices abstracted by the kernel. udev can be configured using rules. The udev rule is in libfido2's README allows members of the `plugdev` group to access HID devices manufactured by Yubico (vendor id 0x1050).
