### ISSUE TITLE
Is it supported on windows server.

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#208]
Hi,

Is libfido2 library available on following windows platforms:

Microsoft Windows 2012 Server R2
Microsoft Windows 2016 Server
Microsoft Windows 2019 Server

Thanks

**Comment by martelletto** [comment]
A native build should work, but I give no guarantees. :) Someone from Yubico might want to weigh in on this, but I wouldn't expect anything older than Windows 10 to be officially supported, even if it works.
