### ISSUE TITLE
Release 1.5.0 is not available from the official Releases page

### ISSUE THREAD

**Issue by prusnak** [Yubico/libfido2#209]
https://developers.yubico.com/libfido2/Releases/ does not contain release 1.5.0

**Comment by martelletto** [comment]
Please see https://github.com/Yubico/libfido2/commit/37c75c837b872bcb65f006c72b80d95156d10e8a#commitcomment-41966381. I will update the ticket once the tarball is out. Apologies for the convenience.

**Comment by martelletto** [comment]
The 1.5.0 release tarball is now available in https://developers.yubico.com/libfido2/Releases/.

**Comment by gabriel** [comment]
FYI, Ubuntu 20 (focal) is still on 1.3.1.
https://packages.ubuntu.com/source/focal/libfido2

**Comment by garybuhrmaster** [comment]
> FYI, Ubuntu 20 (focal) is still on 1.3.1.
> https://packages.ubuntu.com/source/focal/libfido2

You need to talk with the package maintainers for Ubuntu (also referenced at the link you stated).  Different distros have different package update processes.
