### ISSUE TITLE
No Shared Library Available for Windows

### ISSUE THREAD

**Issue by borrrden** [Yubico/libfido2#21]
I noticed that support for Windows shared library is explicitly disabled in the CMake project.  I made some trivial changes locally and using this library as a shared library on Windows doesn't seem to cause any issues so why is it disabled?  If it is because of lack of familiarity with Windows builds then I would be happy to submit a PR for review.

The reason I want it as a shared library is because I wrote a set of .NET bindings to allow use of the library from .NET languages but the ability to link statically is not available to .NET projects.

**Comment by borrrden** [comment]
Note:  For https://github.com/borrrden/Fido2Net

**Comment by martelletto** [comment]
Hi,

It is indeed due to lack of familiarity with Windows builds. A PR 
would definitely be welcome!

-p.
