### ISSUE TITLE
Decrypting message on yubikey that was encrypted by its credential creation public key

### ISSUE THREAD

**Issue by Lethargo** [Yubico/libfido2#216]
Hi,
Is their anyway within the libfido2 framework to alter the code so I can pass a public key encrypted message (from the credential creation ceremony) back from the server to the client and decrypted it using the Yubikey resident/secret key?
Thanks for any help,
Peter

**Comment by martelletto** [comment]
Hi,

The bulk of FIDO2 consists of public-key authentication. The `hmac-secret` extension can be used to implement secret-key (symmetric) encryption. Public-key encryption is not currently possible in FIDO2.

-p.
