### ISSUE TITLE
libfido2 build failure on el6

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#217]
Hi,
When i try to build fido2 library i see below error:
[  0%] Building C object src/CMakeFiles/fido2.dir/aes256.c.o
cd /home/bhsatish/fido_new_el6/fido_new/build/src && /usr/bin/cc  -DHAVE_CLOCK_GETTIME -DHAVE_DEV_URANDOM -DHAVE_ENDIAN_H -DHAVE_ERR_H -DHAVE_GETLINE -DHAVE_GETOPT -DHAVE_GETPAGESIZE -DHAVE_SIGNAL_H -DHAVE_SYSCONF -DHAVE_UNISTD_H -DSIGNAL_EXAMPLE -DTLS=__thread -D_DEFAULT_SOURCE -D_FIDO_INTERNAL -D_FIDO_MAJOR=1 -D_FIDO_MINOR=5 -D_FIDO_PATCH=0 -D_GNU_SOURCE -I/home/bhsatish/fido_new_el6/fido_new/CBOR_INCLUDE_DIRS -I/home/bhsatish/udev_devel_el6/usr/include -I/home/bhsatish/fido_new_el6/fido_new/src -I/home/bhsatish/cbor_new_el6/cbor_new/build/install/include  -Wall -Wextra -Werror -Wshadow -Wwrite-strings -Wmissing-prototypes -Wbad-function-cast -pedantic -pedantic-errors -fstack-protector-all -std=c99 -Wno-unused-result -Wcast-qual -fPIC   -Wconversion -Wsign-conversion -o CMakeFiles/fido2.dir/aes256.c.o   -c /home/bhsatish/fido_new_el6/fido_new/src/aes256.c
In file included from /home/bhsatish/fido_new_el6/fido_new/src/aes256.c:10:
/home/bhsatish/fido_new_el6/fido_new/src/fido.h:108: error: wrong number of arguments specified for ‘__deprecated__’ attribute
/home/bhsatish/fido_new_el6/fido_new/src/fido.h:122: error: wrong number of arguments specified for ‘__deprecated__’ attribute
cc1: warnings being treated as errors

Can you please let me know what am i missing.

**Comment by martelletto** [comment]
Hi,

You can try to remove the `FIDO_DEPRECATED` annotations in lines 108 and 122 of fido.h and see if that gets you further. Out of curiosity, what is the output of `cc --version`?

-p.

**Comment by sb230132** [comment]
Hi,



After i removed FIDO_DEPRECATED macro for those API's I got below errors, which i fixed it and was able to do the build.

cc1: warnings being treated as errors
/home/bhsatish/fido_new_el6/fido_new/src/cbor.c: In function ‘cbor_encode_change_pin_auth’:
/home/bhsatish/fido_new_el6/fido_new/src/cbor.c:729: error: conversion to ‘size_t’ from ‘int’ may change the sign of the result
/home/bhsatish/fido_new_el6/fido_new/src/cbor.c:730: error: conversion to ‘size_t’ from ‘int’ may change the sign of the result


cc --version
cc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23.0.1)
Copyright (C) 2010 Free Software Foundation, Inc.

Will the above macro error be fixed ?

Thanks & Regards
Satish.B

**Comment by martelletto** [comment]
I've dropped the macro in 09f6ad0. Thanks for pointing it out.
