### ISSUE TITLE
Suspicious check in CMake project

### ISSUE THREAD

**Issue by borrrden** [Yubico/libfido2#23]
I noticed the following lines in the CMake project

https://github.com/Yubico/libfido2/blob/274b41af62ecfa498506c5c25c3265b2aa024752/CMakeLists.txt#L227-L230

Judging by what is happening I believe the intent is to carry this out on all Apple builds, not just ones with a custom clang build.  Apple identifies its compiler as `AppleClang` as opposed to `Clang` ([reference](https://cmake.org/cmake/help/v3.14/policy/CMP0025.html))

Recommendation is to use the following logic instead:

```
if (CMAKE_C_COMPILER_ID MATCHES "Clang")
  # using regular Clang or AppleClang
endif()
```

**Comment by martelletto** [comment]
That is indeed better; thanks! Committed in 86422478. Unfortunately 
we can't use CMAKE_C_COMPILER_ID MATCHES "Clang" as we need to 
distinguish between clang + GNU ld and clang + LLVM ld (Apple 
Clang).

-p.
