### ISSUE TITLE
Yubikey 5 NFC returns FIDO_ERR_ACTION_TIMEOUT on make_cred

### ISSUE THREAD

**Issue by cozyGalvinism** [Yubico/libfido2#230]
**What version of libfido2 are you using?**
1.5.0-2
**What operating system are you running?**
Arch Linux on kernel 5.4.72-1
**What application are you using in conjunction with libfido2?**
I tried both pamu2fcfg and ssh-keygen, both with the same result.
**How does the problem manifest itself?**
First, I get asked for a PIN, which I enter (which is odd, since I originally just wanted to press the button on the key). After around 30 seconds, I get the error `error: fido_dev_make_cred (58) FIDO_ERR_ACTION_TIMEOUT`
**Is the problem reproducible?**
It happens every time I try to set up either an SSH key or generate a PAM config for U2F, so it is for me.
**What are the steps that lead to the problem?**
I installed dependencies and binaries for both the Yubikey Personaliation Tool and the Yubikey Manager, as well as libfido2. After running either `pamu2fcfg --debug -ucozygalvinism` or `ssh-keygen -t ed25519-sk -vvvv` and entering the PIN, it won't do anything (even in verbose/debug mode) for around 30 seconds, after which I get the error. Entering a wrong PIN (or trying to enter an OTP) does not work and will lead to "PIN incorrect".
**Does the problem happen with different authenticators?**
I only have the Yubikey 5 NFC, so I can't test this on other devices.

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L
/dev/hidraw12: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;
proto: 0x02
major: 0x05
minor: 0x02
build: 0x06
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1_PRE
extension strings: credProtect, hmac-secret
aaguid: 2fc0579f811347eab116bb5a8db9202a
options: rk, up, noplat, clientPin, credentialMgmtPreview
maxmsgsiz: 1200
maxcredcntlst: 8
maxcredlen: 128
fwversion: 0x0
pin protocols: 1
pin retries: 8
</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ ssh-keygen -t ed25519-sk -vvvv
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
debug3: start_helper: started pid=25848
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/ssh/ssh-sk-helper 
debug1: sshsk_enroll: provider "internal", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0
debug1: sshsk_enroll: using random challenge
debug1: ssh_sk_enroll: using device /dev/hidraw12
debug1: ssh_sk_enroll: fido_dev_make_cred: FIDO_ERR_PIN_REQUIRED
debug1: sshsk_enroll: provider "internal" returned failure -3
debug1: ssh-sk-helper: Enrollment failed: incorrect passphrase supplied to decrypt private key
debug1: ssh-sk-helper: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -43
debug3: reap_helper: pid=25848
Enter PIN for authenticator: 
debug3: start_helper: started pid=25849
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/ssh/ssh-sk-helper 
debug1: sshsk_enroll: provider "internal", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0 with-pin
debug1: sshsk_enroll: using random challenge
debug1: ssh_sk_enroll: using device /dev/hidraw12
debug1: ssh_sk_enroll: fido_dev_make_cred: FIDO_ERR_ACTION_TIMEOUT
debug1: sshsk_enroll: provider "internal" returned failure -1
debug1: ssh-sk-helper: Enrollment failed: invalid format
debug1: ssh-sk-helper: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -4
debug3: reap_helper: pid=25849
Key enrollment failed: invalid format
$ pamu2fcfg --debug -ucozygalvinism
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
is_fido: open
fido_tx: d=0x55ed2e804500, cmd=0x06, buf=0x55ed2e804500, count=8
0000: cb 1e 27 e0 75 3a 96 6d
fido_rx: d=0x55ed2e804500, cmd=0x06, buf=0x55ed2e804508, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb9820
0000: ff ff ff ff 86 00 11 cb 1e 27 e0 75 3a 96 6d 00
0016: 0f 00 04 02 05 02 06 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x55ed2e804508, len=17
0000: cb 1e 27 e0 75 3a 96 6d 00 0f 00 04 02 05 02 06
0016: 05
fido_dev_get_cbor_info_tx: dev=0x55ed2e804500
fido_tx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb9887, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x55ed2e804500, ci=0x55ed2e805260, ms=-1
fido_rx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb9070, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb8fe0
0000: 00 0f 00 04 90 00 c3 00 aa 01 83 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 6c 46 49 44 4f
0032: 5f 32 5f 31 5f 50 52 45 02 82 6b 63 72 65 64 50
0048: 72 6f 74 65 63 74 6b 68 6d 61 63 2d 73 65 63 72
rx: payload_len=195
rx: continuation frame at 0x7ffc59eb8fe0
0000: 00 0f 00 04 00 65 74 03 50 2f c0 57 9f 81 13 47
0016: ea b1 16 bb 5a 8d b9 20 2a 04 a5 62 72 6b f5 62
0032: 75 70 f5 64 70 6c 61 74 f4 69 63 6c 69 65 6e 74
0048: 50 69 6e f5 75 63 72 65 64 65 6e 74 69 61 6c 4d
rx: continuation frame at 0x7ffc59eb8fe0
0000: 00 0f 00 04 01 67 6d 74 50 72 65 76 69 65 77 f5
0016: 05 19 04 b0 06 81 01 07 08 08 18 80 09 82 63 6e
0032: 66 63 63 75 73 62 0a 82 a2 63 61 6c 67 26 64 74
0048: 79 70 65 6a 70 75 62 6c 69 63 2d 6b 65 79 a2 63
rx: continuation frame at 0x7ffc59eb8fe0
0000: 00 0f 00 04 02 61 6c 67 27 64 74 79 70 65 6a 70
0016: 75 62 6c 69 63 2d 6b 65 79 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffc59eb9070, len=195
0000: 00 aa 01 83 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 6c 46 49 44 4f 5f 32 5f 31 5f 50 52
0032: 45 02 82 6b 63 72 65 64 50 72 6f 74 65 63 74 6b
0048: 68 6d 61 63 2d 73 65 63 72 65 74 03 50 2f c0 57
0064: 9f 81 13 47 ea b1 16 bb 5a 8d b9 20 2a 04 a5 62
0080: 72 6b f5 62 75 70 f5 64 70 6c 61 74 f4 69 63 6c
0096: 69 65 6e 74 50 69 6e f5 75 63 72 65 64 65 6e 74
0112: 69 61 6c 4d 67 6d 74 50 72 65 76 69 65 77 f5 05
0128: 19 04 b0 06 81 01 07 08 08 18 80 09 82 63 6e 66
0144: 63 63 75 73 62 0a 82 a2 63 61 6c 67 26 64 74 79
0160: 70 65 6a 70 75 62 6c 69 63 2d 6b 65 79 a2 63 61
0176: 6c 67 27 64 74 79 70 65 6a 70 75 62 6c 69 63 2d
0192: 6b 65 79
parse_reply_element: cbor type
parse_reply_element: cbor type
fido_dev_open_rx: FIDO_MAXMSG=2048, maxmsgsiz=1200
fido_tx: d=0x55ed2e804500, cmd=0x10, buf=0x55ed2e8154b0, count=185
0000: 01 a4 01 58 20 7f 78 e5 d0 0d 8d 94 49 a5 a6 68
0016: b6 ed 91 13 99 da f5 88 94 9a 8d a2 20 5a 91 81
0032: 18 b7 d9 b0 2d 02 a2 62 69 64 6e 70 61 6d 3a 2f
0048: 2f 4e 43 43 2d 31 37 30 31 64 6e 61 6d 65 6e 70
0064: 61 6d 3a 2f 2f 4e 43 43 2d 31 37 30 31 03 a3 62
0080: 69 64 58 20 bb b3 15 6e 5a 13 f0 ad 45 00 d8 a2
0096: 31 a9 b1 c5 40 3f de 0b a8 5e 36 11 91 5c 2e aa
0112: 9b f9 e8 00 64 6e 61 6d 65 6d 63 6f 7a 79 67 61
0128: 6c 76 69 6e 69 73 6d 6b 64 69 73 70 6c 61 79 4e
0144: 61 6d 65 6d 63 6f 7a 79 67 61 6c 76 69 6e 69 73
0160: 6d 04 81 a2 63 61 6c 67 26 64 74 79 70 65 6a 70
0176: 75 62 6c 69 63 2d 6b 65 79
fido_rx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb90c0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb9030
0000: 00 0f 00 04 90 00 01 36 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0x7ffc59eb90c0, len=1
0000: 36
cbor_parse_reply: blob[0]=0x36
fido_dev_make_cred_rx: parse_makecred_reply
Enter PIN for /dev/hidraw12: 
fido_dev_authkey_tx: dev=0x55ed2e804500
fido_tx: d=0x55ed2e804500, cmd=0x10, buf=0x55ed2e818a80, count=6
0000: 06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0x55ed2e804500, authkey=0x55ed2e804420, ms=-1
fido_rx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb8fa0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb8f10
0000: 00 0f 00 04 90 00 51 00 a1 01 a5 01 02 03 38 18
0016: 20 01 21 58 20 84 51 f3 56 a5 17 42 8c c7 92 32
0032: 8c 09 29 91 5b 7d a5 51 50 cb be 9c 12 30 b6 75
0048: b8 81 4d ef 14 22 58 20 31 53 07 0a 5d 55 3c 4d
rx: payload_len=81
rx: continuation frame at 0x7ffc59eb8f10
0000: 00 0f 00 04 00 53 4c f6 e6 f1 6f 29 c0 4f 61 73
0016: e4 96 3a 96 1a 23 1a d7 e0 85 e4 2f b1 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffc59eb8fa0, len=81
0000: 00 a1 01 a5 01 02 03 38 18 20 01 21 58 20 84 51
0016: f3 56 a5 17 42 8c c7 92 32 8c 09 29 91 5b 7d a5
0032: 51 50 cb be 9c 12 30 b6 75 b8 81 4d ef 14 22 58
0048: 20 31 53 07 0a 5d 55 3c 4d 53 4c f6 e6 f1 6f 29
0064: c0 4f 61 73 e4 96 3a 96 1a 23 1a d7 e0 85 e4 2f
0080: b1
fido_tx: d=0x55ed2e804500, cmd=0x10, buf=0x55ed2e816a40, count=103
0000: 06 a4 01 01 02 05 03 a5 01 02 03 38 18 20 01 21
0016: 58 20 f0 62 18 5a 33 be 14 9e c5 63 3c 93 9c 31
0032: 83 85 ad 74 0e ca 77 42 05 26 17 b2 68 56 29 15
0048: 32 5f 22 58 20 97 1d 9e f5 09 fa d4 49 21 aa 86
0064: d3 f2 a8 c8 56 ee 98 fd 17 fa 26 59 7d 4c a0 60
0080: 9c 29 61 c2 1f 06 50 ea 4c 05 7c ef 79 08 10 33
0096: 3a d2 3f 9e 61 5a d4
fido_rx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb8f90, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb8ef0
0000: 00 0f 00 04 90 00 14 00 a1 02 50 4d 29 64 70 0f
0016: 8d a6 62 2a 19 e6 d2 da 45 d2 f3 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=20
fido_rx: buf=0x7ffc59eb8f90, len=20
0000: 00 a1 02 50 4d 29 64 70 0f 8d a6 62 2a 19 e6 d2
0016: da 45 d2 f3
fido_tx: d=0x55ed2e804500, cmd=0x10, buf=0x55ed2e813e30, count=205
0000: 01 a6 01 58 20 7f 78 e5 d0 0d 8d 94 49 a5 a6 68
0016: b6 ed 91 13 99 da f5 88 94 9a 8d a2 20 5a 91 81
0032: 18 b7 d9 b0 2d 02 a2 62 69 64 6e 70 61 6d 3a 2f
0048: 2f 4e 43 43 2d 31 37 30 31 64 6e 61 6d 65 6e 70
0064: 61 6d 3a 2f 2f 4e 43 43 2d 31 37 30 31 03 a3 62
0080: 69 64 58 20 bb b3 15 6e 5a 13 f0 ad 45 00 d8 a2
0096: 31 a9 b1 c5 40 3f de 0b a8 5e 36 11 91 5c 2e aa
0112: 9b f9 e8 00 64 6e 61 6d 65 6d 63 6f 7a 79 67 61
0128: 6c 76 69 6e 69 73 6d 6b 64 69 73 70 6c 61 79 4e
0144: 61 6d 65 6d 63 6f 7a 79 67 61 6c 76 69 6e 69 73
0160: 6d 04 81 a2 63 61 6c 67 26 64 74 79 70 65 6a 70
0176: 75 62 6c 69 63 2d 6b 65 79 08 50 2b 69 48 9e b8
0192: d5 86 a7 72 15 c2 28 35 41 bb cb 09 01
fido_rx: d=0x55ed2e804500, cmd=0x10, buf=0x7ffc59eb90c0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffc59eb9030
0000: 00 0f 00 04 90 00 01 3a 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0x7ffc59eb90c0, len=1
0000: 3a
cbor_parse_reply: blob[0]=0x3a
fido_dev_make_cred_rx: parse_makecred_reply
error: fido_dev_make_cred (58) FIDO_ERR_ACTION_TIMEOUT
</pre>
</details>

**Comment by martelletto** [comment]
Hi,

During the 30 seconds interval:

- Does the key blink?
- What happens if you touch it?

Thank you,

-p.

**Comment by cozyGalvinism** [comment]
Heya, I literally just plugged it into my USB hub (because if I plug it into my PC, I only see the backside of the stick) and saw it blinking. Yeah, that issue is on me haha. Thanks for your help anyways ^^ I'm rather new to this c:

**Comment by martelletto** [comment]
No problem at all! Glad to help.
