### ISSUE TITLE
FreeBSD fido2 and ssh-keygen

### ISSUE THREAD

**Issue by nicocaille** [Yubico/libfido2#232]
Hello,

I am not sure this is relevant to the library itself but I cannot manage to generate an ed25519-sk ssh key from `FreeBSD 12.1-RELEASE`. The Yubikey is recognized and I am using the latest versions of the different libs:

```
root@builder:~ # pkg info | grep libfido2
libfido2-1.5.0                 Provides library functionality for FIDO 2.0

root@builder:~ # pkg info | grep openssh-portable
openssh-portable-8.2.p1_1,1    The portable version of OpenBSD's OpenSSH

root@builder:~ # pkg info | grep libudev-devd
libudev-devd-0.4.2_1           libudev-compatible interface for devd

root@builder:~ # cat /etc/devfs.rules
[localrules=5]
add path 'uhid*'    mode 0660 group operator
add path 'da*'    mode 0660 group operator
add path 'cd*'    mode 0660 group operator
add path 'uscanner*'    mode 0660 group operator
add path 'xpt*' mode 660 group operator
add path 'pass*' mode 660 group operator
add path 'md*' mode 0660 group operator
add path 'msdosfs/*' mode 0660 group operator
add path 'ext2fs/*' mode 0660 group operator
add path 'ntfs/*' mode 0660 group operator
add path 'usb/*' mode 0660 group operator

root@builder:~ # fido2-token -L
0000:0004:00: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0000:0004:01: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0000:0004:02: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0002:0008:00: vendor=0x05ac, product=0x8242 (Apple, Inc. IR Receiver)
0000:0002:00: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
0000:0002:01: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)

root@builder:~ # dmesg |grep Yubico
ugen0.2: <Yubico YubiKey OTP+FIDO+CCID> at usbus0
ukbd0: <Yubico YubiKey OTP+FIDO+CCID, class 0/0, rev 2.00/5.24, addr 1> on usbus0
[14] uhid0: <Yubico YubiKey OTP+FIDO+CCID, class 0/0, rev 2.00/5.24, addr 1> on usbus0
[31789] ugen0.2: <Yubico YubiKey OTP+FIDO+CCID> at usbus0 (disconnected)
[65986] ugen0.2: <Yubico YubiKey OTP+FIDO+CCID> at usbus0
[65986] ukbd0: <Yubico YubiKey OTP+FIDO+CCID, class 0/0, rev 2.00/5.24, addr 4> on usbus0
[65986] uhid0: <Yubico YubiKey OTP+FIDO+CCID, class 0/0, rev 2.00/5.24, addr 4> on usbus0
```

I have tried several combinations for the `ssh-keygen`:

```
root@builder:~ # /usr/local/bin/ssh-keygen -t ed25519-sk -w /dev/uhid0 -f .ssh/id_ed25519_sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
Provider "/dev/uhid0" dlopen failed: /dev/uhid0: invalid file format
Key enrollment failed: invalid format

root@builder:~ # /usr/local/bin/ssh-keygen -t ed25519-sk -w /dev/ugen0.2 -f /root/.ssh/id_ed25519_sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
Provider "/dev/ugen0.2" dlopen failed: /dev/ugen0.2: invalid file format
Key enrollment failed: invalid format

root@builder:~ # /usr/local/bin/ssh-keygen -t ed25519-sk -w /dev/fido -f .ssh/id_ed25519_sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
Provider "/dev/fido" dlopen failed: /dev/fido: invalid file format
Key enrollment failed: invalid format
```

Has anyone successfully managed to generate ED25519-SK on FreeBSD?

Thanks

**Comment by martelletto** [comment]
Hi,

`ssh-keygen -w` takes the path to a library implementing communication with FIDO2 devices. To build this library, please follow the steps at https://github.com/pts/external-sk-libfido2/blob/master/README.txt#L62-L69. These extra steps are needed because FreeBSD's port of OpenSSH does not appear to be built with `--with-security-key-builtin`.

-p.

**Comment by nicocaille** [comment]
Hi,

yes it looks weird that this flag is not enabled or at least an option from the ports. I tried what you suggested and it still doesn't work:

```
root@builder:~ # /usr/local/bin/ssh-keygen -t ed25519-sk -f ~/.ssh/id_mykey_sk -C id_mykey_sk -w "/root/libsk-libfido2.so" -v
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
debug1: start_helper: starting /usr/local/libexec/ssh-sk-helper
debug1: sshsk_enroll: provider "/root/libsk-libfido2.so", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0
debug1: sshsk_enroll: using random challenge
debug1: sshsk_open: provider /root/libsk-libfido2.so implements version 0x00040000
debug1: sshsk_enroll: provider "/root/libsk-libfido2.so" returned failure -1
debug1: ssh-sk-helper: Enrollment failed: invalid format
debug1: ssh-sk-helper: reply len 8
debug1: client_converse: helper returned error -4
Key enrollment failed: invalid format
```

I will try to recompile `openssh-portable` from the ports with the config option `--with-security-key-builtin`. I will also ask the port maintainer to have this enabled if possible.

Thanks

**Comment by nicocaille** [comment]
I have recompiled the port with the option `--with-security-key-builtin`, i checked the output with a grep on fido2:

```
checking if /usr/local/bin/pkg-config knows about libfido2... yes
[...]
checking for fido_init in -lfido2... yes
[...]
cc -o ssh-sk-helper ssh-sk-helper.o ssh-sk.o sk-usbhid.o -L. -Lopenbsd-compat/ -L/usr/local/lib  -Wl,-rpath,/usr/local/lib -fstack-protector-strong  -Wl,-z,retpolineplt -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -fstack-protector-strong -L/usr/local/lib -L/usr/local/lib -lssh -lopenbsd-compat -lssh -lopenbsd-compat -lcrypto -lldns -lz -L/usr/local/lib -lutil -lcrypt -L/usr/local/lib -lfido2 -lcrypto
```

I try again and it looks like it get to talk to the device but still fails:

```
/usr/local/bin/ssh-keygen -t ed25519-sk -f ~/.ssh/id_ed25519-sk -v
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
debug1: start_helper: starting /usr/local/libexec/ssh-sk-helper 
debug1: sshsk_enroll: provider "internal", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0
debug1: sshsk_enroll: using random challenge
debug1: ssh_sk_enroll: using device 0000:0002:00
cdebug1: ssh_sk_enroll: fido_dev_open: FIDO_ERR_RX
debug1: sshsk_enroll: provider "internal" returned failure -1
debug1: ssh-sk-helper: Enrollment failed: invalid format
debug1: ssh-sk-helper: reply len 8
debug1: client_converse: helper returned error -4
Key enrollment failed: invalid format
```

I have noticed something though, when i do the `fido2-token -L` i get two items for the only one key plugged:
```
root@builder:~ # fido2-token -L
0000:0004:00: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0000:0004:01: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0000:0004:02: vendor=0x046d, product=0xc52b (Logitech USB Receiver)
0002:0008:00: vendor=0x05ac, product=0x8242 (Apple, Inc. IR Receiver)
0000:0002:00: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
0000:0002:01: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
```

The `ssh-keygen` is talking to `0000:0002:00` although if i query this device via the `fido2-token -I` it just hangs and i have to kill it (ctrl+c) but if i query the other "address" i get the correct answer:

```
root@builder:~ # fido2-token -I "0000:0002:00"
^C
root@builder:~ # fido2-token -I "0000:0002:01"
proto: 0x02
major: 0x05
minor: 0x02
build: 0x04
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1_PRE
extension strings: credProtect, hmac-secret
aaguid: 2fc05[...]8db9202a
options: rk, up, noplat, clientPin, credentialMgmtPreview
maxmsgsiz: 1200
maxcredcntlst: 8
maxcredlen: 128
fwversion: 0x0
pin protocols: 1
pin retries: 8
```

I have tried with different generations of yubikeys (Neo, Y4, Y5), on FreeBSD, it always shows two lines for one device for `fido2-token -L`

**Comment by martelletto** [comment]
If you change [this line ](https://github.com/Yubico/libfido2/blob/master/src/hid_hidapi.c#L224)to include `|| defined(__FreeBSD__)`, does anything change?

I seem to recall `usage_page` being unset on FreeBSD, which means libfido2 cannot distinguish between the OTP and FIDO HID interfaces. It might also be worth looking into https://github.com/libusb/hidapi instead of https://github.com/signal11/hidapi - the FreeBSD port [uses the latter](https://github.com/freebsd/freebsd-ports/blob/master/comms/hidapi/Makefile). From a glance at libusb/hidapi and FreeBSD's libusb code, it should be working.

-p.

**Comment by martelletto** [comment]
Please disregard my previous comment. I have installed FreeBSD on a VM and got libfido2 to work. Time permitting, I will implement a HID backend for FreeBSD over the weekend.

**Comment by martelletto** [comment]
I've pushed a tentative implementation to https://github.com/Yubico/libfido2/tree/freebsd, tested on FreeBSD 12.2-STABLE. The caveat is that manufacturer and product IDs/strings are currently inaccessible through uhid(4) in FreeBSD, so you will see this:

```
root@freebsd:~/libfido2/build # tools/fido2-token -L
/dev/uhid0: vendor=0x0b5d, product=0x0000 (FreeBSD uhid(4))
```

To get these attributes, you will need to patch your kernel with https://ambientworks.net/tmp/uhid-USB_GET_DEVICEINFO.txt, also tested on FreeBSD 12.2-STABLE.

```
root@freebsd:~/libfido2/build # tools/fido2-token -L
/dev/uhid0: vendor=0x1050, product=0x0406 (Yubico YubiKey FIDO+CCID)
```

I will submit the kernel patch for consideration by the FreeBSD developers.

-p.

**Comment by martelletto** [comment]
I've merged the `freebsd` branch. Meanwhile, the FreeBSD diff has been committed: https://github.com/freebsd/freebsd/commit/ae4d836.

**Comment by nicocaille** [comment]
perfect thanks a lot Pedro, i'll git it a go on my side.

**Comment by martelletto** [comment]
@nicocaille did you have a chance to test the changes?

thank you,

-p.

**Comment by martelletto** [comment]
closing after 30 days, in the understanding that the requested functionality was implemented and is working as expected. please let me know if that is not the case.

**Comment by ocochard** [comment]
Hi, I'm using latest FreeBSD ( FreeBSD 14.0-CURRENT main-n244531 Sat Jan 30) and latest libfido2 lib, but I have still the exact same problem with multiple fido2 tokens reported (there is only one inserted):
```
# fido2-token -L
0000:0003:00: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
0000:0003:01: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
0000:0005:00: vendor=0x0557, product=0x2419 ( )
0000:0005:01: vendor=0x0557, product=0x2419 ( )
```

**Comment by martelletto** [comment]
@ocochard, was libfido2 installed from ports?

**Comment by ocochard** [comment]
@martelletto Yes I've meet this problem with the FreeBSD official package libfido2 (1.6.0).
So I've updated the port myself to latest commit (c3a9b34) but same result.

But I've find how to fix it: The FreeBSD port is using "CMAKE_ON=  USE_HIDAPI", so I've removed this line and now it is working:
```
# fido2-token -L
/dev/uhid0: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)
```

**Comment by martelletto** [comment]
@ocochard Thank you. Glad it's working. @sunpoet, would it be possible to switch the FreeBSD port to use the native HID backend?

**Comment by sunpoet** [comment]
> @ocochard Thank you. Glad it's working. @sunpoet, would it be possible to switch the FreeBSD port to use the native HID backend?

Thanks for reminding me. I've switched the FreeBSD port to use the native HID backend yesterday.

**Comment by mqudsi** [comment]
Old issue, but for posterity and for anyone searching via Google:

```
root@builder:~ # /usr/local/bin/ssh-keygen -t ed25519-sk -w /dev/fido -f .ssh/id_ed25519_sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
Provider "/dev/fido" dlopen failed: /dev/fido: invalid file format
Key enrollment failed: invalid format
```

Under FreeBSD, `/dev/fido` is the hardware watchdog timer and is not related to FIDO authentication. See [watchdog(4)](https://www.freebsd.org/cgi/man.cgi?query=watchdog&apropos=0&sektion=4&manpath=FreeBSD+13.1-RELEASE&arch=default&format=html) for more info.
