### ISSUE TITLE
fido2 returns user presence is required.

### ISSUE THREAD

**Issue by iradization** [Yubico/libfido2#237]
Hi, 

I see that if I configure up=true and uv=false: 

	fido_assert_set_uv(_assertion, FIDO_OPT_TRUE);
	fido_assert_set_up(_assertion, FIDO_OPT_FALSE);

than after submitting the pin code I get failure response = FIDO_ERR_UP_REQUIRED on :

      fido_dev_get_assert(device, _assertion, pin_cstr); 

perhaps anybody can explain what does `user presence` stand for and why does the fido side device it's required ? 

thanks !

**Comment by martelletto** [comment]
Hi,

`user presence` is defined in https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorGetAssertion as: 

> Instructs the authenticator to require user consent to complete the operation. 

Which authenticator/device are you using?

-p.

**Comment by iradization** [comment]
I'm working with fido2 NFC which suppose to support both user verification and user presence. Perhaps can you tell me what might lead to this rejection (since the fido card logic is not published)

**Comment by martelletto** [comment]
Powering the authenticator on but not touching it where it expects to be touched, maybe? It depends on what the authenticator understands "user presence" to be.

**Comment by martelletto** [comment]
Closing; please let me know if there is anything else I can help with.

**Comment by Manouchehri** [comment]
@martelletto Hmm, do YubiKeys actually support FIDO2 without user presence? I can't seem to get it to work in my application either.

```
dave@mbp:~$ sudo systemd-cryptenroll --fido2-device=auto --fido2-with-user-presence=false --fido2-with-client-pin=true --fido2-with-user-verification=false /dev/loop0
🔐 Please enter current passphrase for disk /dev/loop0: *******                 
Initializing FIDO2 credential on security token.
👆 (Hint: This might require confirmation of user presence on security token.)
🔐 Please enter security token PIN: ******                  
Generating secret key on FIDO2 security token.
👆 Locking without user presence test requested, but FIDO2 device /dev/hidraw1 requires it, enabling.
New FIDO2 token enrolled as key slot 1.
```

**Comment by nuno0529** [comment]
@Manouchehri ctap2 spec doesn't allow makeCred command without user presence, https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#:~:text=if%20the%20%22up%22%20option%20is%20false%2C%20end%20the%20operation%20by%20returning%20ctap2_err_invalid_option.

**Comment by martelletto** [comment]
To add to Nuno's point, the CTAP2 spec also does not allow usage of the hmac-secret extension without user presence (UP): https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-hmac-secret-extension. This extension is used by systemd.

**Comment by Manouchehri** [comment]
@martelletto / @nuno0529: Good find, thank you.

If it's disallowed by spec, should we even have an option to allow to "disable" it? I personally haven't found a situation where it works having user presence disabled.

**Comment by LDVG** [comment]
> If it's disallowed by spec, should we even have an option to allow to "disable" it? I personally haven't found a situation where it works having user presence disabled.

There are scenarios in which disabling user presence tests is allowed, see for example "pre-flight" assertions: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#pre-flight

**Comment by jzvikart** [comment]
The specification doesn't make practical sense. A perfectly valid scenario would be to have an unattended server unlock encrypted disk automatically at boot. This specification means that one cannot use fido2, which almost certainly means a less secure solution. If I want to disable use presence test, this should be my decision and my risk, I don't want to be treated like a baby by some standards committee.
