### ISSUE TITLE
Incompatibility between libfido2 and Hypersecu Hyper Fido Pro Mini

### ISSUE THREAD

**Issue by hadmut** [Yubico/libfido2#238]
Hi, 
while programming with libfido2 and performing tests with FIDO2 tokens from different manufacturers (using Ubuntu 20.04 with libfido2 and fido2-tools 1.3.1, I ran into the problem that tokens behave differently _when trying to create resident keys_ 

I tracked it down to

- create a text file with the four lines as input as described in man fido2-cred
- fido2-token -S devicepath  
- fido2-cred -M -r -i test3_cred_input devicepath
- fido2-token -L -r devicepath

to set an initial PIN, create a residental, and list it. 

Tested both identical steps with 

/dev/hidraw3: vendor=0x1050, product=0x0120 (Yubico Security Key by Yubico)
/dev/hidraw5: vendor=0x2ccf, product=0x0854 (HS HyperFIDO)

When doing this with the Yubico, everything works as expected. The listing shows
00: GSq9DQ0stVws3T2T09ohvI7V/Zh3M4z043tFmwXmVh8= www.danisch.de

But with the Hyper Fido Pro Mini from Hypsersecu the creation runs smoothly, but the Listing
Enter PIN for /dev/hidraw5: 
fido2-token: fido_credman_get_dev_rp: FIDO_ERR_UNKNOWN

and

% fido2-token -R /dev/hidraw5

fido2-token: fido_dev_reset: FIDO_ERR_NOT_ALLOWED

% fido2-token -I /dev/hidraw5

proto: 0x02
major: 0x01
minor: 0x00
build: 0x01
caps: 0x07 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0
extension strings: hmac-secret
aaguid: 9f77e279a6e24d58b70031e5943c6a98
options: rk, up, nouv, noplat, clientPin
maxmsgsiz: 2048
pin protocols: 1
pin retries: 8

I can't set a residential cred with the HyperFido from Hypersecu. Exactly same steps and input for both devices. 

Is it possible, that this token does not support resident credentials? I thought this was obligatory for FIDO2 devices. 

If this token does not support resident credentials, shouldn't fido2-cred -M -r fail then instead of pretending to have generated a credential?

regards
Hadmut

**Comment by hadmut** [comment]
Since ssh supports using FIDO1/2 tokens as a second factor starting with version 8.2 I just tried this (it makes use of libfido2 as well). 

Again: 

ssh-keygen -t ecdsa-sk -f ~/.ssh/id_ecdsa_skr -O resident

claims success for both tokens (and correctly gives an error message for an older U2F token), but ssh-keygen -K works only for the yubico token, not for the hypersecu.


I'm wondering whether libfido2 just fails to read the resident list from hypersecu tokens, or whether the token itself is somewhat cheating, not beeing able to offer real resident keys, and libfido2 doesn't notice.

**Comment by martelletto** [comment]
Hi,

The HS HyperFIDO authenticator does not appear to support [FIDO 2.1 Credential Management](https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorCredentialManagement), which is required by OpenSSH for resident keys. As of OpenSSH 8.4, `ssh-keygen` will fail to create resident keys on authenticators that do not support FIDO 2.1 Credential Management.

To confirm this hypothesis, could you provide the output of `$ FIDO_DEBUG=1 fido2-token -L -r 2>&1 | grep cbor_parse_reply`? It would be interesting to see which status code is being returned by the authenticator.

Thank you,

-p.

**Comment by hadmut** [comment]
cbor_parse_reply: blob[0]=0x10

**Comment by martelletto** [comment]
Thanks. As expected, 0x10 [is not defined as a status code](https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#error-responses) in the spec. While strange, it corroborates the hypothesis that the authenticator does not support FIDO 2.1 Credential Management.

**Comment by roycewilliams** [comment]
Interesting. What's the best way to degrade gracefully for the user here?

**Comment by martelletto** [comment]
The best way to degrade gracefully in this case is to refuse to generate resident credentials on the authenticator. This is the behaviour implemented in OpenSSH 8.4. To be precise, OpenSSH 8.4 checks for [FIDO 2.1 Credential Protection support](https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#sctn-credProtect-extension). FIDO 2.1 Credential Protection and Credential Management go hand-in-hand, since one doesn't make sense without the other. Technically speaking, OpenSSH should check for both.

**Comment by martelletto** [comment]
Closing; please let me know if there is anything else I can help with.
