### ISSUE TITLE
AuthData length is incorrect

### ISSUE THREAD

**Issue by mskonovalov** [Yubico/libfido2#241]
**What version of libfido2 are you using?**
1.5.0

**What operating system are you running?**
Macos

**What application are you using in conjunction with libfido2?**
Golang binding https://github.com/keys-pub/go-libfido2

**How does the problem manifest itself?**
If I enable FIDO_DEBUG I can see
`cbor_decode_assert_authdata: buf=0xd5081f0, len=37`
But `fido_assert_authdata_len` returns 39 bytes
see here https://github.com/keys-pub/go-libfido2/issues/17#issuecomment-723276957

**Is the problem reproducible?**
Yes

**What are the steps that lead to the problem?**
Calling fido2-assert via GoLang Binding https://github.com/keys-pub/go-libfido2

**Does the problem happen with different authenticators?**
Didn't check

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey FIDO+CCID@14100000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice: vendor=0x1050, product=0x0406 (Yubico YubiKey FIDO+CCID)
</pre>
</details>

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;

</pre>
</details>

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ calling getAssertion via GoLang binding
fido_tx: d=0x4f3d410, cmd=0x06, buf=0x4f3d410, count=8
0000: ba df 46 c1 f6 92 cc 53
fido_rx: d=0x4f3d410, cmd=0x06, buf=0x4f3d418, count=17, ms=-1
rx_preamble: initiation frame at 0x7ffeefbff398
0000: ff ff ff ff 86 00 11 ba df 46 c1 f6 92 cc 53 00
0016: 19 00 3b 02 05 02 04 05 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x4f3d418, len=17
0000: ba df 46 c1 f6 92 cc 53 00 19 00 3b 02 05 02 04
0016: 05
fido_dev_get_cbor_info_tx: dev=0x4f3d410
fido_tx: d=0x4f3d410, cmd=0x10, buf=0x7ffeefbff3f7, count=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x4f3d410, ci=0x67045f0, ms=-1
fido_rx: d=0x4f3d410, cmd=0x10, buf=0x7ffeefbfebf0, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffeefbfeb08
0000: 00 19 00 3b 90 00 bf 00 aa 01 83 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 6c 46 49 44 4f
0032: 5f 32 5f 31 5f 50 52 45 02 82 6b 63 72 65 64 50
0048: 72 6f 74 65 63 74 6b 68 6d 61 63 2d 73 65 63 72
rx: payload_len=191
rx: continuation frame at 0x7ffeefbfeb08
0000: 00 19 00 3b 00 65 74 03 50 ee 88 28 79 72 1c 49
0016: 13 97 75 3d fc ce 97 07 2a 04 a5 62 72 6b f5 62
0032: 75 70 f5 64 70 6c 61 74 f4 69 63 6c 69 65 6e 74
0048: 50 69 6e f4 75 63 72 65 64 65 6e 74 69 61 6c 4d
rx: continuation frame at 0x7ffeefbfeb08
0000: 00 19 00 3b 01 67 6d 74 50 72 65 76 69 65 77 f5
0016: 05 19 04 b0 06 81 01 07 08 08 18 80 09 81 63 75
0032: 73 62 0a 82 a2 63 61 6c 67 26 64 74 79 70 65 6a
0048: 70 75 62 6c 69 63 2d 6b 65 79 a2 63 61 6c 67 27
rx: continuation frame at 0x7ffeefbfeb08
0000: 00 19 00 3b 02 64 74 79 70 65 6a 70 75 62 6c 69
0016: 63 2d 6b 65 79 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffeefbfebf0, len=191
0000: 00 aa 01 83 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 6c 46 49 44 4f 5f 32 5f 31 5f 50 52
0032: 45 02 82 6b 63 72 65 64 50 72 6f 74 65 63 74 6b
0048: 68 6d 61 63 2d 73 65 63 72 65 74 03 50 ee 88 28
0064: 79 72 1c 49 13 97 75 3d fc ce 97 07 2a 04 a5 62
0080: 72 6b f5 62 75 70 f5 64 70 6c 61 74 f4 69 63 6c
0096: 69 65 6e 74 50 69 6e f4 75 63 72 65 64 65 6e 74
0112: 69 61 6c 4d 67 6d 74 50 72 65 76 69 65 77 f5 05
0128: 19 04 b0 06 81 01 07 08 08 18 80 09 81 63 75 73
0144: 62 0a 82 a2 63 61 6c 67 26 64 74 79 70 65 6a 70
0160: 75 62 6c 69 63 2d 6b 65 79 a2 63 61 6c 67 27 64
0176: 74 79 70 65 6a 70 75 62 6c 69 63 2d 6b 65 79
parse_reply_element: cbor type
parse_reply_element: cbor type
fido_dev_open_rx: FIDO_MAXMSG=2048, maxmsgsiz=1200
fido_dev_get_assert_tx:
fido_tx: d=0x4f3d410, cmd=0x10, buf=0x67448c0, count=148
0000: 02 a3 01 75 63 61 6e 76 61 2e 6f 6b 74 61 70 72
0016: 65 76 69 65 77 2e 63 6f 6d 02 58 20 56 22 53 b8
0032: 23 42 36 c2 89 5e f7 6c 9b 00 da 6d f8 56 17 60
0048: 33 ac bc 6e bf 07 7a 2a 95 57 50 93 03 81 a2 62
0064: 69 64 58 40 55 f1 66 a5 f0 9f 13 5d e3 f0 77 70
0080: e6 28 82 b8 91 88 15 98 0b f9 70 00 b1 9c f9 2d
0096: 95 e5 a9 2a 1a 05 c9 a7 86 4b 3a d1 56 d2 42 a4
0112: b0 d5 ab 38 3b c3 b9 30 54 c5 c7 88 71 13 73 77
0128: 79 9e fa a5 64 74 79 70 65 6a 70 75 62 6c 69 63
0144: 2d 6b 65 79
fido_dev_get_assert_rx:
fido_rx: d=0x4f3d410, cmd=0x10, buf=0x7ffeefbfec30, count=2048, ms=-1
rx_preamble: initiation frame at 0x7ffeefbfeb48
0000: 00 19 00 3b 90 00 cb 00 a3 01 a2 62 69 64 58 40
0016: 55 f1 66 a5 f0 9f 13 5d e3 f0 77 70 e6 28 82 b8
0032: 91 88 15 98 0b f9 70 00 b1 9c f9 2d 95 e5 a9 2a
0048: 1a 05 c9 a7 86 4b 3a d1 56 d2 42 a4 b0 d5 ab 38
rx: payload_len=203
rx: continuation frame at 0x7ffeefbfeb48
0000: 00 19 00 3b 00 3b c3 b9 30 54 c5 c7 88 71 13 73
0016: 77 79 9e fa a5 64 74 79 70 65 6a 70 75 62 6c 69
0032: 63 2d 6b 65 79 02 58 25 53 94 5f ec 10 94 a9 1e
0048: 54 e1 7c 04 f0 09 d6 d5 06 6f 1b aa 37 ef 08 c7
rx: continuation frame at 0x7ffeefbfeb48
0000: 00 19 00 3b 01 0c b9 08 69 e5 e6 4d 0c 01 00 00
0016: 01 da 03 58 47 30 45 02 21 00 8d ae 92 50 67 46
0032: 1f ad d3 ab 42 13 18 24 00 67 89 60 b5 1a 87 82
0048: 2d 75 d0 fd 1a 63 2e 25 f7 71 02 20 7f de fb 75
rx: continuation frame at 0x7ffeefbfeb48
0000: 00 19 00 3b 02 72 53 39 9f 42 5d 64 1b 57 e0 0f
0016: fb 57 50 9e 39 b5 d4 57 97 17 c0 20 11 ad 18 1b
0032: 48 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0x7ffeefbfec30, len=203
0000: 00 a3 01 a2 62 69 64 58 40 55 f1 66 a5 f0 9f 13
0016: 5d e3 f0 77 70 e6 28 82 b8 91 88 15 98 0b f9 70
0032: 00 b1 9c f9 2d 95 e5 a9 2a 1a 05 c9 a7 86 4b 3a
0048: d1 56 d2 42 a4 b0 d5 ab 38 3b c3 b9 30 54 c5 c7
0064: 88 71 13 73 77 79 9e fa a5 64 74 79 70 65 6a 70
0080: 75 62 6c 69 63 2d 6b 65 79 02 58 25 53 94 5f ec
0096: 10 94 a9 1e 54 e1 7c 04 f0 09 d6 d5 06 6f 1b aa
0112: 37 ef 08 c7 0c b9 08 69 e5 e6 4d 0c 01 00 00 01
0128: da 03 58 47 30 45 02 21 00 8d ae 92 50 67 46 1f
0144: ad d3 ab 42 13 18 24 00 67 89 60 b5 1a 87 82 2d
0160: 75 d0 fd 1a 63 2e 25 f7 71 02 20 7f de fb 75 72
0176: 53 39 9f 42 5d 64 1b 57 e0 0f fb 57 50 9e 39 b5
0192: d4 57 97 17 c0 20 11 ad 18 1b 48
adjust_assert_count: cbor_type
adjust_assert_count: cbor_type
adjust_assert_count: cbor_type
cbor_decode_assert_authdata: buf=0x65261c0, len=37
</pre>
</details>

**Comment by martelletto** [comment]
Hi,

Like `fido_cred_authdata_ptr()`, `fido_assert_authdata_ptr()` returns a pointer to a CBOR-encoded byte string. This information was missing from `fido_assert_authdata_ptr()`'s documentation, which has been corrected in d42c63f. My apologies.

If you are validating authdata, I strongly suggest reconstructing it with the expected values and using that to check the signature.

If you are marshalling authdata for transmission to a WebAuthn server, this code could be useful: https://github.com/martelletto/fido2-webauthn-client.

I will close the ticket, but feel free to ask questions if you have any.

-p.

**Comment by mskonovalov** [comment]
Hi @martelletto thanks for quick response.

You are right this was it. After fixing this everything works fine.

I'm just curious if there is a reason for this inconsistency considering that other fields of data are not CBOR-encoded?
Thank you.

**Comment by martelletto** [comment]
The rationale at the time was that, since functions to access the different parts of authdata were already provided, callers to `fido_{assert,cred}_authdata_ptr()` were most likely interested in parsing authdata themselves, from scratch, as it arrived from the authenticator. Given the feedback on these functions (you were not the only one bitten by this), that proved to be a bogus assumption. At this point, the behaviour of these functions is mostly historical.

For `fido_cred_authdata_ptr()`, a `fido_cred_authdata_raw_ptr()` counterpart was added. We should probably do the same for `fido_assert_authdata_ptr()`.

**Comment by mskonovalov** [comment]
Thanks for the explanation. Yeah, adding *raw* function sounds reasonable.
Thank you.
