### ISSUE TITLE
Windows binaries dynamically linked against Visual C++ runtime

### ISSUE THREAD

**Issue by Nehluxhes** [Yubico/libfido2#246]
Hello,

crypto-46.dll in the windows binaries releases is dynamically linked against Visual C++ runtime (vcruntime140.dll more specifically), is this intended?
Would it be possible to get a statically linked version with no additional dependencies?

Or if not, I guess this dependency should be added to the documentation.

Thanks.

**Comment by martelletto** [comment]
Definitely not intended. Thanks for pointing it out.

**Comment by martelletto** [comment]
Does [this](https:///ambientworks.net/tmp/libfido2-1.6.0gh246.zip) (sha256sum a7f7b253fada1f1b5f22962a2943bcfafd3ce80a60212f8e633e98d944de63aa) look any better?

**Comment by Nehluxhes** [comment]
Thanks but I am afraid not, I was able to successfully compile a test project using the static lib files (and linking against bcrypt.lib;hid.lib;setupapi.lib ) but they seem to have been compiled with the /MD flag so they still require the VC runtime
https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-160

**Comment by martelletto** [comment]
Thank you for the pointer. Is [this build](https://ambientworks.net/tmp/libfido2-1.6.0gh246-1.zip) (sha256sum a7aa4696fe7cf82594cc1fa46a2ea4607b8c81205328e3ab478915c439226e8c) any better? (See commit 88bda07).

**Comment by Nehluxhes** [comment]
Yes it is working, no CRT dependency anymore, thank you very much!

**Comment by martelletto** [comment]
Fixed in d0499aa.
