### ISSUE TITLE
Add support for communication via NFC for MacOS

### ISSUE THREAD

**Issue by cyberbob** [Yubico/libfido2#249]
If I understand correctly, currently the FIDO functionality is only available via USB. Although devices such as Yubikey 5 NFC have the ability to communicate using NFC. Without this support I cannot use webauthm in e.g. Firefox without connecting to a USB port, even though the token is on an external NFC reader and I can use e.g. OpenPGP. Is it planned to introduce NFC support in this library ?

**Comment by martelletto** [comment]
On Linux, yes: https://github.com/Yubico/libfido2/issues/247#issuecomment-740429352.

**Comment by cyberbob** [comment]
I'm using ACR1252U and Yubikey 5 NFC on OSX, is this the same code base as for Linux ?

**Comment by cyberbob** [comment]
I've reopened - will be easier to track potential progress on this.

**Comment by martelletto** [comment]
Implemented in https://github.com/Yubico/libfido2/pull/530.

**Comment by cyberbob** [comment]
Thank You!

**Comment by dhcav** [comment]
@cyberbob I'm new to this area of tech, could you pls confirm: you are using an NFC FIDO token with a USB reader to achieve the same result as plugging the key in directly? 
I am getting a FIDO-capable NFC chip implanted in my hand and trying to establish if I can carry a compact USB reader with me in case I need to auth on a non-NFC-capable device.
