### ISSUE TITLE
RFE: Add SOVERSION to build properties for ABI versioning

### ISSUE THREAD

**Issue by garybuhrmaster** [Yubico/libfido2#25]
For distribution and packaging purposes it would be useful (presuming the library ABI is mostly stable at this point), to add the SOVERSION property to the build, allowing library minor and patch updates without forcing applications to be rebuilt due to library minor/patch bumps.

Presuming that the FIDO_MAJOR value will be bumped for ABI changes, perhaps something like the following might work (or add a new ABI_VERSION value if the FIDO_MAJOR not sufficiently stable or not intended to be thought if as a ABI version?):

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index bff3a78..5e1b4ab 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -83,7 +83,7 @@ elseif(APPLE)
                "-framework IOKit")
 endif()
 set_target_properties(fido2_shared PROPERTIES OUTPUT_NAME fido2
-       VERSION ${FIDO_VERSION})
+       VERSION ${FIDO_VERSION} SOVERSION ${FIDO_MAJOR})
 install(TARGETS fido2_shared
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
```

Thank you for your consideration.

**Comment by martelletto** [comment]
Makes perfect sense to me. Committed in 8a988142. Thank you!
