### ISSUE TITLE
Question: what is the analogue for navigator.credetials.get()

### ISSUE THREAD

**Issue by mskonovalov** [Yubico/libfido2#250]
In Web browser API https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-get
there is a get function that allows to do 2 things:
provide a list of CredentailID and also interrupt the interaction with mfa device.

This allows the following flow:
I have 2 mfa yubikey devices plugged in.
Then I do request to authn server and get a list of registered mfa factors with CredentialID for each and a challenge.
Then in the browser flow when I request navigator.credentials.get() all attached mfa devices started to blink and whatever I touch the assertion from it will be got for the follow up requests.
And interaction with other mfa devices will be cancelled.

How to achieve similar with libfido2?
Thanks

**Comment by mskonovalov** [comment]
For example, the same is suppported in python-fido2
where in `get_assertion` function you can pass the list of `"allowCredentials": [{"type": "public-key", "id": credential_id}],`

**Comment by martelletto** [comment]
Hi,

- You can use [`fido_assert_allow_cred()`](https://developers.yubico.com/libfido2/Manuals/fido_assert_allow_cred.html) to build a list of credentials allowed in an assertion. An example is provided in [`examples/assert.c`](https://github.com/Yubico/libfido2/blob/master/examples/assert.c).
- You can use [`fido_dev_get_touch_begin()`](https://developers.yubico.com/libfido2/Manuals/fido_dev_get_touch_begin.html) to have all authenticators blink and wait for touch. An example is provided in [`examples/select.c`](https://github.com/Yubico/libfido2/blob/master/examples/select.c).

Hope that helps,

-p.

**Comment by mskonovalov** [comment]
Thanks for the suggestion.

`fido_assert_allow_cred()` does the trick.

I'm curious if there is a way to interrupt the `fido_dev_get_assert`?

**Comment by mskonovalov** [comment]
@martelletto If I understand correctly (correct me if I'm wrong) `fido_dev_get_touch_begin()` is not related to `fido_dev_get_assert` call.
So if I start using `fido_dev_get_touch_begin` I'd need to ask user to touch the device twice: first to choose which one he wants to use and then second time when I call `fido_dev_get_assert` on the chosen device.
Is there a way to do it with a single touch?

Currently I just do parallel `fido_dev_get_assert` in separate threads to all connected devices and after successful result from one device I would like to interrupt calls to the rest of the devices.
Thanks

**Comment by mskonovalov** [comment]
ok, I think I achieved the desired behavior with `fido_dev_cancel`

**Comment by martelletto** [comment]
Since you know the credential ID, you can use an assertion with `user presence = false` to decide which authenticator to use. This logic is implemented here: https://github.com/openssh/openssh-portable/blob/master/sk-usbhid.c#L323-L371.

However, if the credentials are protected with the `userVerificationRequired` extension and PIN is the only user verification method available, you will either need to ask the user which authenticator to use or risk decrementing the PIN retry counters of authenticators with a different PIN. The former is implemented by `fido_dev_get_touch_begin()`.
