### ISSUE TITLE
Unclear documentation for fido_init and threads

### ISSUE THREAD

**Issue by riastradh** [Yubico/libfido2#253]
- The [fido_init man page](https://developers.yubico.com/libfido2/Manuals/fido_init.html) doesn't mention threads.
- A [comment on an issue about thread safety](https://github.com/Yubico/libfido2/issues/43#issuecomment-504729819) suggests fido_init is meant to be a once-only function -- I took

  > the only function you have to be careful with is fido_init, which tells the library whether to emit debug output. Since fido_init is a one-shot initialisation function

  to mean that an application must call fido_init exactly once before any other fido_* function, for instance with pthread_once.
- The implementation of fido_init doesn't actually work if you have multiple threads -- as of 15fc7c41c7c748668a11464b124e5988129c817f, the variables that fido_init sets (via fido_log_init) are all thread-local, so if you want debug output to be enabled, you _must_ call fido_init in _every_ thread before fido_*; merely calling it once, for instance with pthread_once, will fail to enable logging in any other thread.

What semantics is intended?  Should every thread call fido_init before any other fido_* calls, or should an application make sure to call fido_init exactly once before any other fido_* function in any thread, or what?

**Comment by watk** [comment]
I have a related question. Is it safe to call, e.g., fido_dev_get_assert() on one thread and call fido_dev_cancel() on another thread? Of course, since fido_dev_get_assert() is blocking we can't protect the fido_dev_t* with a mutex, so this looks racey.

The context is implementing simultaneously querying multiple connected devices, waiting for the first response, and then canceling the remaining pending calls.

**Comment by martelletto** [comment]
The former: every thread needs to call `fido_init()`, the rationale being that there is no shared global state kept by the library. I've pushed d02a261 to clarify the documentation. Thanks for pointing it out.

**Comment by riastradh** [comment]
Thanks!
