### ISSUE TITLE
build fails on el7

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#260]
Hi,
Any plans to fix below error ?
/var/lib/pb2/internal/extra/libfido2/src/hid_linux.c: In function 'timespec_to_ms':
/var/lib/pb2/internal/extra/libfido2/src/hid_linux.c:388:35: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  388 |  if (ts->tv_sec < 0 || ts->tv_sec > INT64_MAX / 1000LL ||
      |                                   ^
/var/lib/internal/extra/libfido2/src/hid_linux.c:389:49: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  389 |      ts->tv_nsec < 0 || ts->tv_nsec / 1000000LL > INT64_MAX)
      |                                                 ^

**Comment by sb230132** [comment]
Fido version is 1.5.0

**Comment by martelletto** [comment]
This was addressed in 7a17a4e9127fb6df6278f19396760e7d60a5862c (which is not part of 1.5.0). You can get past the warning in 1.5.0 by defining `CFLAGS` accordingly, prior to the invocation of CMake: `$ export CFLAGS=-Wno-error=type-limits`. For more information, see https://github.com/Yubico/libfido2/issues/210.
