### ISSUE TITLE
Question: Can someone request yubico notorize/release the 1.6.0 release on their website?

### ISSUE THREAD

**Issue by garybuhrmaster** [Yubico/libfido2#263]
( somewhat related to https://github.com/Yubico/libfido2/issues/209 )

Is it possible to poke yubico staff to notorize (and post) libfido 1.6.0 on their website?  While the website announced the 1.6.0 release (on their release notes page) back in late December (when it was tagged on github), the actual yubico release website page has not yet been updated.  While I certainly understand there was a major holiday period in there, it is starting to look like the work has been deferred indefinitely.

Thanks.

**Comment by martelletto** [comment]
A signed tarball is now available at https://developers.yubico.com/libfido2/Releases/. Windows and Ubuntu PPA packages will follow shortly. Thank you!
