### ISSUE TITLE
fido_dev_info_manifest() cound not detect some devices on Windows

### ISSUE THREAD

**Issue by ElvisBlue** [Yubico/libfido2#264]
As the tittle said fido_dev_info_manifest() failed for some devices on Windows. After debugging I found the code causes this problem

file: hid_win.c
function: get_int(HANDLE dev, int16_t *vendor_id, int16_t *product_id)

This function uses WinAPI HidD_GetAttributes() to get vendor_id and product_id. vendor_id and product_id returned from HidD_GetAttributes() are in type "unsigned short" but they are comparing with max value of "short" (INT16_MAX).

```
if (HidD_GetAttributes(dev, &attr) == false ||
	    attr.VendorID > INT16_MAX || attr.ProductID > INT16_MAX) {
		fido_log_debug("%s: HidD_GetAttributes", __func__);
		return (-1);
	}
```
This causes any device which have product_id or vendor_id larger than 0x7FFF fail to be detected by function fido_dev_info_manifest().

**Comment by martelletto** [comment]
Fixed in abe77473c136e5de3194c51cb69c7b9f4d7b1d81. Thank you!
