### ISSUE TITLE
libfido2 1.5.0 vs 1.6.0

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#266]
Hello,
Where can i find all differences between 1.5.0 and 1.6.0. Like what all issues has been resolved etc.
Regards
Satish

**Comment by martelletto** [comment]
A summary is available in [NEWS](https://github.com/Yubico/libfido2/blob/master/NEWS). A comprehensive diff can be obtained with `git log -p 1.5.0..1.6.0`.
