### ISSUE TITLE
Building on macOS 10.11 and older fails due to missing clock_gettime

### ISSUE THREAD

**Issue by trodemaster** [Yubico/libfido2#267]
We recently added libfido2 to macports (https://ports.macports.org/port/libfido2/summary) and discovered that it fails to build on with macOS 10.11 and older. It appears other build targets like OpenBSD have worked around this issue and ideally older macOS versions should be supported as well. 

**What version of libfido2 are you using?**
1.6.0

**What operating system are you running?**
macOS 10.11

**What application are you using in conjunction with libfido2?**
OpenSSH 8.4p1

**How does the problem manifest itself?**
When building on the target systems.
```
#error "please provide an implementation of clock_gettime() for your platform"
 ^
1 error generated.
```

**Is the problem reproducible?**
Yes

**What are the steps that lead to the problem?**
Building via the stated process

**Does the problem happen with different authenticators?**
N/A

**Comment by martelletto** [comment]
1.6.0 won't work on POSIX-like systems that lack `clock_gettime()`.  The good news is that 1.5.0 should work, and future releases of libfido2 as well.
