### ISSUE TITLE
Version 1.0 stops working with SoftU2F

### ISSUE THREAD

**Issue by Silvercast** [Yubico/libfido2#27]
I used to be able to test libfido2 with [SoftU2F](https://github.com/github/SoftU2F) on old version of libfido2 but new version doesn't let me.

I'm on macOS 10.14.4 . Could be the SoftU2F doesn't return manufacturer name but that shouldn't crash nor stop the functionality.

```
get_utf8: IOHIDDeviceGetProperty
get_str: get_utf8 manufacturer
is_fido: unsupported report len
is_fido: unsupported report len
is_fido: unsupported report len
is_fido: unsupported report len
get_utf8: IOHIDDeviceGetProperty
```

**Comment by martelletto** [comment]
Hi,

It is unclear to me which sequence of API calls is being used. However, the manufacturer string should only concern fido_dev_info_manifest(). It should still be possible to fido_dev_open() it, and talk to it normally.

It would be interesting to find out why get_utf8() is failing. Can you use MacOS's built-in system tool to find out whether the device has a manufacturer string configured?

-p.

**Comment by Silvercast** [comment]
I will reopen when I have more info on this.
