### ISSUE TITLE
fido_dev_get_assert fails with unsupported user verification set to false

### ISSUE THREAD

**Issue by Nehluxhes** [Yubico/libfido2#271]
Hi,

I am setting user verification to false in my code with
fido_assert_set_uv(assertions, FIDO_OPT_FALSE);

and everything is working fine most of the time.
But if I happen to use a fido key that does not support user verification at all, fido_dev_get_assert returns FIDO_ERR_UNSUPPORTED_OPTION

I have to explicitly set user verification to FIDO_OPT_OMIT for it to work.
That seems weird to me, if I set it to false I expect the lib to not use it, whether it is supported or not.

Regards,

**Comment by martelletto** [comment]
By calling `fido_assert_set_uv()` with `FIDO_OPT_FALSE`, you are explicitly asking the authenticator to disable user verification. If the authenticator does not support user verification, a subsequent `fido_dev_get_assert()` will fail with `FIDO_ERR_UNSUPPORTED_OPTION`. This is per spec.

-p.
