### ISSUE TITLE
Compiling libfido2 on RHEL 7.8

### ISSUE THREAD

**Issue by andersonreloaded** [Yubico/libfido2#292]
Folks,

Having tried Yubikey 5 on Ubuntu 18.04 LTS successfully, I am trying to test the same on RHEL 7.8.
However, unlike for Ubuntu, packages are not available for installation in RHEL.
Started building the required packages from source. 

When it comes to building libfido2 (release 1.6.0), I am stuck at the following problem.

```
/usr/bin/ld: cbor.c.o: plugin needed to handle lto object
/usr/bin/ld: serialization.c.o: plugin needed to handle lto object
/usr/bin/ld: arrays.c.o: plugin needed to handle lto object
/usr/bin/ld: common.c.o: plugin needed to handle lto object
/usr/bin/ld: floats_ctrls.c.o: plugin needed to handle lto object
/usr/bin/ld: bytestrings.c.o: plugin needed to handle lto object
/usr/bin/ld: strings.c.o: plugin needed to handle lto object
/usr/bin/ld: maps.c.o: plugin needed to handle lto object
/usr/bin/ld: ints.c.o: plugin needed to handle lto object
../src/libfido2.a(dev.c.o): In function `fido_dev_get_touch_begin':
dev.c:(.text+0xde7): undefined reference to `cbor_build_bytestring'
dev.c:(.text+0xe89): undefined reference to `cbor_new_definite_bytestring'
../src/libfido2.a(info.c.o): In function `decode_versions':
info.c:(.text+0xe5): undefined reference to `cbor_isa_array'
info.c:(.text+0xf8): undefined reference to `cbor_array_is_definite'
info.c:(.text+0x12a): undefined reference to `cbor_array_size'
`/usr/bin/ld: cbor.c.o: plugin needed to handle lto object'
```

Please suggest on how to resolve the issue...

**Comment by andersonreloaded** [comment]
@martelletto I built libcbor as a static library.

**Comment by martelletto** [comment]
You will need libcbor as a shared library to build libfido2 as a shared library; try passing `-DBUILD_SHARED_LIBS=ON` to cmake when building libcbor.

**Comment by andersonreloaded** [comment]
@martelletto I have tried with shared library version of libcbor.

For libcbor, I have used the following:
`cmake3 -DHAVE_CBOR_H=/usr/local/include/cbor -DBUILD_SHARED_LIBS=ON libcbor`

For building libfido, I have used the following
`cmake3 -DCBOR_INCLUDE_DIRS=/usr/local/include/cbor -DCBOR_LIBRARY_DIRS=/usr/local/lib64 ..`

Now, libfido2-1.6.0 compiled successfully. Thank you @martelletto.

**Comment by andersonreloaded** [comment]
I also learnt that `PKG_CONFIG_PATH` variable needs to be set for compiling the packages from source.

`export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib64/pkgconfig/`

**Comment by martelletto** [comment]
Thank you! Glad it's working.
