### ISSUE TITLE
Resulting Shared Library in wrong destination

### ISSUE THREAD

**Issue by xgcssch** [Yubico/libfido2#316]
**What version of libfido2 are you using?**
1.7

**How does the problem manifest itself?**
When building fido2 as a shared library, the resulting Object is not placed in the correct directory according

https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
https://cmake.org/cmake/help/latest/command/install.html

This is due to specifying

```
RUNTIME DESTINATION ${CMAKE_INSTALL_LIBDIR})
```

in line 123 of file `src/CMakeLists.txt`.

It should be changed to 

```
RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
```

**Comment by martelletto** [comment]
Fixed in d3ed2bfc1172074f81ce04973f33db532c4ec141. Thank you!
