### ISSUE TITLE
Linking with hidapi is broken on Linux

### ISSUE THREAD

**Issue by susnux** [Yubico/libfido2#323]
**What version of libfido2 are you using?**
1.7.0

**What operating system are you running?**
Linux (openSUSE Tumbleweed)

**What application are you using in conjunction with libfido2?**
`-`

**How does the problem manifest itself?**
When building with hidapi enabled linking fails because `hid_hidapi.c`, `nfc_linux.c` rely on `hid_*` functions from `hid_unix.c`.

This can be fixed with this patch:
```diff
diff -Nur libfido2-1.7.0/src/CMakeLists.txt new/src/CMakeLists.txt
--- libfido2-1.7.0/src/CMakeLists.txt   2021-03-29 17:28:56.000000000 +0200
+++ new/src/CMakeLists.txt      2021-04-17 04:08:16.614325721 +0200
@@ -45,6 +45,9 @@
 
 if(USE_HIDAPI)
        list(APPEND FIDO_SOURCES hid_hidapi.c)
+       if(NOT WIN32 AND NOT APPLE)
+               list(APPEND FIDO_SOURCES hid_unix.c)
+       endif()
 elseif(WIN32)
        list(APPEND FIDO_SOURCES hid_win.c)
 elseif(APPLE)
```

**Is the problem reproducible?**
yes

**What are the steps that lead to the problem?**
Build with `USE_HIDAPI`.

**Does the problem happen with different authenticators?**
`-`

**Please include the output of `fido2-token -L`.**
`-`

**Please include the output of `FIDO_DEBUG=1`.**
`-`

**Comment by martelletto** [comment]
fixed in 4bd253d; thank you for the report & patch!
