### ISSUE TITLE
fido_dev_open() fails when called in Objective-C project

### ISSUE THREAD

**Issue by staziz04** [Yubico/libfido2#328]
Hi

I am trying to write C wrapper over a libfido2 lib in Objective-C project. However fido_dev_open() function fails with following trace:

IOServiceOpen failed: 0xe00002e2
fido_hid_open: IOHIDDeviceOpen
fido_dev_open_tx: dev->io.open 

It works fine if called in a C project.

Any clues why it isn't working..

**Comment by martelletto** [comment]
Nothing comes to mind. Can you print the return value of `IOHIDDeviceOpen()`?

**Comment by staziz04** [comment]
> Nothing comes to mind. Can you print the return value of `IOHIDDeviceOpen()`?

I am using static lib. I got the this debug info only.
IOServiceOpen failed: 0xe00002e2
fido_hid_open: IOHIDDeviceOpen
fido_dev_open_tx: dev->io.open

**Comment by martelletto** [comment]
Oh, my apologies. You have already included the information I was asking. It looks like a permission error:

> IOServiceOpen failed: 0xe00002e2

See:

```c
#define kIOReturnNotPermitted    iokit_common_err(0x2e2) // not permitted
```
in https://opensource.apple.com/source/xnu/xnu-4570.41.2/iokit/IOKit/IOReturn.h.auto.html.

It is not immediately obvious to me why the behaviour differs between C and Objective-C, but hopefully the nature of the error code might provide a clue.

**Comment by martelletto** [comment]
Great! Glad it helped.
