### ISSUE TITLE
Is libfido2 saving its Debug Info somewhere.

### ISSUE THREAD

**Issue by staziz04** [Yubico/libfido2#329]
I am using libfido2 in my project. I want to check the debug info/errors if any from libfido2 when I am not debugging. Is the lib saving/logging the info somewhere. I am on mac platform.

**Comment by martelletto** [comment]
When not in debugging mode, libfido2 doesn't log anything. When in debugging mode, libfido2 produces log output on stderr. An application may use `fido_set_log_handler()` to redirect the output elsewhere, if it so wishes.

**Comment by staziz04** [comment]
Perfect. Got it !! Thanks !
