### ISSUE TITLE
Yubico 5 NFC with openssh fido resident keys: "debug1:ssh_sk_enroll: /dev/hidraw2 does not support credprot, refusing to create unprotected resident/verify-required key"

### ISSUE THREAD

**Issue by inmmi** [Yubico/libfido2#334]
Hi,
I'm trying out the support for FIDO/U2F hardware authenticators added OpenSSH release >= 8.2 (https://www.openssh.com/txt/release-8.2)

Generating and authenting with the private/public pair key generated thanks to   "$ ssh-keygen -t ecdsa-sk -f ~/.ssh/id_ecdsa_sk" works fine.

But trying the FIDO resident keys feature of that same release, in order to be able to move without hassle my token bewtween computers, fails  with this error message:
Generating public/private ecdsa-sk key pair.
```
You may need to touch your authenticator to authorize key generation.
Enter PIN for authenticator: 
debug3: start_helper: started pid=8513
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/lib/openssh/ssh-sk-helper 
debug1: sshsk_enroll: provider "internal", device "(null)", application "ssh:", userid "(null)", flags 0x25, challenge len 0 with-pin
debug1: sshsk_enroll: using random challenge
debug1: sk_probe: 1 device(s) detected
debug1: sk_probe: selecting sk by touch
debug1: ssh_sk_enroll: using device /dev/hidraw2
debug1: ssh_sk_enroll: /dev/hidraw2 does not support credprot, refusing to create unprotected resident/verify-required key
debug1: sshsk_enroll: provider "internal" returned failure -2
debug1: ssh-sk-helper: Enrollment failed: requested feature not supported
debug1: ssh-sk-helper: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -59
debug3: reap_helper: pid=8513
Key enrollment failed: requested feature not supported

```
But according to https://developers.yubico.com/libfido2/Release_Notes.html , "FIDO2 credential protection (credprot) support." was added to libfido2 1.4.0 and i'm using version 1.6.0 

So just wondering if this feature is no supported on my Yubico 5 NFC token or if that might be a bug. You'll find below further information on the token
Thanks

``
$ ykman info
Device type: YubiKey 5 NFC
Serial number: 10140062
Firmware version: 5.1.2
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.

Applications	USB          	NFC          
FIDO2       	Enabled      	Enabled      	
OTP         	Enabled      	Enabled      	
FIDO U2F    	Enabled      	Enabled      	
OATH        	Enabled      	Enabled      	
YubiHSM Auth	Not available	Not available	
OpenPGP     	Enabled      	Enabled      	
PIV         	Enabled      	Enabled      	

$ ykman fido2 info
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try 'ykman -h' for help.

Error: No such command 'fido2'.

$ ykman fido info
PIN is set, with 8 attempt(s) remaining.
``

**Comment by martelletto** [comment]
It appears that your key does not support credential protection, a FIDO2.1 extension required by ssh for the resident keys case. What is the output of `fido2-token -I /dev/hidraw2`?

**Comment by inmmi** [comment]
> It appears that your key does not support credential protection, a FIDO2.1 extension required by ssh for the resident keys case. What is the output of `fido2-token -I /dev/hidraw2`?

oops, sorry for not posting that. Here it's:
```
proto: 0x02
major: 0x05
minor: 0x01
build: 0x02
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0
extension strings: hmac-secret
aaguid: fa2b99dc9e3942578f924a30d23c4118
options: rk, up, noplat, clientPin
maxmsgsiz: 1200
maxcredcntlst: 0
maxcredlen: 0
fwversion: 0x0
pin protocols: 1
pin retries: 8
uv retries: undefined
```
TBH, my hope is that this (very useful) feature is supported on this token :-)

**Comment by martelletto** [comment]
I am afraid your token does not support the feature. :(

**Comment by inmmi** [comment]
> I am afraid your token does not support the feature. :(

Bummer :( 
Just for the record and in the hope that might useful for others, what bits of information made you conclude that this feature was not supported on this token please ?
Thanks

**Comment by martelletto** [comment]
The `credProtect` string is absent from the list of extension strings in the output of `fido2-token -I`.

**Comment by inmmi** [comment]
> The `credProtect` string is absent from the list of extension strings in the output of `fido2-token -I`.

Got it ! Thank you very much for your help !
Regards,
