### ISSUE TITLE
GPG signature fails on Windows

### ISSUE THREAD

**Issue by borrrden** [Yubico/libfido2#37]
I've been following along and have tried to build on Windows again but I get the message that GPG verification fails 

> gpg: Can't check signature: No public key

Which public key do I need to install?  This should probably be added to the README.

**Comment by martelletto** [comment]
Hi, the public key is the one used by the LibreSSL team to sign their releases, and can be found on the same directory as the Windows build script. As far as I can see, it is copied by the build script to the build directory prior to verification, so it is strange that it doesn't work for you. Do you get any other output from GPG?

**Comment by borrrden** [comment]
a few other things but none of them seemed to be of consequence. I tried running the command directly. What I noticed is that if I install them into my default key ring and mark them as trusted that it says good signature but the entries in the key ring are all marked as “unknown trust”

**Comment by martelletto** [comment]
Strange. One would expect ` gpg --no-default-keyring --keyring ./libressl.gpg` to ignore the default keyring and use the supplied one instead. Two things we could check are:

- Local GPG configuration/settings;
- GPG version.

On my machine:

```
gpg (GnuPG) 2.2.11
libgcrypt 1.8.4
```

**Comment by borrrden** [comment]
To be clear I was doing my own command line testing with and without the no default key ring setting. I’ll get back with some more info tomorrow.

**Comment by borrrden** [comment]
Ok so the only thing I did before trying is install gpg4win-vanilla from chocolatey.  This results in gpg.exe being installed and added to the path so that it shows up at C:\Program Files (x86)\GNU\GnuPG\pub\gpg.exe.

Version info
> gpg (GnuPG) 2.0.30 (Gpg4win 2.3.4)
> libgcrypt 1.7.8

I'll try getting a newer version from outside of chocolatey

**Comment by borrrden** [comment]
Actually the actual newest version is under a different package name on chocolatey.  Installing that one works, but gpg4win-vanilla is an older version that does not.  It seems like the newer version treats this situation like a warning rather than an error because I am getting the following output

```
gpg: Signature made 04/22/19 11:13:41 Tokyo Standard Time
gpg:                using RSA key 1FFAA0B24B708F96
gpg: using subkey 1FFAA0B24B708F96 instead of primary key 663AF51BD5E4D8D5
gpg: using pgp trust model
gpg: Good signature from "Brent Cook <busterb@gmail.com>" [unknown]
gpg:                 aka "Brent Cook <bcook@rapid7.com>" [unknown]
gpg:                 aka "Brent Cook <bcook@openbsd.org>" [unknown]
gpg:                 aka "keybase.io/busterb <busterb@keybase.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: A1EB 079B 8D3E B92B 4EBD  3139 663A F51B D5E4 D8D5
     Subkey fingerprint: 6F67 522E C596 C025 B245  4991 1FFA A0B2 4B70 8F96
gpg: binary signature, digest algorithm SHA1, key algorithm rsa4096
```

I will close this ticket since there doesn't seem to be an actual issue here.  I'll be looking over the 1.1 release for anything I need to add to my C# binding project so if there is anything in particular API or sample wise please let me know!
