### ISSUE TITLE
Weird behavior with BioPass Feitan

### ISSUE THREAD

**Issue by Silvercast** [Yubico/libfido2#38]
We are testing against [BioPass Feitan](https://www.ftsafe.com/onlinestores/product?id=3) which has a fingerprint scanner.  We're actually confused by user verification bit.
If we disable user verification bit in make credentials or verify attestation the key works as a button, i.e. any unregistered fingers can be used as long as the button is pushed.
If we turn on user verification bit it either crashes or returns error 43 FIDO_ERR_UNSUPPORTED_OPTION or error 35 FIDO_ERR_PIN_NOT_SET.

Also how do libfido2 knows a device works with user verification or not, without trying and getting error code?

**Comment by martelletto** [comment]
Hi Silvercast,

On 03/06/2019 13:46, Silvercast wrote:
> We are testing against [BioPass Feitan](https://www.ftsafe.com/onlinestores/product?id=3) which has a fingerprint scanner.  We're actually confused by user verification bit.
> If we disable user verification bit in make credentials or verify attestation the key works as a button, i.e. any unregistered fingers can be used as long as the button is pushed.

It would appear the key is waiting for touch, as per step 8 in section
5.1 of the CTAP spec [1].

> If we turn on user verification bit it either crashes or returns error 43 FIDO_ERR_UNSUPPORTED_OPTION or error 35 FIDO_ERR_PIN_NOT_SET.

What crashes, and how? Whether you get FIDO_ERR_UNSUPPORTED_OPTION or
FIDO_ERR_PIN_NOT_SET depends on whether a PIN is configured on the
device, I presume? Or do you see both errors at random?

In any case, the output of FIDO_DEBUG=1 would be interesting.

> Also how do libfido2 knows a device works with user verification or not, without trying and getting error code?

There is no such logic in libfido2, to the best of my knowledge. The
only thing libfido2 tries to handle transparently is whether to talk
CTAP1 (U2F) or CTAP2 (FIDO2) to the authenticator. The capabilities of a
CTAP2 authenticator can be retrieved through the
fido_dev_get_cbor_info() function. If the authenticator supports user
verification, the "uv" option in the returned data structure should be
set to true.

-p.

[1]
https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#authenticatorMakeCredential

**Comment by Silvercast** [comment]
The crash was because of our upper code. 
For those who may wander here, use `fido_dev_get_cbor_info` and `fido_cbor_info_options` to detect device capabilities (up, uv, rk etc.)
