### ISSUE TITLE
libfido2 won't recognize Kensington VeriMark Guard USB-C Fingerprint Key

### ISSUE THREAD

**Issue by arash-acceptto** [Yubico/libfido2#381]
**What version of libfido2 are you using?**
Tested on `v1.8` and `v1.7`

**What operating system are you running?**
Tested on `Windows 10` and `macOS Big Sur`

**What application are you using in conjunction with libfido2?**
Tried using `fido2-token -L` to check for device detection.
 
**How does the problem manifest itself?**
Basically anything that calls into the `fido_dev_info_manifest(...)` won't recognize the key.
We're using a [Kensington VeriMark Guard USB-C Fingerprint Key](https://www.kensington.com/p/products/data-protection/biometric/verimark-guard-usb-c-fingerprint-key-fido2-webauthnctap2-fido-u2f-cross-platform/)

**Is the problem reproducible?**
Yes.

**What are the steps that lead to the problem?**
Run `fido2-token -L`

**Does the problem happen with different authenticators?**
No, we've been using libfido2 with YubiKeys and Feitan authenticators with not issues.

This issue only happens with the [Kensington VeriMark Guard USB-C Fingerprint Key](https://www.kensington.com/p/products/data-protection/biometric/verimark-guard-usb-c-fingerprint-key-fido2-webauthnctap2-fido-u2f-cross-platform/)

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L

</pre>
</details>

It's always empty with the Kensington VeriMark authenticator.

**Please include the output of `fido2-token -I`.**

<details>
<summary><code>fido2-token -I</code></summary>
<br>
<pre>
$ fido2-token -I &lt;device&gt;

</pre>
</details>

`fido2-token -L` is always empty with the Kensington VeriMark authenticator, so there's no device to use with the `-I` here.

**Please include the output of `FIDO_DEBUG=1`.**

<details>
<summary><code>FIDO_DEBUG=1</code></summary>
<br>
<pre>
$ export FIDO_DEBUG=1
$ &lt;command1&gt;
$ &lt;command2&gt;
(...)
$ &lt;commandn&gt;

</pre>
</details>

Same results as before, no additional information is available in the output.

-----------

We didn't step into the functions in the `*hid_*.c` to determine why/where it fails, please let me know if I can provide more information.

Thanks,

**Comment by martelletto** [comment]
Fixed in e093ccf04. Thank you for the report and support!
