### ISSUE TITLE
Question concerning fido2 on Windows 10 1909

### ISSUE THREAD

**Issue by jh250535** [Yubico/libfido2#382]
In the new version of Windows 10 1909, Administrator rights are required to be able to see the Yubico device using the fido2.dll.  However, it appears like Yubico has updated fido2.dll to support the new webauthn functionality, which should access a Yubico device without having to run as Administrator.  However, I was not able to obtain a recent build of fido2.dll which includes this new functionality.  Where can I find the updated fido2.dll?  My goals is to access the Yubico device from Windows 10 1909 without having to run as Administrator.  If my approach is wrong, please advise me on how to achieve my goal.  Thank you.  
My email is john.hamilton@ncr.com
Also, I am using the 1.8.0. fido2.dll.

**Comment by martelletto** [comment]
Hi, a few questions:

- Are you using fido2.dll from https://developers.yubico.com/libfido2/Releases/libfido2-1.8.0-win64.zip or did you build it yourself?
- What are you observing?
- Does FIDO_DEBUG provide any output?

Thank you,

-p.

**Comment by jh250535** [comment]
- Yes, I am using fido2.dll from https://developers.yubico.com/libfido2/Releases/libfido2-1.8.0-win64.zip
- I am observing that when I use fido2.dll, my Yubico device can only be accessed when my app is running as Administrator.  This is when running on Windows 10 1909 and later.
- I don't know how to use the FIDO_DEBUG setting.

**Comment by jh250535** [comment]
Ok, here is the output:

PS C:\Users\JH250535\Downloads\libfido2-1.8.0-win64\libfido2-1.8.0-win64\Win64\Release\v142\dynamic> ./fido2-token -L
winhello_manifest: api version 1
fido_winhello_manifest: not present
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col03#8&74c713f&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#intc816&col01#3&36a7043c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#intc816&col02#3&36a7043c&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col01#7&22d20b00&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col02#7&22d20b00&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col03#7&22d20b00&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col01#8&74c713f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_00#8&1d926054&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_00#8&32b3146e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#converteddevice&col02#5&379854aa&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#converteddevice&col03#5&379854aa&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_1050&pid_0120#6&113ad1e7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: CreateFileA
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col02#8&74c713f&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col01#5&166197cb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_02&col01#8&29a611d1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col02#5&166197cb&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_02&col02#8&29a611d1&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col03#5&166197cb&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#syna2393&col04#5&166197cb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_01#8&5ced40f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col04#8&74c713f&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#converteddevice&col01#5&379854aa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: hid_ok
PS C:\Users\JH250535\Downloads\libfido2-1.8.0-win64\libfido2-1.8.0-win64\Win64\Release\v142\dynamic>

**Comment by martelletto** [comment]
Thank you. It looks like [WebAuthNIsUserVerifyingPlatformAuthenticatorAvailable()](https://github.com/microsoft/webauthn/blob/master/webauthn.h#L761) is returning false. Does Windows Hello have a PIN or fingerprint configured on your machine?

**Comment by jh250535** [comment]
No, Windows Hello is not configured on my machine.  I am using a USB Yubico device.

**Comment by martelletto** [comment]
Understood; could you try to configure a PIN or fingerprint in Windows Hello and see if you are able to observe the USB device?

**Comment by jh250535** [comment]
Due to my company's policies, Windows Hello Face, Fingerprint, and PIN are all unavailable for sign-in.  But didn't the token show up when I ran "./fido2-token -L"?  Does this mean it will be recognized by fido2-cred.exe and fido2-assert.exe?

**Comment by martelletto** [comment]
No, unfortunately it won't work. Your USB device was not detected by libfido2, because there is no way for libfido2  to detect it; detection and communication are both handled internally by Windows Hello. All libfido2 can do is to check whether Windows Hello itself is ready to go. In your case, it isn't, and libfido2 skips Windows Hello altogether. Perhaps libfido2 is trying to do too much and the call to WebAuthNIsUserVerifyingPlatformAuthenticatorAvailable() should be skipped. Could you try to comment it out? I could upload test binaries if that works better.

**Comment by jh250535** [comment]
I don't know how to rebuild the libfido2.  If you could upload test binaries that would be great.

**Comment by martelletto** [comment]
I've shared a zip file with you in Google Drive. Did it make it through?

**Comment by jh250535** [comment]
My account john.hamilton@ncr.com is not registered with Google, and I received no email.  How do I access the shared zip file?

**Comment by martelletto** [comment]
That's a good question. I tried e-mailing it to you but Google blocked it, since it contains executables and shared libraries. Can you get it from https://ambientworks.net/tmp/libfido2-1.8.0-patched-win64.zip, sha256 229676df8c30c378c5625ef1cd4755106304570c0ba189cd4d00705ad9a5b300?

**Comment by jh250535** [comment]
Ok, I got it.  Here is the new output from "./fido2-token -L"

PS C:\Users\JH250535\Downloads\libfido2-1.8.0-patched-win64\libfido2-1.8.0-patched-win64\Win64\Release\v142\dynamic> ./fido2-token -L
winhello_manifest: api version 1
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col03#8&74c713f&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#intc816&col01#3&36a7043c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#intc816&col02#3&36a7043c&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col01#7&22d20b00&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col02#7&22d20b00&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_047f&pid_c056&mi_03&col03#7&22d20b00&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col01#8&74c713f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_00#8&1d926054&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_00#8&32b3146e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#converteddevice&col02#5&379854aa&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#converteddevice&col03#5&379854aa&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_1050&pid_0120#6&113ad1e7&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: CreateFileA
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col02#8&74c713f&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col01#5&166197cb&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_02&col01#8&29a611d1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col02#5&166197cb&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_02&col02#8&29a611d1&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#syna2393&col03#5&166197cb&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#syna2393&col04#5&166197cb&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: hid_ok
copy_info: path=\\?\hid#vid_04d9&pid_fa58&mi_01#8&5ced40f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: is_fido
copy_info: path=\\?\hid#vid_258a&pid_0013&mi_01&col04#8&74c713f&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}
copy_info: is_fido
copy_info: path=\\?\hid#converteddevice&col01#5&379854aa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd
copy_info: hid_ok
windows://hello: vendor=0x045e, product=0x0001 (Microsoft Corporation Windows Hello)
PS C:\Users\JH250535\Downloads\libfido2-1.8.0-patched-win64\libfido2-1.8.0-patched-win64\Win64\Release\v142\dynamic>

**Comment by martelletto** [comment]
Thank you. You should now be able to talk to the USB device by directing libfido2 toward the pseudo-device with path windows://hello.

**Comment by jh250535** [comment]
Yes, it is working now.  I would like to say Thank You so much for your quick responses and your help.

**Comment by martelletto** [comment]
No problem; happy I was able to help. Thank you once again for your help debugging the problem!
