### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by elukewalker** [Yubico/libfido2#4]
Feature Request: Update the cred and assert examples to give the user the option to specify a relying party and user.

**Comment by martelletto** [comment]
Hi Luke,

The feature you are requesting is implemented by fido2-cred and fido2-assert, command-line tools that are shipped with libfido2. Documentation is currently only available in the form of man pages; assuming you have libfido2 checked out on the current working directory, you can use man man/fido2-cred.1 on Linux and macOS to access the documentation from the command line. The cred and assert examples are not meant for general use, but as reference implementations.

-p.
