### ISSUE TITLE
libfido2 does not build on FreeBSD after 53b014150190

### ISSUE THREAD

**Issue by emaste** [Yubico/libfido2#40]
In 53b014150190 hidapi was replaced with bespoke `hid_{linux,osx,win}.c` implementations, and after that commit does not build on FreeBSD.

I am trying to determine the best path forward - possibilities:
- Use hid_linux.c and https://github.com/FreeBSDDesktop/libudev-devd 
- Restore old hidapi use for FreeBSD (add wrappers back in a new hid_hidapi.c)
- (Re)implement the subset of hidapi functionality needed by libfido2
- Implement something based on libusbhid

**Comment by martelletto** [comment]
On 08/06/2019 17:47, Ed Maste wrote:
> In 53b014150190 hidapi was replaced with bespoke `hid_{linux,osx,win}.c` implementations, and after that commit does not build on FreeBSD.
> 
> I am trying to determine the best path forward - possibilities:
> - Use hid_linux.c and https://github.com/FreeBSDDesktop/libudev-devd 
> - Restore old hidapi use for FreeBSD (add wrappers back in a new hid_hidapi.c)
> - (Re)implement the subset of hidapi functionality needed by libfido2
> - Implement something based on libusbhid

Apologies for the unintended breakage. I am tempted to say that the best
course of action is to implement something based on libusbhid, since it
seems to be part of FreeBSD base.

From a quick look at libusbhid, I see that the I/O primitives are there,
but it does not seem to provide an abstraction to discover USB devices.
Fortunately, libusb also seems to be part of FreeBSD base, and it does
appear to provide a function to that end, libusb_get_device_list().

A hid_bsd.c combining libusb + libusbhid could work, and would not have
external dependencies. Does that make sense?

-p.

**Comment by emaste** [comment]
Apology unnecessary - we had some local patches in the FreeBSD ports tree to get it to build that never went upstream, so you might not have known it built on FreeBSD at all.

I haven't done much USB development before so didn't have good intuition about the best approach; if libusb + libusbhid indeed provide what's needed that seems reasonable, I'll start down that path.

**Comment by emaste** [comment]
For reference the FreeBSD build hacks are in https://github.com/freebsd/freebsd-ports/blob/master/security/libfido2/Makefile

**Comment by martelletto** [comment]
On 08/06/2019 18:25, Ed Maste wrote:
> For reference the FreeBSD build hacks are in https://github.com/freebsd/freebsd-ports/blob/master/security/libfido2/Makefile

Thanks, I wasn't aware of them. In hindsight, I probably should have
realized.

-p.

**Comment by emaste** [comment]
Maybe I can talk @myfreeweb into taking a look at it.

**Comment by myfreeweb** [comment]
well, I'm a bit busy right now so I can't just implement it yet, but:

> Use hid_linux.c and https://github.com/FreeBSDDesktop/libudev-devd

Could be an interesting challenge for improving libudev-devd further I guess. The rest of the Linux file (`get_report_descriptor`) would have to be rewritten though, since our uhid interface uses different structs than Linux hidraw.

> libusb + libusbhid

Using a library that provides a whole different way of accessing devices just to enumerate doesn't sound that good.

For authenticator-rs (ex u2f-hid-rs) I just did `ls /dev | grep uhid` basically:

https://github.com/mozilla/authenticator-rs/blob/674fd0b46bd1659973bbf8db5e7a4e819a38b9cb/src/freebsd/monitor.rs#L64-L73

I guess enumerating via `/dev` + libusbhid would be the easier solution.

> the FreeBSD build hacks

Doesn't look like much, just the man directory, endian.h path and not linking libcrypto for some reason.

**Comment by martelletto** [comment]
On 09/06/2019 12:49, myfreeweb wrote:
> I guess enumerating via `/dev` + libusbhid would be the easier solution.

Sounds good to me.

-p.

**Comment by emaste** [comment]
>> libusb + libusbhid
>
> Using a library that provides a whole different way of accessing devices just to enumerate doesn't sound that good.

Indeed, I did not realize that they're completely separate including the kernel interface used.

> I guess enumerating via `/dev` + libusbhid would be the easier solution.

Yeah, I ended up trying enumeration via something like:
```
static int
selectfile(const struct dirent *dp)
{
        if (strncmp(dp->d_name, "uhid", 4) == 0)
                return (1);

        return (0);
}

int
fido_dev_info_manifest(fido_dev_info_t *devlist, size_t ilen, size_t *olen)
{
...
        nitems = scandir("/dev", &de, selectfile, alphasort);
        if (nitems < 0)
                return (FIDO_ERR_INVALID_ARGUMENT);
...
```

The issue I ran into then is that libusbhid doesn't provide access to the vendor/device ID etc.

**Comment by myfreeweb** [comment]
> libusbhid doesn't provide access to the vendor/device ID etc

huh, that's surprising. well.. then it's sysctl time I guess.

For input devices in libudev-devd, I've had to add new sysctls for the kernel. For USB, we have this already:

```
dev.uhid.0.%pnpinfo: vendor=0x1050 product=0x0407 devclass=0x00 devsubclass=0x00 devproto=0x00 sernum="" release=0x0435 mode=host intclass=0x03 intsubclass=0x00 intprotocol=0x00
dev.uhid.0.%location: bus=0 hubaddr=1 port=21 devaddr=5 interface=1 ugen=ugen0.5
```

**Comment by emaste** [comment]
The next issue I ran into is read not returning expected data:
```
% build/tools/fido2-cred -M -d -i cred_param /dev/uhid1
...
tx: d=0x800a22000, cmd=0x86, buf=0x800a22000, count=8
  be a3 97 b0 46 7a 8b 27 
rx: initiation frame at 0x7fffffffdcd8, len 64
  00 ff ff ff bf 00 01 03 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
rx: cid (0xffffff00, 0xffffffff), cmd (0xbf, 0x86)
fido_dev_open_rx: rx
fido2-cred: fido_dev_open /dev/uhid1: FIDO_ERR_RX
```

Some more digging lead me to this: https://github.com/mozilla/authenticator-rs/blob/master/src/freebsd/device.rs#L65

and with a similar change in my `write()` to drop the first byte if 0 `fido2-cred` now behaves identically as observed on Linux, failing with "invalid cbor."

```
...
decode_cred_authdata: buf=0x800a3c000, len=202
decode_attcred: buf=0x800a3c025, len=165
decode_attcred: attcred->id.len=70
ctap_check_cbor: invalid cbor
cbor_map_iter: ctap_check_cbor
parse_cbor_reply: cbor_map_iter
fido_dev_make_cred_rx: parse_makecred_reply
fido2-cred: fido_dev_make_cred: FIDO_ERR_RX_INVALID_CBOR
```

(Note, I'm testing with a SoloKeys Solo here, so maybe there's something it doesn't implement etc.? The key does work with Firefox.)

**Comment by martelletto** [comment]
On 09/06/2019 15:12, Ed Maste wrote:
> decode_cred_authdata: buf=0x800a3c000, len=202
> decode_attcred: buf=0x800a3c025, len=165
> decode_attcred: attcred->id.len=70
> ctap_check_cbor: invalid cbor
> cbor_map_iter: ctap_check_cbor
> parse_cbor_reply: cbor_map_iter
> fido_dev_make_cred_rx: parse_makecred_reply
> fido2-cred: fido_dev_make_cred: FIDO_ERR_RX_INVALID_CBOR

Interesting. Could you share the CBOR payload that triggered the problem?

CTAP2 authenticators are expected to follow the CTAP2 canonical CBOR
encoding form [1]. This is being checked by ctap_check_cbor(). The bug
could be in the function (hopefully!), or in the authenticator.

-p.

[1]
https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#ctap2-canonical-cbor-encoding-form

**Comment by emaste** [comment]
Full output from `fido2-cred -M -d -i cred_param` here: https://termbin.com/7nqj

cbor.me turned the payload into:
```
{2: h'AEB0388497C8C3D375C157EE720698AC7878BE870AD8F1AA99372FAC5DB45B54410000011F8876631BD4A0427F57730EC71C9E02790046642EA4893F7A1F03E221018A74E2B1D529E149CF8B5D5952E4C08926A7E6686982F7AEB0388497C8C3D375C157EE720698AC7878BE870AD8F1AA99372FAC5DB45B541F010000A50102032620012158206302586BCBD29138410FE8C7ECFC16D925B18B6CE48A9C2844435535288CD048225820B3D5626D841B5A173B3F9FF258EB915F7C56B2E96EAEA5824A68B5E85D756C2A', 3: {"alg": -7, "sig": h'3045022070E183FEF35FB89F1989BC0E65294472124B99B7D22B9C8A9B91AAED2E71E057022100FD355644FA7E2FE01735984778BA68BAD26CB2F48E30DE0AF6E54DE0FF7922B1', "x5c": [h'308202E130820288A003020102020101300A06082A8648CE3D040302308180310B30090603550406130255533111300F06035504080C084D6172796C616E6431123010060355040A0C09536F6C6F204B6579733110300E060355040B0C07526F6F742043413115301306035504030C0C736F6C6F6B6579732E636F6D3121301F06092A864886F70D010901161268656C6C6F40736F6C6F6B6579732E636F6D3020170D3138313131313132353230305A180F32303638313032393132353230305A308192310B30090603550406130255533111300F06035504080C084D6172796C616E6431123010060355040A0C09536F6C6F204B65797331223020060355040B0C1941757468656E74696361746F72204174746573746174696F6E3115301306035504030C0C736F6C6F6B6579732E636F6D3121301F06092A864886F70D010901161268656C6C6F40736F6C6F6B6579732E636F6D3059301306072A8648CE3D020106082A8648CE3D0301070342000422FE0FB52A78BEC645371A28A7574349A46F854DCA4E251C9F75303DBF10D5D2D20BB9692CDDB25C14D8398512F623EE91BAC6ACFF4A1A27EFE0C1543FD4D9C5A381DC3081D9301D0603551D0E041604143BE6D2C06FF2E7B07C9D9E28C020B00D07C815C830819F0603551D23048197308194A18186A48183308180310B30090603550406130255533111300F06035504080C084D6172796C616E6431123010060355040A0C09536F6C6F204B6579733110300E060355040B0C07526F6F742043413115301306035504030C0C736F6C6F6B6579732E636F6D3121301F06092A864886F70D010901161268656C6C6F40736F6C6F6B6579732E636F6D820900C44763928FF4BE8C30090603551D1304023000300B0603551D0F0404030204F0300A06082A8648CE3D040302034700304402207110462CF516189755CA64503B69B2DF1771ABAD8EC0D6A6073D668A3BBBFE6102201E82EFEB5E4E3A008464D2F884C378359363812EBEA612326E2990C8914B7152']}, 1: "packed"}
```

**Comment by emaste** [comment]
So non-canonical key ordering, with issue here: https://github.com/solokeys/solo/issues/170

**Comment by martelletto** [comment]
On 09/06/2019 15:59, Ed Maste wrote:
> So non-canonical key ordering, with issue here: https://github.com/solokeys/solo/issues/170

Indeed. Nice catch. If you comment out the call to ctap_check_cbor() in
cbor_map_iter(), it should work.

-p.

**Comment by emaste** [comment]
Thanks for all of your help!

> Indeed. Nice catch. If you comment out the call to ctap_check_cbor() in
> cbor_map_iter(), it should work.

Yes, the example in fido2-cred's man page worked. Aside, I was very happy to see that there's a regression test as a build step (it started failing after my hack).

I'll submit a pull request with my libusbhid support after getting it cleaned up and sorting out the device/vendor ID (right now I just have it return bogus static data).

**Comment by martelletto** [comment]
Hi, please let me know if there is anything else I can do to help. Looking forward to installing FreeBSD at work, even if just to test libfido2. :)

-p.

**Comment by grembo** [comment]
> Thanks for all of your help!
> 
> > Indeed. Nice catch. If you comment out the call to ctap_check_cbor() in
> > cbor_map_iter(), it should work.
> 
> Yes, the example in fido2-cred's man page worked. Aside, I was very happy to see that there's a regression test as a build step (it started failing after my hack).
> 
> I'll submit a pull request with my libusbhid support after getting it cleaned up and sorting out the device/vendor ID (right now I just have it return bogus static data).

Did you ever manage to get there? (I just stumbled over this while looking at security/py-yubikey-manager, which also lacks fido2 support on FreeBSD [py-fido2 in this case, so kind of unrelated]).

**Comment by martelletto** [comment]
FYI, a hidapi backend was contributed by Google in #91, which should make libfido2 build on FreeBSD again. It can be enabled by passing -DUSE_HIDAPI=1 to cmake.

**Comment by martelletto** [comment]
I have confirmed that the hidapi backend works on FreeBSD 12.1-RELEASE. I have also pushed a few bits and pieces to make it easier to build libfido2 on FreeBSD. With c58efaa230 and the dependencies in place, cmake -DUSE_HIDAPI=1 should do the trick.

**Comment by emaste** [comment]
Thanks!
