### ISSUE TITLE
attestation format

### ISSUE THREAD

**Issue by shimritd** [Yubico/libfido2#41]
Hi,

in parse_cbor_reply when parsing the attestation statement, the first thing that the package is looking for is a NULL byte.
if (blob[0] != FIDO_OK) {
		log_debug("%s: blob[0]=0x%02x", __func__, blob[0]);
		r = blob[0];
		goto fail;
}
and then the parsing itself starts from blob+1.
Is there a reason for that? 
Thanks a lot!!

**Comment by martelletto** [comment]
On 17/06/2019 08:52, shimritd wrote:
> Hi,
> 
> in parse_cbor_reply when parsing the attestation statement, the first thing that the package is looking for is a NULL byte.
> if (blob[0] != FIDO_OK) {
> 		log_debug("%s: blob[0]=0x%02x", __func__, blob[0]);
> 		r = blob[0];
> 		goto fail;
> }
> and then the parsing itself starts from blob+1.
> Is there a reason for that? 
> Thanks a lot!!
> 
> 

Hi,

The function that parses attestation statements is decode_attstmt() [1].
parse_cbor_reply() [2] parses command responses from the authenticator,
which are prefixed with a 1-byte status code [3]. Status = 0 (FIDO_OK)
means success, and all other values are errors.

Please feel free to contact me directly should you have further questions.

-p.

[1] https://github.com/Yubico/libfido2/blob/867d3a/src/cbor.c#L1328
[2] https://github.com/Yubico/libfido2/blob/867d3a/src/cbor.c#L122
[3]
https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#responses
