### ISSUE TITLE
cred id

### ISSUE THREAD

**Issue by shimritd** [Yubico/libfido2#42]
Hi,

I have a question on the credential id length.

On registration,  when I get the values form cred->attcred.id.ptr and cred->attcred.id.len, I get a byte array of length 64.
On authentication, when I get the value from assert->stmt[idx]->id.ptr and assert->stmt[idx]->id.len, I get a byte array of length 16.

Shouldn't that be the same value which is the credential Id?

Thanks!

**Comment by martelletto** [comment]
Hi,

The WebAuthn specification states [1]:

>  Credential IDs are generated by authenticators in two forms:
> 
> 1. At least 16 bytes that include at least 100 bits of entropy, or
> 
> 2. The public key credential source, without its Credential ID, encrypted so only its managing authenticator can decrypt it. This form allows the authenticator to be nearly stateless, by having the Relying Party store any necessary state.

What this means is that, typically, you will see credential IDs of 64 bytes for non-resident (wrapped) ES256 credentials, and 16 bytes for resident ES256 credentials. Both length and value should be consistent between "make credential" and "get assertion" operations.

Could there be a confusion between resident/non-resident credentials in your case?

-p.

[1] https://www.w3.org/TR/webauthn/#credential-id

**Comment by shimritd** [comment]
So I’m a little bit confused here, I’ll be happy to your thought here…

On registration, I’m calling fido_cred_set_options with rk=false.
On authentication, I’m getting the allow credential list from the server and I’m calling fido_assert_allow_cred for each cred_id in the list.
So how come after calling fido_dev_get_assert, I get 16 bytes in assert->stmt[idx]->id?

**Comment by martelletto** [comment]
It sounds like you are doing everything right. I recommend having a look at the output of both "make credential" and "get assertion" with FIDO_DEBUG=1.

**Comment by shimritd** [comment]
Here it is.
Thanks!

Make credential:
tx: d=0000029CFD4C5250, cmd=0x86, buf=0000029CFD4C5250, count=8
  4e bd 18 6d e7 67 61 de
rx: initiation frame at 000000D85934C8C0, len 64
  ff ff ff ff 86 00 11 4e bd 18 6d e7 67 61 de 00
  0e 00 08 02 05 01 02 05 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
tx: d=0000029CFD4C5250, cmd=0x90, buf=000000D85934CAB4, count=1
  07
rx: initiation frame at 000000D85934BDA0, len 64
  00 0e 00 08 90 00 01 30 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
tx: d=0000029CFD4C5250, cmd=0x90, buf=0000029CFB861AB0, count=170
  01 a5 01 58 20 41 f8 dd ae be d0 18 15 b2 4e 8b
  20 73 8c 30 cc 90 96 5b bc 4b 7d c4 90 8e f3 34
  72 d0 55 60 88 02 a2 62 69 64 69 6c 6f 63 61 6c
  68 6f 73 74 64 6e 61 6d 65 69 6c 6f 63 61 6c 68
  6f 73 74 03 a3 62 69 64 54 5a 6a 49 33 4d 47 5a
  6c 59 7a 67 74 5a 6d 59 33 4d 53 30 30 64 6e 61
  6d 65 6c 45 6c 61 64 20 41 76 72 61 68 61 6d 6b
  64 69 73 70 6c 61 79 4e 61 6d 65 65 65 6c 61 64
  61 04 81 a2 63 61 6c 67 39 00 06 64 74 79 70 65
  6a 70 75 62 6c 69 63 2d 6b 65 79 06 a1 6b 68 6d
  61 63 2d 73 65 63 72 65 74 f5
rx: initiation frame at 000000D85934BCF0, len 64
  00 0e 00 08 90 03 fb 00 a3 01 66 70 61 63 6b 65
  64 02 58 d2 49 96 0d e5 88 0e 8c 68 74 34 17 0f
  64 76 60 5b 8f e4 ae b9 a2 86 32 c7 99 5c f3 ba
  83 1d 97 63 c1 00 00 00 c1 cb 69 48 1e 8f f7 40
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 00 39 93 ec 0a 27 29 a1 54 a8 00 40
  00 eb 0d 68 d8 b1 fa a9 e3 11 d2 08 f8 d6 bd c4
  ec 86 30 56 be b5 f5 96 89 b8 f9 22 f7 ab ea 38
  a0 ea 50 1e 73 1f c1 b0 8f e1 e0 1a d0 48 56 12
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 01 da 29 34 11 64 1d 8b c3 89 7d 5b
  ed f7 09 e7 1f a5 01 02 03 26 20 01 21 58 20 bb
  b6 98 68 6d 65 9c dc d8 47 bf a5 5f 81 35 ea 76
  22 4c 8e 22 f0 6f 07 60 d9 07 8a 1f 5c b5 5d 22
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 02 58 20 d2 10 51 e2 03 a7 fc 01 89
  ed 32 56 07 32 30 0e fa 41 5b ae 70 e8 01 91 7b
  ec 5d 90 cf 26 f0 9a a1 6b 68 6d 61 63 2d 73 65
  63 72 65 74 f5 03 a3 63 61 6c 67 26 63 73 69 67
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 03 58 46 30 44 02 20 13 96 f9 91 fb
  75 2c 56 d2 f8 95 60 b8 bc b8 37 70 90 30 0a 00
  f2 f1 b9 01 25 cf 0f e8 38 6e 83 02 20 6c 7b 47
  f0 68 e4 65 9e a0 e0 9c f5 6e 6f bb 58 77 b4 2e
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 04 fc 70 05 00 d3 5b 21 99 b6 f1 55
  7b ef 63 78 35 63 81 59 02 c1 30 82 02 bd 30 82
  01 a5 a0 03 02 01 02 02 04 18 ac 46 c0 30 0d 06
  09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 2e 31 2c
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 05 30 2a 06 03 55 04 03 13 23 59 75
  62 69 63 6f 20 55 32 46 20 52 6f 6f 74 20 43 41
  20 53 65 72 69 61 6c 20 34 35 37 32 30 30 36 33
  31 30 20 17 0d 31 34 30 38 30 31 30 30 30 30 30
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 06 30 5a 18 0f 32 30 35 30 30 39 30
  34 30 30 30 30 30 30 5a 30 6e 31 0b 30 09 06 03
  55 04 06 13 02 53 45 31 12 30 10 06 03 55 04 0a
  0c 09 59 75 62 69 63 6f 20 41 42 31 22 30 20 06
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 07 03 55 04 0b 0c 19 41 75 74 68 65
  6e 74 69 63 61 74 6f 72 20 41 74 74 65 73 74 61
  74 69 6f 6e 31 27 30 25 06 03 55 04 03 0c 1e 59
  75 62 69 63 6f 20 55 32 46 20 45 45 20 53 65 72
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 08 69 61 6c 20 34 31 33 39 34 33 34
  38 38 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06
  08 2a 86 48 ce 3d 03 01 07 03 42 00 04 79 ea 3b
  2c 7c 49 70 10 62 23 0c d2 3f eb 60 e5 29 31 71
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 09 d4 83 f1 00 be 85 9d 6b 0f 83 97
  03 01 b5 46 cd d4 6e cf ca e3 e3 f3 0f 81 e9 ed
  62 bd 26 8d 4c 1e bd 37 b3 bc be 92 a8 c2 ae eb
  4e 3a a3 6c 30 6a 30 22 06 09 2b 06 01 04 01 82
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0a c4 0a 02 04 15 31 2e 33 2e 36 2e
  31 2e 34 2e 31 2e 34 31 34 38 32 2e 31 2e 37 30
  13 06 0b 2b 06 01 04 01 82 e5 1c 02 01 01 04 04
  03 02 05 20 30 21 06 0b 2b 06 01 04 01 82 e5 1c
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0b 01 01 04 04 12 04 10 cb 69 48 1e
  8f f7 40 39 93 ec 0a 27 29 a1 54 a8 30 0c 06 03
  55 1d 13 01 01 ff 04 02 30 00 30 0d 06 09 2a 86
  48 86 f7 0d 01 01 0b 05 00 03 82 01 01 00 97 9d
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0c 03 97 d8 60 f8 2e e1 5d 31 1c 79
  6e ba fb 22 fa a7 e0 84 d9 ba b4 c6 1b bb 57 f3
  e6 b4 c1 8a 48 37 b8 5c 3c 4e db e4 83 43 f4 d6
  a5 d9 b1 ce da 8a e1 fe d4 91 29 21 73 05 8e 5e
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0d e1 cb dd 6b da c0 75 57 c6 a0 e8
  d3 68 25 ba 15 9e 7f b5 ad 8c da f8 04 86 8c f9
  0e 8f 1f 8a ea 17 c0 16 b5 5c 2a 7a d4 97 c8 94
  fb 71 d7 53 d7 9b 9a 48 4b 6c 37 6d 72 3b 99 8d
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0e 2e 1d 43 06 bf 10 33 b5 ae f8 cc
  a5 cb b2 56 8b 69 24 22 6d 22 a3 58 ab 7d 87 e4
  ac 5f 2e 09 1a a7 15 79 f3 a5 69 09 49 7d 72 f5
  4e 06 ba c1 c3 b4 41 3b ba 5e af 94 c3 b6 4f 34
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 0f f9 eb a4 1a cb 6a e2 83 77 6d 36
  46 53 78 48 fe e8 84 bd dd f5 b1 ba 57 98 54 cf
  fd ce ba c3 44 05 95 27 e5 6d d5 98 f8 f5 66 71
  5a be 43 01 dd 19 11 30 e6 b9 f0 c6 40 39 12 53
rx: continuation frame at 000000D85934BCF0, len 64
  00 0e 00 08 10 e2 29 80 3f 3a ef 27 4b ed bf de
  3f cb bd 42 ea d6 79 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload at 000000D85934BF10, len 1019
  00 a3 01 66 70 61 63 6b 65 64 02 58 d2 49 96 0d
  e5 88 0e 8c 68 74 34 17 0f 64 76 60 5b 8f e4 ae
  b9 a2 86 32 c7 99 5c f3 ba 83 1d 97 63 c1 00 00
  00 c1 cb 69 48 1e 8f f7 40 39 93 ec 0a 27 29 a1
  54 a8 00 40 00 eb 0d 68 d8 b1 fa a9 e3 11 d2 08
  f8 d6 bd c4 ec 86 30 56 be b5 f5 96 89 b8 f9 22
  f7 ab ea 38 a0 ea 50 1e 73 1f c1 b0 8f e1 e0 1a
  d0 48 56 12 da 29 34 11 64 1d 8b c3 89 7d 5b ed
  f7 09 e7 1f a5 01 02 03 26 20 01 21 58 20 bb b6
  98 68 6d 65 9c dc d8 47 bf a5 5f 81 35 ea 76 22
  4c 8e 22 f0 6f 07 60 d9 07 8a 1f 5c b5 5d 22 58
  20 d2 10 51 e2 03 a7 fc 01 89 ed 32 56 07 32 30
  0e fa 41 5b ae 70 e8 01 91 7b ec 5d 90 cf 26 f0
  9a a1 6b 68 6d 61 63 2d 73 65 63 72 65 74 f5 03
  a3 63 61 6c 67 26 63 73 69 67 58 46 30 44 02 20
  13 96 f9 91 fb 75 2c 56 d2 f8 95 60 b8 bc b8 37
  70 90 30 0a 00 f2 f1 b9 01 25 cf 0f e8 38 6e 83
  02 20 6c 7b 47 f0 68 e4 65 9e a0 e0 9c f5 6e 6f
  bb 58 77 b4 2e fc 70 05 00 d3 5b 21 99 b6 f1 55
  7b ef 63 78 35 63 81 59 02 c1 30 82 02 bd 30 82
  01 a5 a0 03 02 01 02 02 04 18 ac 46 c0 30 0d 06
  09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 2e 31 2c
  30 2a 06 03 55 04 03 13 23 59 75 62 69 63 6f 20
  55 32 46 20 52 6f 6f 74 20 43 41 20 53 65 72 69
  61 6c 20 34 35 37 32 30 30 36 33 31 30 20 17 0d
  31 34 30 38 30 31 30 30 30 30 30 30 5a 18 0f 32
  30 35 30 30 39 30 34 30 30 30 30 30 30 5a 30 6e
  31 0b 30 09 06 03 55 04 06 13 02 53 45 31 12 30
  10 06 03 55 04 0a 0c 09 59 75 62 69 63 6f 20 41
  42 31 22 30 20 06 03 55 04 0b 0c 19 41 75 74 68
  65 6e 74 69 63 61 74 6f 72 20 41 74 74 65 73 74
  61 74 69 6f 6e 31 27 30 25 06 03 55 04 03 0c 1e
  59 75 62 69 63 6f 20 55 32 46 20 45 45 20 53 65
  72 69 61 6c 20 34 31 33 39 34 33 34 38 38 30 59
  30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48
  ce 3d 03 01 07 03 42 00 04 79 ea 3b 2c 7c 49 70
  10 62 23 0c d2 3f eb 60 e5 29 31 71 d4 83 f1 00
  be 85 9d 6b 0f 83 97 03 01 b5 46 cd d4 6e cf ca
  e3 e3 f3 0f 81 e9 ed 62 bd 26 8d 4c 1e bd 37 b3
  bc be 92 a8 c2 ae eb 4e 3a a3 6c 30 6a 30 22 06
  09 2b 06 01 04 01 82 c4 0a 02 04 15 31 2e 33 2e
  36 2e 31 2e 34 2e 31 2e 34 31 34 38 32 2e 31 2e
  37 30 13 06 0b 2b 06 01 04 01 82 e5 1c 02 01 01
  04 04 03 02 05 20 30 21 06 0b 2b 06 01 04 01 82
  e5 1c 01 01 04 04 12 04 10 cb 69 48 1e 8f f7 40
  39 93 ec 0a 27 29 a1 54 a8 30 0c 06 03 55 1d 13
  01 01 ff 04 02 30 00 30 0d 06 09 2a 86 48 86 f7
  0d 01 01 0b 05 00 03 82 01 01 00 97 9d 03 97 d8
  60 f8 2e e1 5d 31 1c 79 6e ba fb 22 fa a7 e0 84
  d9 ba b4 c6 1b bb 57 f3 e6 b4 c1 8a 48 37 b8 5c
  3c 4e db e4 83 43 f4 d6 a5 d9 b1 ce da 8a e1 fe
  d4 91 29 21 73 05 8e 5e e1 cb dd 6b da c0 75 57
  c6 a0 e8 d3 68 25 ba 15 9e 7f b5 ad 8c da f8 04
  86 8c f9 0e 8f 1f 8a ea 17 c0 16 b5 5c 2a 7a d4
  97 c8 94 fb 71 d7 53 d7 9b 9a 48 4b 6c 37 6d 72
  3b 99 8d 2e 1d 43 06 bf 10 33 b5 ae f8 cc a5 cb
  b2 56 8b 69 24 22 6d 22 a3 58 ab 7d 87 e4 ac 5f
  2e 09 1a a7 15 79 f3 a5 69 09 49 7d 72 f5 4e 06
  ba c1 c3 b4 41 3b ba 5e af 94 c3 b6 4f 34 f9 eb
  a4 1a cb 6a e2 83 77 6d 36 46 53 78 48 fe e8 84
  bd dd f5 b1 ba 57 98 54 cf fd ce ba c3 44 05 95
  27 e5 6d d5 98 f8 f5 66 71 5a be 43 01 dd 19 11
  30 e6 b9 f0 c6 40 39 12 53 e2 29 80 3f 3a ef 27
  4b ed bf de 3f cb bd 42 ea d6 79
decode_cred_authdata: buf=0000029CFB8BCDA0, len=210
decode_attcred: buf=0000029CFB8BCDC5, len=173
decode_extensions: buf=0000029CFB8BCE64, len=14

Get assertion:
tx: d=0000029CFD4C4560, cmd=0x86, buf=0000029CFD4C4560, count=8
  0e a1 57 6f 85 b0 c0 2a
rx: initiation frame at 000000D85934CB50, len 64
  ff ff ff ff 86 00 11 0e a1 57 6f 85 b0 c0 2a 00
  0e 00 09 02 05 01 02 05 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_dev_authkey_tx: dev=0000029CFD4C4560
tx: d=0000029CFD4C4560, cmd=0x90, buf=0000029CFB8606E0, count=6
  06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0000029CFD4C4560, authkey=0000029CFD4C24D0, ms=-1
rx: initiation frame at 000000D85934BC50, len 64
  00 0e 00 09 90 00 51 00 a1 01 a5 01 02 03 38 18
  20 01 21 58 20 d3 f7 66 ea 4a dd e2 89 8e 5f fd
  6b 6b 0d 41 65 03 be 53 43 f3 6f d7 88 98 04 3d
  d3 65 7d c6 9a 22 58 20 c1 d2 5b 6b b5 1b 60 96
rx: continuation frame at 000000D85934BC50, len 64
  00 0e 00 09 00 d3 15 44 19 9a 49 51 f5 cc c0 84
  df 2d f8 67 09 b3 81 58 9c be 6a de 56 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload at 000000D85934BE70, len 81
  00 a1 01 a5 01 02 03 38 18 20 01 21 58 20 d3 f7
  66 ea 4a dd e2 89 8e 5f fd 6b 6b 0d 41 65 03 be
  53 43 f3 6f d7 88 98 04 3d d3 65 7d c6 9a 22 58
  20 c1 d2 5b 6b b5 1b 60 96 d3 15 44 19 9a 49 51
  f5 cc c0 84 df 2d f8 67 09 b3 81 58 9c be 6a de
  56
tx: d=0000029CFD4C4560, cmd=0x90, buf=0000029CFB8BC410, count=204
  02 a4 01 69 6c 6f 63 61 6c 68 6f 73 74 02 58 20
  8e 3b 99 bd 55 46 7d aa 49 0a db 2d 05 70 1f 5e
  dc d3 e0 8b 73 bf 15 b6 3d 0a 97 72 19 53 4f fe
  04 a1 6b 68 6d 61 63 2d 73 65 63 72 65 74 a3 01
  a5 01 02 03 26 20 01 21 58 20 4e 77 b8 cf 7e 3e
  6b b3 f0 8d 3e 55 d3 8e fd 49 b7 f4 92 38 b4 76
  90 04 a2 6b f4 6b 34 01 18 e7 22 58 20 19 8a 00
  9e 6d 3f b9 b4 5f 56 35 58 96 94 d7 53 05 c1 ff
  5d 16 d6 1b c7 f4 29 b2 25 b3 3a 80 3d 02 58 20
  50 60 30 95 9b 03 a6 9d d7 8d 09 3c b9 c3 a3 7c
  ee 83 7c d5 89 61 a3 96 9b 6f 31 fc 0c 65 60 b0
  03 50 59 84 64 df 7e 83 5d c6 18 04 e0 d1 62 10
  dd 17 05 a2 62 75 70 f5 62 75 76 f4
rx: initiation frame at 000000D85934BE70, len 64
  00 0e 00 09 90 00 e6 00 a5 01 a2 62 69 64 50 c0
  51 a2 2d 28 6e 9e b1 a1 c9 f3 46 2a a8 8b 51 64
  74 79 70 65 6a 70 75 62 6c 69 63 2d 6b 65 79 02
  58 54 49 96 0d e5 88 0e 8c 68 74 34 17 0f 64 76
rx: continuation frame at 000000D85934BE70, len 64
  00 0e 00 09 00 60 5b 8f e4 ae b9 a2 86 32 c7 99
  5c f3 ba 83 1d 97 63 81 00 00 00 c2 a1 6b 68 6d
  61 63 2d 73 65 63 72 65 74 58 20 18 89 a7 57 e4
  dc 9b f7 5b d4 26 05 78 bb 46 14 69 e9 ca 88 ca
rx: continuation frame at 000000D85934BE70, len 64
  00 0e 00 09 01 74 1a f4 a2 74 4c a0 a4 71 e2 8b
  03 58 48 30 46 02 21 00 d7 a7 fb 7c 2b 49 db 96
  0f 0b e6 98 51 3b ea 7d 7d e7 77 f5 76 3f 7d de
  14 d3 70 df 57 6c 7d a7 02 21 00 d6 e5 3c b3 1f
rx: continuation frame at 000000D85934BE70, len 64
  00 0e 00 09 02 58 8a 8f 39 e6 25 c1 36 ac 77 dc
  14 3e ff 07 76 65 28 df f2 54 49 9f 49 17 7b c3
  04 a1 62 69 64 54 5a 6a 49 33 4d 47 5a 6c 59 7a
  67 74 5a 6d 59 33 4d 53 30 30 05 02 00 00 00 00
rx: payload at 000000D85934C090, len 230
  00 a5 01 a2 62 69 64 50 c0 51 a2 2d 28 6e 9e b1
  a1 c9 f3 46 2a a8 8b 51 64 74 79 70 65 6a 70 75
  62 6c 69 63 2d 6b 65 79 02 58 54 49 96 0d e5 88
  0e 8c 68 74 34 17 0f 64 76 60 5b 8f e4 ae b9 a2
  86 32 c7 99 5c f3 ba 83 1d 97 63 81 00 00 00 c2
  a1 6b 68 6d 61 63 2d 73 65 63 72 65 74 58 20 18
  89 a7 57 e4 dc 9b f7 5b d4 26 05 78 bb 46 14 69
  e9 ca 88 ca 74 1a f4 a2 74 4c a0 a4 71 e2 8b 03
  58 48 30 46 02 21 00 d7 a7 fb 7c 2b 49 db 96 0f
  0b e6 98 51 3b ea 7d 7d e7 77 f5 76 3f 7d de 14
  d3 70 df 57 6c 7d a7 02 21 00 d6 e5 3c b3 1f 58
  8a 8f 39 e6 25 c1 36 ac 77 dc 14 3e ff 07 76 65
  28 df f2 54 49 9f 49 17 7b c3 04 a1 62 69 64 54
  5a 6a 49 33 4d 47 5a 6c 59 7a 67 74 5a 6d 59 33
  4d 53 30 30 05 02
decode_assert_authdata: buf=0000029CFD4C3F30, len=84
decode_hmac_secret: buf=0000029CFD4C3F55, len=47
tx: d=0000029CFD4C4560, cmd=0x90, buf=000000D85934CBB4, count=1
  08
rx: initiation frame at 000000D85934BE80, len 64
  00 0e 00 09 90 00 e4 00 a4 01 a2 62 69 64 50 6d
  e1 39 1f f0 72 4a c1 78 a3 74 46 b6 73 12 ce 64
  74 79 70 65 6a 70 75 62 6c 69 63 2d 6b 65 79 02
  58 54 49 96 0d e5 88 0e 8c 68 74 34 17 0f 64 76
rx: continuation frame at 000000D85934BE80, len 64
  00 0e 00 09 00 60 5b 8f e4 ae b9 a2 86 32 c7 99
  5c f3 ba 83 1d 97 63 81 00 00 00 c3 a1 6b 68 6d
  61 63 2d 73 65 63 72 65 74 58 20 18 89 a7 57 e4
  dc 9b f7 5b d4 26 05 78 bb 46 14 69 e9 ca 88 ca
rx: continuation frame at 000000D85934BE80, len 64
  00 0e 00 09 01 74 1a f4 a2 74 4c a0 a4 71 e2 8b
  03 58 48 30 46 02 21 00 9c a0 39 c5 bf 83 34 63
  f4 09 24 46 39 24 e9 65 3f af 68 51 f9 de e0 62
  7c 43 20 0c ef 6c e8 a5 02 21 00 d3 21 c3 ff 31
rx: continuation frame at 000000D85934BE80, len 64
  00 0e 00 09 02 e9 0e 2d 47 a2 7f d6 60 f0 7e cc
  ca 25 6b 1b 9c 30 5c b4 16 c4 b4 72 b7 52 51 e8
  04 a1 62 69 64 54 67 61 51 75 41 34 32 39 53 4a
  79 32 65 39 4a 63 74 50 55 79 00 00 00 00 00 00
rx: payload at 000000D85934C0A0, len 228
  00 a4 01 a2 62 69 64 50 6d e1 39 1f f0 72 4a c1
  78 a3 74 46 b6 73 12 ce 64 74 79 70 65 6a 70 75
  62 6c 69 63 2d 6b 65 79 02 58 54 49 96 0d e5 88
  0e 8c 68 74 34 17 0f 64 76 60 5b 8f e4 ae b9 a2
  86 32 c7 99 5c f3 ba 83 1d 97 63 81 00 00 00 c3
  a1 6b 68 6d 61 63 2d 73 65 63 72 65 74 58 20 18
  89 a7 57 e4 dc 9b f7 5b d4 26 05 78 bb 46 14 69
  e9 ca 88 ca 74 1a f4 a2 74 4c a0 a4 71 e2 8b 03
  58 48 30 46 02 21 00 9c a0 39 c5 bf 83 34 63 f4
  09 24 46 39 24 e9 65 3f af 68 51 f9 de e0 62 7c
  43 20 0c ef 6c e8 a5 02 21 00 d3 21 c3 ff 31 e9
  0e 2d 47 a2 7f d6 60 f0 7e cc ca 25 6b 1b 9c 30
  5c b4 16 c4 b4 72 b7 52 51 e8 04 a1 62 69 64 54
  67 61 51 75 41 34 32 39 53 4a 79 32 65 39 4a 63
  74 50 55 79
decode_assert_authdata: buf=0000029CFD4C43B0, len=84
decode_hmac_secret: buf=0000029CFD4C43D5, len=47

**Comment by martelletto** [comment]
Thank you for the debug output.

Looking at the get assertion command, I see that the allow list is absent from the payload, and the authenticator replies with two assertions obtained with different resident credentials for localhost. Could you double-check the code that calls fido_assert_allow_cred()?

**Comment by shimritd** [comment]
Thanks a lot, we did have some problems with the allow credential list.

**Comment by shimritd** [comment]
Another question,
We are sending a request via tx (called from fido_dev_get_assert_tx) with CTAP_FRAME_INIT | CTAP_CMD_CBOR as the command.
But we are getting a response from rx (called from fido_dev_get_assert_rx) with cmd=bf which is: CTAP_FRAME_INIT | CTAP_CMD_LOCK | CTAP_KEEPALIVE

Any idea why?

**Comment by shimritd** [comment]
We found the problem, thanks!

**Comment by martelletto** [comment]
Great! I will close this issue since there is nothing objective to fix, but feel free to continue the conversation.
