### ISSUE TITLE
Returning w_char in two places?

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#44]
In the latest release docs I see `fido_dev_info_product_string` and `fido_dev_info_manufacturer_string` return `w_char`. This is weird since all other functions return normal `char`s. In the master branch they seem to do so.

Is this fixed on master?

**Comment by martelletto** [comment]
Fixed in e349342; thanks!

**Comment by PvdBerg1998** [comment]
It seems this was fixed 4 months ago. Does the 1.1 release contain this fix? Am I looking at outdated docs?

**Comment by martelletto** [comment]
The two functions return char * in 1.1, but I forgot to update the docs. My bad.

**Comment by PvdBerg1998** [comment]
Thanks for the quick response!
