### ISSUE TITLE
fido_cred_set_type

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#45]
In the docs, you write the only possible values are `COSE_RS256` and `COSE_ES256`, but in the source you also check for `COSE_EDDSA`. Is this a mistake?

**Comment by PvdBerg1998** [comment]
Perhaps this is a difference between `master` and the latest release. If so, do you have an ETA on the next release?

**Comment by martelletto** [comment]
On 29/06/2019 19:54, Pim van den Berg wrote:
> In the docs, you write the only possible values are `COSE_RS256` and `COSE_ES256`, but in the source you also check for `COSE_EDDSA`. Is this a mistake?
> 

I realise that the documentation at
https://developers.yubico.com/libfido2/Manuals/ wasn't synced to reflect
the latest release. My apologies. I will fix that next week.

The documentation in HEAD, however, is accurate, and reflects the
support for COSE_EDDSA (Ed25519), which was added in version 1.1.0. If
you are on a UNIX-like platform, I suggest installing mandoc
(https://mandoc.bsd.lv/), building libfido2 from HEAD, and looking at
the generated HTML documentation.

I expect the next release of libfido2 to happen in July.

-p.

**Comment by martelletto** [comment]
Reopening this so I don't forget to sync the docs on developers.yubico.com (again).

**Comment by PvdBerg1998** [comment]
I wonder why it is disallowed to call this function more than once?

**Comment by martelletto** [comment]
On 29/06/2019 22:02, Pim van den Berg wrote:
> I wonder why it is disallowed to call this function more than once?
> 

I thought it error-inducing to allow the credential type to be reset
when fido_cred_t might contain a public key of a different type.

We could make it fail if fido_cred_t contains a public key, but IMHO
that complicates the API in a non-trivial way.

I do understand that this limitation prevents a fido_cred_t from being
reused for a registration/authentication of a different type, which is a
bummer.

-p.

**Comment by PvdBerg1998** [comment]
Sorry to bug you about this; I'm trying my Rust wrapper, following relatively closely your `cred.c` example. I'm getting the following debug output:

> fido_dev_get_pin_token_tx: fido_blob_set
add_cbor_pin_params: fido_dev_get_pin_token
fido_dev_make_cred_tx: add_cbor_pin_params
FIDO_ERR_INTERNAL

Any idea what is happening here?

**Comment by PvdBerg1998** [comment]
It seems most functions return `FIDO_ERR_INTERNAL` when given a length of 0, which seems like it should be valid to me.

**Comment by martelletto** [comment]
The documentation at developers.yubico.com was synced to reflect master HEAD; thanks for the reminder!

**Comment by PvdBerg1998** [comment]
@martelletto Thanks for giving so much support and being patient! I wish more devs were like you. Cheers.
