### ISSUE TITLE
Ability to build libfido2 without dependency from WinHello (Windows 1909 build)

### ISSUE THREAD

**Issue by kmenshikh** [Yubico/libfido2#455]
While build libfido2 for Windows platform it depends from WinHello (webauthn.dll)
CMakeLists.txt:
//---------------------
Ver 1.8.0:
LN 196:
  if (HAVE_WEBAUTHN_H)
    add_definitions(-DUSE_WINHELLO)
    set(USE_WINHELLO ON)
  endif()
//---------------------
Ver 1.9.0
LN 191: 
  add_definitions(-DUSE_WINHELLO)
  set(USE_WINHELLO ON)
//---------------------

This prevents to use libfido2 on Windows prior 1909
I'd like to build libfido2 without dependency from WinHello (webauthn.dll).
To use it even on Windows7 (i've checked and it works pretty good on Windows7 (Ver 1.8.0)).

For now only way to comment these 2 lines of code:
  # add_definitions(-DUSE_WINHELLO)
  # set(USE_WINHELLO ON)

But it's not good solution.
I'd like to pass cmake parameter to disable WinHello:

 & $CMake <bla-bla-bla> `
   -DUSE_WINHELLO="OFF"

**Comment by martelletto** [comment]
Fixed in d0c89ecd. Thank you!
