### ISSUE TITLE
fido_dev_make_cred

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#46]
~The docs note that this function generates a Credential based on `list of excluded credential IDs;`. However, I can't find a way to actually set this list, is that correct?~ Edit: Found it. It's just not listed in the place I had expected it to be.

Also, what is the `format` (`fido_cred_set_fmt`) used for? Because it is not listed in the list of used attributes.

**Comment by PvdBerg1998** [comment]
It's used for verification. Nvm.

**Comment by martelletto** [comment]
Yes, that's correct. The description of fido_cred_set_fmt()'s purpose
could be made clearer, though. Thanks for pointing that out.

On your other point, credential IDs can be added to a credential's
exclude list through fido_cred_exclude(). As the documentation stands,
fido_dev_make_cred(3) references fido_cred_set(3), which references
fido_cred_exclude(3). Perhaps it would be better to reference
fido_cred_exclude(3) from fido_dev_make_cred(3) directly.

-p.
