### ISSUE TITLE
Is libfido2 necessary on the server side?

### ISSUE THREAD

**Issue by akaFTS** [Yubico/libfido2#460]
I'm trying to set up authentication using FIDO2 keys for my SSH server. Is libfido2 only necessary in the client side (in order to communicate with the physical key over USB) or is it needed in the server side as well?

**Comment by martelletto** [comment]
libfido2 is only necessary on the client side. The only requirement on the server side is that it needs to be able to understand the signatures made by the client, which was first included in OpenSSH 8.2.

**Comment by akaFTS** [comment]
Thanks!
