### ISSUE TITLE
libfido2 not detecting devices on macos, "Key enrollment failed: invalid format"

### ISSUE THREAD

**Issue by jaredm4** [Yubico/libfido2#462]
Not sure if this is an issue on my mac or an issue with libfido2, but it can't see to find my usb security keys (yubico security key nor yubikey 5 series nano). `ykman` can see them both just fine.

`libfido2`, `openssh` and `ykman` all installed via Homebrew.

Here is one example.

```sh
❯ $(brew --prefix ykman)/bin/ykman info
Device type: YubiKey 5 Nano
Serial number: ...
Firmware version: 5.1.2
Form factor: Nano (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID

Applications
FIDO2       	Enabled
OTP         	Enabled
FIDO U2F    	Enabled
OATH        	Enabled
YubiHSM Auth	Not available
OpenPGP     	Enabled
PIV         	Enabled
❯ $(brew --prefix libfido2)/bin/fido2-token -L
❯ $(brew --prefix libfido2)/bin/fido2-token -V
1.9.0
❯ $(brew --prefix openssh)/bin/ssh-keygen -vvvv -t ecdsa-sk -f ~/.ssh/id_ecdsa_sk2
Generating public/private ecdsa-sk key pair.
You may need to touch your authenticator to authorize key generation.
debug3: start_helper: started pid=2428
debug3: ssh_msg_send: type 5
debug3: ssh_msg_recv entering
debug1: start_helper: starting /usr/local/Cellar/openssh/8.8p1/libexec/ssh-sk-helper
debug1: sshsk_enroll: provider "internal", device "(null)", application "ssh:", userid "(null)", flags 0x01, challenge len 0
debug1: sshsk_enroll: using random challenge
debug1: sk_probe: 0 device(s) detected
debug1: ssh_sk_enroll: failed to find sk
debug1: sshsk_enroll: provider "internal" failure -1
debug1: ssh-sk-helper: Enrollment failed: invalid format
debug1: main: reply len 8
debug3: ssh_msg_send: type 5
debug1: client_converse: helper returned error -4
debug3: reap_helper: pid=2428
Key enrollment failed: invalid format
```

Any thoughts? TIA

**Comment by jaredm4** [comment]
It turns out that the Anker Thunderbolt Dock I use on this macbook pro to use USB-A keys didn't play well with libfido2. I used a different usb-A to type-C adapter/dongle straight into MBP USB-C and libfido2 can now see it.

So the takeaway here is libfido2 struggles to find USB keys on the dock/hub I'm using. I'm not sure if it's a problem with all docks or just mine.

Side note - Anyway for libfido2 to acccept Touch ID since it supports webauthn?

Feel free to close this or use as a way to track the hub issue as a bug.

**Comment by martelletto** [comment]
Thank you for the report. Could you please share the output of `FIDO_DEBUG=1 $(brew --prefix libfido2)/bin/fido2-token -L`?

**Comment by martelletto** [comment]
On a separate note, could you please check whether the changes in https://github.com/Yubico/libfido2/tree/issue-462 fix the problem for you?

```
$ brew install cmake pkg-config zlib openssl@1.1 libcbor
$ PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig" cmake -B build
$ make -C build
$ build/tools/fido2-token -L
ioreg://4298587891: ...
$ build/tools/fido2-token -I ioreg://4298587891
```

Thanks!

**Comment by jaredm4** [comment]
First question:
```sh
❯ FIDO_DEBUG=1 $(brew --prefix libfido2)/bin/fido2-token -L
get_path: IORegistryEntryGetPath
```

Second, after making your branch:
```
❯ build/tools/fido2-token -L
ioreg://4294974203: vendor=0x1050, product=0x0120 (Yubico Security Key by Yubico)
❯ build/tools/fido2-token -I ioreg://4294974203
proto: 0x02
major: 0x05
minor: 0x01
build: 0x02
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0
extension strings: hmac-secret
aaguid: 6d44ba9bf6ec2e49b9300c8fe920cb73
options: rk, up, noplat, noclientPin
maxmsgsiz: 1200
maxcredcntlst: 0
maxcredlen: 0
fwversion: 0x0
pin protocols: 1
pin retries: undefined
uv retries: undefined
```

Looks like it works and can find it now. Does this output help?

**Comment by martelletto** [comment]
It does; thank you for testing. I will put the fix forward for review by my peers next week. If it is merged, it will be part of libfido2 1.10, to be released late January / early February. The Homebrew folks are quite fast at picking up new releases, so I would expect the fix to be available in Homebrew by then. If you prefer, I would be happy to provide step by step instructions on how to rebuild OpenSSH with the fix.

Regarding Touch ID, are you aware of an interface we could use to talk to it that offers basic FIDO2/U2F primitives? I am aware of work in this area, but nothing stood out so far.

**Comment by jaredm4** [comment]
I don't, a little out of my wheelhouse. Only thing I've done regarding accessing Touch ID from shell is [enabling it for sudo access](https://apple.stackexchange.com/questions/259093/can-touch-id-for-the-mac-touch-bar-authenticate-sudo-users-and-admin-privileges). Probably not useful for this purpose though.

Thanks for being able to troubleshoot and find a solution so quickly! Impressive.

**Comment by martelletto** [comment]
Fixed. Thank you for the report & testing, and apologies for the inconvenience.
