### ISSUE TITLE
Support custom transport functions

### ISSUE THREAD

**Issue by riastradh** [Yubico/libfido2#465]
I would like to automatically test an application that uses libfido2 to make and verify credentials.  To this end, I would like to drop in a software U2F/FIDO emulator that can be used with as much of the unmodified libfido2 API as possible given a simple opt-in by an application.

**Describe the feature you would like.**
1. A way to pass a handle through fido transport functions.

   Currently fido io functions (fido_dev_io_t) have an opaque handle they can use internally, but not fido transport functions (fido_dev_handle_t).  The one use of fido transport functions inside libfido2 (nfc_linux.c) uses the io handle, but since the structure of fido_dev_t is opaque to applications outside libfido2, so custom fido transport functions can't get at the io handle either.  So custom fido transport functions are not very useful outside libfido2 (they would have to rely on static storage for what amounts to a single global device handle in the program).  Applications can use custom fido io functions instead, but that adds some extra encapsulation and decapsulation hassle that libfido2 could obviate with custom fido transport functions instead.

   Because custom fido transport functions are not very useful as is, I suggest simply changing the signatures of the transport tx and rx functions to pass an opaque handle as an argument -- either the io handle, or another handle that can be set with a new API function or parameter:

   ```
   typedef int   fido_dev_rx_t(struct fido_dev *, void *handle, uint8_t, unsigned char *, size_t, int);
   typedef int   fido_dev_tx_t(struct fido_dev *, void *handle, uint8_t, const unsigned char *, size_t);
   ```

   While here, it would be nice if fido_dev_set_sigmask worked with custom fido io or transport functions.

2. Export `fido_dev_new_with_info` and `fido_dev_open_with_info`.

   Currently these are defined, but not exported in src/export.gnu &c., so there is no way for users of the library to request the io or transport functions in a fido_dev_into_t be used in a fido_dev_t, and to use the path in a fido_dev_info_t, you have to write `fido_dev_open(dev, fido_dev_info_path(devinfo))`.

2. A way to fill fido_dev_info_t with custom path/vendor/product/transport/io.

   My application uses fido_dev_info_manifest to list the available devices, and then iterates over them (concurrently in threads) to use the devices with fido_dev_info_path, fido_dev_new, fido_dev_open, &c.  With (2) above, it would use fido_dev_new_with_info and fido_dev_open_with_info instead, and automatically get any custom io or transport functions.

   For automatic testing purposes, I would like to be able to replace the call to fido_dev_info_manifest by something that substitutes my software U2F/FIDO emulator for the host's USB HIDs.  Something like:

   ```
   if (testmode) {
           error = fido_dev_info_set(devinfo, /*index*/0, /*path*/"/path/to/softfido/state",
               /*vendor*/"Acme Fido Software, Inc.", /*product*/"Softfido Token 0.0",
               /*transport*/&softfido_transport, /*io*/&softfido_io);
           ndevs = 1;
   } else {
           error = fido_dev_info_manifest(devinfo, maxndevs, &ndevs);
   }
   ```

   As long as the rest of the application uses fido_dev_new_with_info and fido_dev_open_with_info, it would be none the wiser -- I could use the software U2F/FIDO emulator and test all the code paths I currently have to test by pushing the buttons on physical devices.

**Describe the impact to existing functionality.**
Part (1) could break code that already uses custom fido transport functions, but they aren't really useful as is.  I searched all of public GitHub for users of fido_dev_set_transport_functions, and everything I could find was in libfido2 or a copy of it.

Parts (2) and (3) should have no impact on existing functionality.

**Describe how you are willing to help.**
I drafted a software U2F/FIDO emulator using custom fido transport functions this weekend and started using it to test the application.  I've drafted these changes in a local patch to libfido2 and I would be happy to tidy the changes up and submit them as a PR if this approach seems agreeable, once I've finished verifying that my testing mechanism works.

**Comment by martelletto** [comment]
> **Describe the feature you would like.**
> 
> 1. A way to pass a handle through fido transport functions.
>    Currently fido io functions (fido_dev_io_t) have an opaque handle they can use internally, but not fido transport functions (fido_dev_handle_t).  The one use of fido transport functions inside libfido2 (nfc_linux.c) uses the io handle, but since the structure of fido_dev_t is opaque to applications outside libfido2, so custom fido transport functions can't get at the io handle either.  So custom fido transport functions are not very useful outside libfido2 (they would have to rely on static storage for what amounts to a single global device handle in the program).  Applications can use custom fido io functions instead, but that adds some extra encapsulation and decapsulation hassle that libfido2 could obviate with custom fido transport functions instead.
>    Because custom fido transport functions are not very useful as is, I suggest simply changing the signatures of the transport tx and rx functions to pass an opaque handle as an argument -- either the io handle, or another handle that can be set with a new API function or parameter:
>    ```
>    typedef int   fido_dev_rx_t(struct fido_dev *, void *handle, uint8_t, unsigned char *, size_t, int);
>    typedef int   fido_dev_tx_t(struct fido_dev *, void *handle, uint8_t, const unsigned char *, size_t);
>    ```

Would it help if we defined a `fido_dev_handle()` that returned the opaque pointer associated with a `fido_dev_t`?

> 2. Export `fido_dev_new_with_info` and `fido_dev_open_with_info`.
>    Currently these are defined, but not exported in src/export.gnu &c., so there is no way for users of the library to request the io or transport functions in a fido_dev_into_t be used in a fido_dev_t, and to use the path in a fido_dev_info_t, you have to write `fido_dev_open(dev, fido_dev_info_path(devinfo))`.

Can I kindly ask you to document these functions? That's the main reason they haven't been added to the official API yet.

> 3. A way to fill fido_dev_info_t with custom path/vendor/product/transport/io.
>    My application uses fido_dev_info_manifest to list the available devices, and then iterates over them (concurrently in threads) to use the devices with fido_dev_info_path, fido_dev_new, fido_dev_open, &c.  With (2) above, it would use fido_dev_new_with_info and fido_dev_open_with_info instead, and automatically get any custom io or transport functions.

Sounds like you are describing `fido_dev_register_manifest_func()`: https://github.com/Yubico/libfido2/blob/master/src/dev.c#L261. Would it make sense to document and incorporate this function into the official API alongside `fido_dev_new_with_info()` and `fido_dev_open_with_info()`?

Thank you,

-p.

**Comment by riastradh** [comment]
> >    Because custom fido transport functions are not very useful as is, I suggest simply changing the signatures of the transport tx and rx functions to pass an opaque handle as an argument -- either the io handle, or another handle that can be set with a new API function or parameter:
> >    ```
> >    typedef int   fido_dev_rx_t(struct fido_dev *, void *handle, uint8_t, unsigned char *, size_t, int);
> >    typedef int   fido_dev_tx_t(struct fido_dev *, void *handle, uint8_t, const unsigned char *, size_t);
> >    ```
> 
> Would it help if we defined a `fido_dev_handle()` that returned the opaque pointer associated with a `fido_dev_t`?

That would work too, as long as there's a way to set it as well.  Right now, the only opaque handle is fido_dev_t::io_handle, which is set only by calling fido_dev_open which sets it to whatever fido_dev_io_t::open returns.

I suggested changing the signature because it would more closely match how the io functions work, and there are no existing users and applications can't really use custom transport functions anyway (without confining themselves to a single static transport state in a program, or at least in each thread) so the danger of ABI breakage is negligible.  There's also not much the transport functions can do with the fido_dev_t, really -- even for nfc_linux.c, everything they do is via fido_dev_t::io_handle and the underlying I/O functions.  But separate accessor functions for the handle would be fine.

> > 1. Export `fido_dev_new_with_info` and `fido_dev_open_with_info`.
> >    Currently these are defined, but not exported in src/export.gnu &c., so there is no way for users of the library to request the io or transport functions in a fido_dev_into_t be used in a fido_dev_t, and to use the path in a fido_dev_info_t, you have to write `fido_dev_open(dev, fido_dev_info_path(devinfo))`.
> 
> Can I kindly ask you to document these functions? That's the main reason they haven't been added to the official API yet.

Sure, I can try drafting that this week.

> > 1. A way to fill fido_dev_info_t with custom path/vendor/product/transport/io.
> >    My application uses fido_dev_info_manifest to list the available devices, and then iterates over them (concurrently in threads) to use the devices with fido_dev_info_path, fido_dev_new, fido_dev_open, &c.  With (2) above, it would use fido_dev_new_with_info and fido_dev_open_with_info instead, and automatically get any custom io or transport functions.
> 
> Sounds like you are describing `fido_dev_register_manifest_func()`: https://github.com/Yubico/libfido2/blob/master/src/dev.c#L261. Would it make sense to document and incorporate this function into the official API alongside `fido_dev_new_with_info()` and `fido_dev_open_with_info()`?

Actually, fido_dev_register_manifest_func isn't quite what I want:

1. fido_dev_register_manifest_func would let me provide my own device info records _in addition to_ the system USB/NFC/&c. ones.  But in this case, for testing, I want to _replace_ the system ones so my automatic software tests aren't affected by whatever USB devices are plugged into the system when I run it.

   (It would get pretty tiresome if I had to tap the button every time a CI rig runs the test, or if plugging in a device caused the tests to take longer because they're waiting for timeouts!)

2. fido_dev_register_manifest_func doesn't, on its own, provide a way to set the members of fido_dev_info_t, so it's not enough: without exposing the struct definition of fido_dev_info_t or adding API functions like the fido_dev_info_set I sketched above, applications wouldn't be able to do anything useful in their manifest functions.

**Comment by martelletto** [comment]
> > Would it help if we defined a `fido_dev_handle()` that returned the opaque pointer associated with a `fido_dev_t`?
> 
> That would work too, as long as there's a way to set it as well. Right now, the only opaque handle is fido_dev_t::io_handle, which is set only by calling fido_dev_open which sets it to whatever fido_dev_io_t::open returns.

Let's try to explore that option then, if there are no objections.


> > Can I kindly ask you to document these functions? That's the main reason they haven't been added to the official API yet.
> 
> Sure, I can try drafting that this week.

Thank you!

> Actually, fido_dev_register_manifest_func isn't quite what I want:

You are right; my bad.

On a tangential note, does the differentiation between test/no-test need to happen at the manifest level? Something like the pseudo-code below could work otherwise:

```c
fido_dev_t *
open_dev(int test)
{
        fido_dev_t *d;

        d = fido_dev_new();

        if (test) {
                fido_set_transport_functions(d, &test_funcs);
                fido_dev_open(d, "dummy");
        } else {
                /* pick & open device from manifest */
                fido_dev_open(d, path_from_manifest);
        }

        return d;
}
```

**Comment by riastradh** [comment]
> > > Would it help if we defined a `fido_dev_handle()` that returned the opaque pointer associated with a `fido_dev_t`?
> > 
> > 
> > That would work too, as long as there's a way to set it as well. Right now, the only opaque handle is fido_dev_t::io_handle, which is set only by calling fido_dev_open which sets it to whatever fido_dev_io_t::open returns.
> 
> Let's try to explore that option then, if there are no objections.

No objection here.  What do you think about a separate fido_dev_t::transport_handle vs reusing fido_dev_t::io_handle for the transport layer too?  I'm not sure the extra complexity is warranted, but repurposing the same variable for two layers strikes me as inviting trouble down the line.

> On a tangential note, does the differentiation between test/no-test need to happen at the manifest level? Something like the pseudo-code below could work otherwise:

For a very simple case like what you quoted, that would work.  But I have considerably more logic that iterates over a list of device info records, spawns a thread for each one, opens a device in each thread, and then waits for all the threads to complete, and I'd like to exercise as much of that path as possible unconditionally:

https://github.com/riastradh/fidocrypt/blob/b3ccf5e74f112f433e0bc1fa4fbf2c809a0c84ab/fidocrypt.c#L664-L768

The actual fido_dev_new/open occurs in separate functions (https://github.com/riastradh/fidocrypt/blob/b3ccf5e74f112f433e0bc1fa4fbf2c809a0c84ab/fidocrypt.c#L358-L382, https://github.com/riastradh/fidocrypt/blob/b3ccf5e74f112f433e0bc1fa4fbf2c809a0c84ab/fidocrypt.c#L516-L540) so it can happen in separate threads.  Some of this could be factored out with some effort, but the point is that there's a lot here I would like to exercise by just changing the manifest.  Just inserting the test mode at the point of fido_dev_new/open doesn't help with that.

**Comment by LDVG** [comment]
Hi,

> No objection here. What do you think about a separate fido_dev_t::transport_handle vs reusing fido_dev_t::io_handle for the transport layer too? I'm not sure the extra complexity is warranted, but repurposing the same variable for two layers strikes me as inviting trouble down the line.

As you say, we're not sure the extra complexity is warranted. Let's first try using the existing handle.

> For a very simple case like what you quoted, that would work. But I have considerably more logic that iterates over a list of device info records, spawns a thread for each one, opens a device in each thread, and then waits for all the threads to complete, and I'd like to exercise as much of that path as possible unconditionally.

Thank you for the clarification!

**Comment by riastradh** [comment]
I drafted a PR, https://github.com/Yubico/libfido2/pull/478, to implement the proposed changes.  Some notes:

- Example change to use these for automatic testing, by dropping in a software U2F/FIDO implementation as a replacement for fido_dev_info_manifest: https://github.com/riastradh/fidocrypt/commit/e0b657ba38c10dcf4c4de0d02b5a903cc37672d5 The patch to the existing code is slightly larger than I want, because...

- fido_dev_set_sigmask currently refuses to work when there are custom transport or I/O functions.  It would be nice to be able to pass the sigmask through.

  Now, custom transport functions are unlikely to be in use outside of libfido2 as is, so I don't think it would be harmful to add a new function alongside the tx and rx functions for set_sigmask, or to add a sigmask parameter to the existing functions, but you seemed reluctant to change anything about the ABI.

  We could alternatively store the sigmask in fido_dev_t and expose a fido_dev_sigmask function to query it -- but currently custom I/O functions can't take advantage of that because they only get the I/O handle, not the fido_dev_t.

  What would you suggest doing here?

- I haven't written man pages for the new functions (fido_dev_io_handle, fido_dev_info_set), nor for fido_dev_set_transport_functions.  They seem like they belong together in a new man page, dedicated to custom transport functions, but they could also go in the existing one for fido_dev_set_io_functions.  Preferences?

**Comment by LDVG** [comment]
> I drafted a PR, #478, to implement the proposed changes. Some notes:

Thank you! I added some minor in-line comments in the PR.

> fido_dev_set_sigmask currently refuses to work when there are custom transport or I/O functions. [...]
>  What would you suggest doing here?

For now, we'd suggest handling this in the application if possible.

> * I haven't written man pages for the new functions (fido_dev_io_handle, fido_dev_info_set), nor for fido_dev_set_transport_functions.  They seem like they belong together in a new man page, dedicated to custom transport functions, but they could also go in the existing one for fido_dev_set_io_functions.  Preferences?

How about something along the lines of;
- `fido_dev_io_handle` in `fido_dev_set_io_functions.3`
- `fido_dev_set_transport_functions` in `fido_dev_set_io_functions.3`
- `fido_dev_info_set`  in `fido_dev_info_manifest.3`

**Comment by riastradh** [comment]
> > I drafted a PR, #478, to implement the proposed changes. Some notes:
> 
> Thank you! I added some minor in-line comments in the PR.

Thanks!

> > fido_dev_set_sigmask currently refuses to work when there are custom transport or I/O functions. [...]
> > What would you suggest doing here?
> 
> For now, we'd suggest handling this in the application if possible.

It's not a problem for me right now because my custom transport functions are purely computational, but this is likely to cause trouble for any applications that actually do I/O in custom transport functions (e.g., communicating with a subprocess or over a socket): there's no way for the custom transport or I/O functions to get at the caller's requested signal mask without crossing one or two abstraction barriers to get at some kind of caller state from within the transport function.

At the point of fido_dev_info_set we might not have even started the thread where the I/O happens; can't pass it through fido_dev_new/open_with_info; can't even really pass it through fido_dev_open except by a craftily formatted path, if you break the devinfo abstraction.

> > I haven't written man pages for the new functions (fido_dev_io_handle, fido_dev_info_set), nor for fido_dev_set_transport_functions.  They seem like they belong together in a new man page, dedicated to custom transport functions, but they could also go in the existing one for fido_dev_set_io_functions.  Preferences?
> 
> How about something along the lines of;
> 
>     * `fido_dev_io_handle` in `fido_dev_set_io_functions.3`
> 
>     * `fido_dev_set_transport_functions` in `fido_dev_set_io_functions.3`
> 
>     * `fido_dev_info_set`  in `fido_dev_info_manifest.3`

Sounds good, done.

**Comment by LDVG** [comment]
> It's not a problem for me right now because my custom transport functions are purely computational, but this is likely to cause trouble for any applications that actually do I/O in custom transport functions (e.g., communicating with a subprocess or over a socket): there's no way for the custom transport or I/O functions to get at the caller's requested signal mask without crossing one or two abstraction barriers to get at some kind of caller state from within the transport function.

Thank you for the comments. Since the sigmask is not required in this use case, we'd like to defer handling this extra complexity for the time being. If it turns out to be required for some use case, let's deal with it in a separate issue.

> Sounds good, done.

Thanks! I've left a few minor comments again. I'll also go ahead and request a review from my peers.
