### ISSUE TITLE
ssh-sk-helper not found on macOS - incorrect homebrew prefix 

### ISSUE THREAD

**Issue by mrinalwadhwa** [Yubico/libfido2#469]
Not sure if this is the best place to report this ... but I saw other similar issues reported here, so I hope I'm at the right place:

I'm unable to generate a `ed25519-sk` key 

```
$ ssh-keygen -t ed25519-sk
Generating public/private ed25519-sk key pair.
You may need to touch your authenticator to authorize key generation.
start_helper: helper "/usr/local/Cellar/openssh/8.8p1/libexec/ssh-sk-helper" unusable: No such file or directory
Key enrollment failed: No such file or directory
```

On my machine Homebrew's Cellar is at `~/..homebrew/Cellar` and `brew --prefix` returns `~/..homebrew`

Thank you for your help.

**What version of libfido2 are you using?**

```
libfido2: stable 1.9.0
```

**What operating system are you running?**

macOS Monterey 12.0.1

**What application are you using in conjunction with libfido2?**

OpenSSH_8.8p1

**Is the problem reproducible?**

Yes

**Please include the output of `fido2-token -L`.**

<details>
<summary><code>fido2-token -L</code></summary>
<br>
<pre>
$ fido2-token -L

IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/YubiKey OTP+FIDO+CCID@14200000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice: vendor=0x1050, product=0x0407 (Yubico YubiKey OTP+FIDO+CCID)

</pre>
</details>

**Comment by martelletto** [comment]
Hi, thank you for the report. This looks like an issue in Homebrew. At a first glance, it looks like `_PATH_SSH_SK_HELPER` is not being defined (or is wrongly defined) during OpenSSH's build. To test this hypothesis, are you able to generate and use a `ed25519-sk` key  if you set the `SSH_SK_HELPER` path to the complete path of ssh-sk-helper on your system?

**Comment by mrinalwadhwa** [comment]
Thank you, yes that worked. Sort of.

After setting `SSH_SK_HELPER ` path, I got this error.

```
$ ssh -T git@github.com
sign_and_send_pubkey: signing failed for ED25519-SK "/Users/mrinal/.ssh/id_ed25519_sk" from agent: agent refused operation
git@github.com: Permission denied (publickey).
```

but using it with `-i` displayed the same error but seems to work:

```
$ ssh  -i ~/.ssh/id_ed25519_sk  -T git@github.com
sign_and_send_pubkey: signing failed for ED25519-SK "/Users/mrinal/.ssh/id_ed25519_sk" from agent: agent refused operation
Enter passphrase for key '/Users/mrinal/.ssh/id_ed25519_sk':
Confirm user presence for key ED25519-SK SHA256:hfp5+lci3h/z9lhHsJjOm1WJsg9cZSjFwsh+ZHIDKAM
User presence confirmed
Hi mrinalwadhwa! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by martelletto** [comment]
Looks like your ssh-agent is unhappy with the key. You can try to skip it using `ssh -o IdentityAgent=none -i ~/.ssh/id_ed25519_sk -T git@github.com` or provide a corresponding blurb in `~/.ssh/config`, e.g:

```
Host github.com
        User git
        IdentityAgent none
        IdentityFile /Users/mrinal/.ssh/id_ed25519
```

**Comment by mrinalwadhwa** [comment]
That worked. Thank you for your help 🙏
