### ISSUE TITLE
fido_dev_force_u2f missing in docs

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#47]
In one of the examples, `fido_dev_force_u2f` is used, but this function is missing in the docs.

**Comment by martelletto** [comment]
On 29/06/2019 22:06, Pim van den Berg wrote:
> In one of the examples, `fido_dev_force_u2f` is used, but this function is missing in the docs.
> 

Thanks, I will add the documentation bits.

-p.

**Comment by martelletto** [comment]
Fixed in 4774e8; thanks!
