### ISSUE TITLE
How to build libfido2 on windows10

### ISSUE THREAD

**Issue by nunnnunngogo** [Yubico/libfido2#470]
I can understand what I should do first to start.
I tried to do clone and execute build.ps1 but I feel it is wrong.
My environments are windows10 and visual studio code1.16.2
I want to communicate with yubikey using CTAP. 
please tell me another way or answer this question. 

finally, I'm a beginner against computers and I would provide some information on my computer if you need it.

**Comment by martelletto** [comment]
Hi,

You were on the right track, but before you are able to run build.ps1, you need to make sure that these tools are in place: https://github.com/Yubico/libfido2/blob/master/windows/build.ps1#L6-L9. Also, please note that Yubico provides signed Windows binaries at https://developers.yubico.com/libfido2/Releases/.

-p.

**Comment by nunnnunngogo** [comment]
thank you for your reply marteletto.

I have confirmed that the tools that you point out are in the correct place.

please tell me the next step.

**Comment by martelletto** [comment]
The next step is to run build.ps1 as done in https://github.com/Yubico/libfido2/blob/master/.github/workflows/windows_builds.yml#L26, e.g:

```
$ .\windows\build.ps1 -Arch x64 -Type dynamic -Config Release
```
Alternatively, you can run release.ps1 to build every configuration, type, and architecture, but that takes a while.

**Comment by nunnnunngogo** [comment]
thanks for your reply,

I have done running release.ps1.
Is it finished?
if it is not finished, would you tell me the next step?
If you are possible, please tell me the access method to the yubikey using libfido2.

**Comment by martelletto** [comment]
If release.ps1 completed successfully, you should now have a libfido2 release in `output\pkg` and build artifacts in `build`. You can communicate with a YubiKey using the command-line tools under `output\pkg\Win64\Release\v143\dynamic` called fido2-assert, fido2-cred, and fido2-token (which are documented [here](https://developers.yubico.com/libfido2/Manuals/)), or the command-line example tools under `build\x64\dynamic\examples\Release` (which are documented [here](https://github.com/Yubico/libfido2/blob/master/examples/README.adoc)). Alternatively, you can use libfido2 to build your own application/tool. libfido2's API is documented [here](https://developers.yubico.com/libfido2/Manuals/). In all cases, if you run into problems, you can set the `FIDO_DEBUG` environment variable to 1 to capture debug output.

**Comment by nunnnunngogo** [comment]
I cannot find output\pkg.
Does it mean that build is not completed?

**Comment by nunnnunngogo** [comment]
I cannot find output\pkg.
Does it mean that build is not completed?
![１](https://user-images.githubusercontent.com/94525218/142204628-af155298-8c08-46a1-a449-f04354f30a98.PNG)

**Comment by martelletto** [comment]
If you ran release.ps1 and don't have `output\pkg`, then yes, something went wrong with the build.

**Comment by nunnnunngogo** [comment]
oh... would you tell me how to fix it? I would provide some information if you need.

**Comment by martelletto** [comment]
Sure, but would you mind reaching out to me in private so we don't annoy other people? My e-mail address is quite easy to find. Feel free to reach out.

**Comment by nunnnunngogo** [comment]
I just sent an email to you. Thank you.

**Comment by borrrden** [comment]
Hello, sorry to hijack this but actually I'm having a similar problem.  I confirmed that problem also happens when running the manifest.exe program from this repo as well.  Only one device shows up in the output (Windows Hello) but the HID detection doesn't seem to be working.  The Yubikey Manager detects it though.

**Comment by borrrden** [comment]
Omg I commented on the wrong issue!  I meant to comment on https://github.com/Yubico/libfido2/issues/384 but I also had this one open.  Sorry!

**Comment by martelletto** [comment]
@borrrden the Windows Hello pseudo-device functions as a proxy for HID communication, which is blocked to unprivileged applications in recent versions of Windows. Does HID detection work if you run manifest.exe with administrator privileges? If it doesn't, could you capture the output of FIDO_DEBUG? Thanks!

**Comment by martelletto** [comment]
Hi @G-S-E,

Thank you for the detailed debug output.

> run_manifest: found 1 hid device
> \\?\hid#vid_1050&pid_0402#9&37e46d38&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: vendor=0x1050, product=0x0402 (Yubico YubiKey FIDO)

This is the path of the HID device. Can you please try to:

```
$ fido2-token.exe -d -S "\\?\hid#vid_1050&pid_0402#9&37e46d38&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"
```

**Comment by G-S-E** [comment]
> This is the path of the HID device. Can you please try to:

That works but can I use windows://hello pseudo-device somehow? Is it possible to use it as a non-admin user?

Thank you.

**Comment by martelletto** [comment]
> That works but can I use windows://hello pseudo-device somehow? Is it possible to use it as a non-admin user?

The set of operations allowed on the windows://hello pseudo-device (which is a thin abstraction around webauthn.dll) is restricted by Windows. You should be able to use it to enroll credentials (authenticatorMakeCredential) and get signatures (authenticatorGetAssertion). Anything else (e.g. PIN management, or virtually any operation implemented by fido2-token) will require direct access to the HID device, and therefore administrator privileges.
