### ISSUE TITLE
Build with BUILD_STATIC_LIBS option, still depend on openssl and libcbor

### ISSUE THREAD

**Issue by c2uc2u** [Yubico/libfido2#471]
I would like to bundle the libfido2,openssl1.1, and libcbor as single package to be referenced in my project. See for the static libfido2.a file generated by BUILD_STATIC_LIBS, it still depends on the openssl1.1 and libcbor. could you guide me on how to bundle them in just in one .a file?
Thanks!

**Comment by martelletto** [comment]
Assuming you are in a UNIX-like environment, you will need to find `libcbor.a` and `libcrypto.a` and use `ar x` to extract the contents of the two archives, followed by `ar qc bundle.a *.o` to create a bundle with all the object files. Please note that `libcbor.a` and `libcrypto.a` should correspond to the header files used to build libfido2.

**Comment by c2uc2u** [comment]
Hi Martelletto
Thanks for the suggestion. Maybe my question is not clear enough. Let me add more explanation.
In my project, I have two components, e.g component A is for another function and it links to OpenSSL 3.0 (libcrypto.a).
Component B is libfido2 which link to openssl 1.1 (libcrypyo.a).
Because of the symbol conflict, I cannot link the different OpenSSL version (libcrypto.a) into one project, so I propose to do the following:
For component B (libfido2), make it as a shared lib and include two static libs: libcbor.a and libcrypto.a(1.1), then I can add the shared lib into the project as a workaround.

It seems libcbor and libcrypto in libfido2 is a share link, I would like to find a way to make them as the static lib in libfido2.

Thanks!

**Comment by martelletto** [comment]
Oh, I see. Sorry for the confusion. You could do this:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3ac6e0d..e97c358 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -206,8 +206,9 @@ else()
                message(FATAL_ERROR "could not find zlib")
        endif()

-       set(CBOR_LIBRARIES "cbor")
-       set(CRYPTO_LIBRARIES "crypto")
+       set(CBOR_LIBRARIES "/home/pedro/fakeroot/lib64/libcbor.a")
+       set(CRYPTO_LIBRARIES "/home/pedro/fakeroot/lib64/libcrypto.a")
+       set(ZLIB_LIBRARIES "/home/pedro/fakeroot/lib/libz.a")

        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
                pkg_search_module(UDEV libudev REQUIRED)
```

Then:

```sh
$ PKG_CONFIG_PATH=/dev/null cmake -DCRYPTO_INCLUDE_DIRS=/home/pedro/fakeroot/include -DCRYPTO_LIBRARY_DIRS=/home/pedro/fakeroot/lib -B build
```

(The exact flags will depend on your build environment. You may not need to define `CRYPTO_{INCLUDE,LIBRARY}_DIRS`.)

This will give you a `libfido2.so.1.10.0` with cbor/OpenSSL/zlib symbols defined, resolved internally, but not exported.

On a side note, libfido2 1.9.0 is compatible with OpenSSL 3.0, so you could reuse libcrypto.a from component A.

Hope this helps!

-p.

**Comment by c2uc2u** [comment]
Hi martelletto,
Thanks for the detailed info, it works on my side.
