### ISSUE TITLE
Missing Windows Install Instuctions

### ISSUE THREAD

**Issue by mikeburns7** [Yubico/libfido2#479]
Please add instructions for installing libfido2 on Windows. 

I see there is a build.ps1 script in the .windows directory which I assume needs to be run to install libfido2, but it is not immediately clear if this is how to conduct the install.

If running build.ps1 is the proper procedure, I am happy to write up the procedure

**Comment by mikeburns7** [comment]
When downloading from https://developers.yubico.com/libfido2/Releases/libfido2-1.9.0-win.zip - where is the documentation on how to install the release?

Where do you place the files once unzipped?

**Comment by martelletto** [comment]
That depends on your project's build system. I might be able to help you depending on what you are trying to do, but there is no universal answer to that question.

**Comment by mikeburns7** [comment]
I am not building a project.

I was following this post about how github now supports ssh security keys. 
 - https://www.yubico.com/blog/github-now-supports-ssh-security-keys/

Following this post, under the "Getting Started" section, the post suggests libfido2 to be installed:
_"To get started you’ll need OpenSSH version 8.2 or later, and you’ll also need libfido2 installed. Windows users may need to use Cygwin for this."_

This lead me to assume I need to install this library on my windows machine in order to create an ssh key on my YubiKey

**Comment by martelletto** [comment]
Work to support security keys on Windows is ongoing: https://github.com/PowerShell/openssh-portable/pull/541. You could try the Cygwin ssh package, but whether it supports security keys is unclear to me. I will try to get the article clarified. Thank you.

**Comment by martelletto** [comment]
Closing as there isn't much else that can be done on the topic in the scope of this forum.
