### ISSUE TITLE
Inconsistent behaviour when given a length of 0

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#48]
It seems *some* (like `fido_dev_make_cred`, `fido_cred_exclude`) functions return `FIDO_ERR_INTERNAL` when given a length of 0, which seems like it should be valid to me, or it should return `FIDO_ERR_INVALID_LENGTH` or similar.

**Comment by martelletto** [comment]
I agree that FIDO_ERR_INTERNAL is a misleading error to return.

-p.

**Comment by martelletto** [comment]
Fixed in 4ca0d9e7; thanks!
