### ISSUE TITLE
Biometric enrollment using fido2-token exe giving error FIDO_ERR_PIN_AUTH_INVALID

### ISSUE THREAD

**Issue by alpha-check** [Yubico/libfido2#480]
Hii,
I am trying to enroll a biometric using a authenticator (THINC by ensurity) which has biometric reader.
i am using command 
**./fido2-token -S -e device**  to enroll a new biometric,
using fido2-token executable which is in libfido2.

but after PIN prompt I am getting error 
**cbor_parse_reply : blob[0]=0x33
bio_rx_enroll_begin: bio_parse_enroll_status
bio_enroll_begin_wait: tx/rx
fido2-token: fido_bio_dev_enroll_begin : FIDO_ERR_PIN_AUTH_INVALID.**

please help me out and can you please tell me what is the way to enroll a biometric if i am building libfido2 code on a new OS which does not support FIDO2 till now.

**Comment by martelletto** [comment]
Hi, thank you for opening an issue. Could you share the output of `fido2-token -Se` with the `FIDO_DEBUG` environment variable set to 1?

**Comment by alpha-check** [comment]
@martelletto thanks for quick response.
here is logs in debug mode 


fido_tx: dev=0x23cb028, cmd=0x06
fido_tx: buf=0x23cb028, len=8
0000: d8 fa cc f5 ba e6 4e 46
fido_rx: dev=0x23cb028, cmd=0x06, ms=-1
rx_preamble: buf=0xbdb4349c, len=64
0000: ff ff ff ff 86 00 11 d8 fa cc f5 ba e6 4e 46 ae
0016: 45 23 89 02 01 01 01 07 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=17
fido_rx: buf=0x23cb030, len=17
0000: d8 fa cc f5 ba e6 4e 46 ae 45 23 89 02 01 01 01
0016: 07
fido_dev_get_cbor_info_tx: dev=0x23cb028
fido_tx: dev=0x23cb028, cmd=0x10
fido_tx: buf=0xbdb434f0, len=1
0000: 04
fido_dev_get_cbor_info_rx: dev=0x23cb028, ci=0x23cb0b8, ms=-1
fido_rx: dev=0x23cb028, cmd=0x10, ms=-1
rx_preamble: buf=0xbdb42c74, len=64
0000: ae 45 23 89 90 00 ad 00 a8 01 83 66 55 32 46 5f
0016: 56 32 68 46 49 44 4f 5f 32 5f 30 6c 46 49 44 4f
0032: 5f 32 5f 31 5f 50 52 45 02 82 6b 68 6d 61 63 2d
0048: 73 65 63 72 65 74 6b 63 72 65 64 50 72 6f 74 65
rx: payload_len=173
rx: buf=0xbdb42c74, len=64
0000: ae 45 23 89 00 63 74 03 50 45 4e 53 46 49 44 4f
0016: fd 6c 93 8e 92 67 19 3e 9a 04 a7 62 72 6b f5 62
0032: 75 70 f5 62 75 76 f5 64 70 6c 61 74 f4 69 63 6c
0048: 69 65 6e 74 50 69 6e f5 75 63 72 65 64 65 6e 74
rx: buf=0xbdb42c74, len=64
0000: ae 45 23 89 01 69 61 6c 4d 67 6d 74 50 72 65 76
0016: 69 65 77 f5 78 1b 75 73 65 72 56 65 72 69 66 69
0032: 63 61 74 69 6f 6e 4d 67 6d 74 50 72 65 76 69 65
0048: 77 f5 05 19 04 b0 06 81 01 07 0a 08 18 60 00 00
fido_rx: buf=0xbdb42cec, len=173
0000: 00 a8 01 83 66 55 32 46 5f 56 32 68 46 49 44 4f
0016: 5f 32 5f 30 6c 46 49 44 4f 5f 32 5f 31 5f 50 52
0032: 45 02 82 6b 68 6d 61 63 2d 73 65 63 72 65 74 6b
0048: 63 72 65 64 50 72 6f 74 65 63 74 03 50 45 4e 53
0064: 46 49 44 4f fd 6c 93 8e 92 67 19 3e 9a 04 a7 62
0080: 72 6b f5 62 75 70 f5 62 75 76 f5 64 70 6c 61 74
0096: f4 69 63 6c 69 65 6e 74 50 69 6e f5 75 63 72 65
0112: 64 65 6e 74 69 61 6c 4d 67 6d 74 50 72 65 76 69
0128: 65 77 f5 78 1b 75 73 65 72 56 65 72 69 66 69 63
0144: 61 74 69 6f 6e 4d 67 6d 74 50 72 65 76 69 65 77
0160: f5 05 19 04 b0 06 81 01 07 0a 08 18 60

fido_dev_open_rx: FIDO_MAXMSG=2048, maxmsgsiz=1200
Enter PIN for /dev/hidraw0:
Touch your security key.
fido_dev_authkey_tx: dev=0x23cb028
fido_tx: dev=0x23cb028, cmd=0x10
fido_tx: buf=0x23cc1f0, len=6
0000: 06 a2 01 01 02 02
fido_dev_authkey_rx: dev=0x23cb028, authkey=0x23cbfa8, ms=-1
fido_rx: dev=0x23cb028, cmd=0x10, ms=-1
rx_preamble: buf=0xbdb42be4, len=64
0000: ae 45 23 89 90 00 50 00 a1 01 a5 01 02 03 26 20
0016: 01 21 58 20 ab dc 33 a3 d2 4a 29 0b 19 73 f1 88
0032: 8d f8 4b 92 51 65 1c d3 20 83 39 db e5 91 8f b3
0048: 1f 38 b6 cc 22 58 20 9a 32 f4 69 40 e2 9c dc 43
rx: payload_len=80
rx: buf=0xbdb42be4, len=64
0000: ae 45 23 89 00 1b 4d cc 9a f4 6c 0a d9 b6 bf e7
0016: 75 e9 cb 01 28 df dd b6 43 84 58 31 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
fido_rx: buf=0xbdb42c64, len=80
0000: 00 a1 01 a5 01 02 03 26 20 01 21 58 20 ab dc 33
0016: a3 d2 4a 29 0b 19 73 f1 88 8d f8 4b 92 51 65 1c
0032: d3 20 83 39 db e5 91 8f b3 1f 38 b6 cc 22 58 20
0048: 9a 32 f4 69 40 e2 9c dc 43 1b 4d cc 9a f4 6c 0a
0064: d9 b6 bf e7 75 e9 cb 01 28 df dd b6 43 84 58 31
fido_tx: dev=0x23cb028, cmd=0x10
fido_tx: buf=0x23cd690, len=103
0000: 06 a4 01 01 02 05 03 a5 01 02 03 38 18 20 01 21
0016: 58 20 b5 93 ea c7 f2 68 b2 63 2e 93 60 d8 ed 32
0032: 99 28 a6 b1 3e 5d 55 d4 b4 78 1e 7d fa 69 04 d6
0048: 8c 60 22 58 20 ce 98 31 db ae 35 47 24 a5 82 d8
0064: bb 49 3f 16 61 6f 91 49 0e f5 89 ef 11 4c 9f c6
0080: 3f 59 60 c1 17 06 50 c1 8b 61 be d8 97 ad 4d b1
0096: 17 73 ce d1 3b 0b 18
fido_rx: dev=0x23cb028, cmd=0x10, ms=-1
rx_preamble: buf=0xbdb42bf4, len=64
0000: ae 45 23 89 90 00 25 00 a1 02 58 20 7b f6 ae 7f
0016: cc c0 90 22 fb 01 67 6e 12 38 33 19 06 72 89 47
0032: 92 15 80 39 81 88 9f f1 0b e6 e9 6e 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=37
fido_rx: buf=0xbdb42c6c, len=37
0000: 00 a1 02 58 20 7b f6 ae 7f cc c0 90 22 fb 01 67
0016: 6e 12 38 33 19 06 72 89 47 92 15 80 39 81 88 9f
0032: f1 0b e6 e9 6e
fido_tx: dev=0x23cb028, cmd=0x10
fido_tx: buf=0x23cb628, len=34
0000: 40 a5 01 01 02 01 03 a1 03 1a 00 00 27 10 04 01
0016: 05 50 e1 1f ec 02 88 95 86 49 d1 53 26 24 7d a9
0032: fd 2c
fido_rx: dev=0x23cb028, cmd=0x10, ms=-1
rx_preamble: buf=0xbdb42c6c, len=64
0000: ae 45 23 89 90 00 01 33 00 00 00 00 00 00 00 00
0016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0032: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0048: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
rx: payload_len=1
fido_rx: buf=0xbdb42ce4, len=1
0000: 33
cbor_parse_reply: blob[0]=0x33
bio_rx_enroll_begin: bio_parse_enroll_status
bio_enroll_begin_wait: tx/rx
fido2-token: fido_bio_dev_enroll_begin: FIDO_ERR_PIN_AUTH_INVALID

**Comment by martelletto** [comment]
Thank you for the debug output. It is not immediately obvious to me why that's failing. My understanding is that your authenticator is following https://fidoalliance.org/specs/fido2/vendor/BioEnrollmentPrototype.pdf, with which the code seems to comply. As an extra data point, could you try the diff below and see if it gets you further?

```diff
diff --git a/src/bio.c b/src/bio.c
index 4ddc937..a5d7254 100644
--- a/src/bio.c
+++ b/src/bio.c
@@ -429,7 +429,7 @@ bio_enroll_begin_wait(fido_dev_t *dev, fido_bio_template_t *t,
                goto fail;
        }
 
-       if ((r = bio_tx(dev, cmd, argv, 3, NULL, e->token, ms)) != FIDO_OK ||
+       if ((r = bio_tx(dev, cmd, NULL, 0, NULL, e->token, ms)) != FIDO_OK ||
            (r = bio_rx_enroll_begin(dev, t, e, ms)) != FIDO_OK) {
                fido_log_debug("%s: tx/rx", __func__);
                goto fail;

**Comment by alpha-check** [comment]
After the changes now i am getting this error 
"
bio_rx_enroll_begin: fido_rx
bio_enroll_begin_wait: tx/rx
-2 : return value from the bio_enroll_begin_wait
fido2-token: fido_bio_dev_enroll_begin: FIDO_ERR_RX
"

earlier  **bio_tx** was not giving error as per what i have found in debugging **bio_rx_enroll_begin** what giving error.
As I don't have much knowledge about these function will you please explain what these 2 functions are doing as a whole.

thanks a lot

**Comment by martelletto** [comment]
These functions are trying to communicate with your authenticator to initiate a fingerprint enrollment procedure. That's an operation that requires libfido2 to prove to the authenticator that it knows the correct PIN. When computing this proof, libfido2 ends up with a different value than the one expected by the authenticator.

The error you saw with the diff is a bit strange. I will have to circle back and take another look at the debug output. Thanks for testing.

**Comment by martelletto** [comment]
@alpha-check, are you able to use Chrome to enroll a fingerprint using chrome://settings/securityKeys? If so, could you please capture and share the output of chrome://device-log/?refresh=5?

**Comment by alpha-check** [comment]
@martelletto , I tried to enroll fingerprint  on chrome on this path  chrome://settings/securityKeys? but there is no option for biometric enrollment in chrome browser over desktop (Windows 10). 
But I am able to register a key for the 2-factor authentication over chrome by TAP and PIN. 

one thing that I want to know is this command **./fido2-token -S -e device**  sufficient to start a biometric enroll on the key.
second, Is there any demo website where I can check the process of biometric enrollment.

**Comment by martelletto** [comment]
`fido2-token -Se <device>` should be enough to start a fingerprint enrollment on a FIDO2.1 biometric authenticator, but for some reason it is failing with your authenticator. I am not aware of any website implementing biometric enrollment; to the best of my knowledge, that's a functionality not exposed by browsers to RPs. Since you are able to enroll a fingerprint using Windows Hello, could you share the logs from Event Viewer (Event Viewer -> Applications and Services Logs -> Microsoft -> Windows -> WebAuthN -> Operational)?

Regarding chrome://settings/securityKeys, I don't think that's a region-specific feature; it's just not available on Windows. It should work if you retry from Linux/macOS.

**Comment by alpha-check** [comment]
please find logs of the bio enrollment on the windows hello.
[fido_bio_enroll_event.txt](https://github.com/Yubico/libfido2/files/7675034/fido_bio_enroll_event.txt)

**Comment by martelletto** [comment]
Thank you for the logs. Does the following diff help? If not, could you please include the output of FIDO_DEBUG?

```diff
diff --git a/src/bio.c b/src/bio.c
index 4ddc937..8c52de5 100644
--- a/src/bio.c
+++ b/src/bio.c
@@ -424,7 +424,7 @@ bio_enroll_begin_wait(fido_dev_t *dev, fido_bio_template_t *t,
 
        memset(&argv, 0, sizeof(argv));
 
-       if ((argv[2] = cbor_build_uint32(timo_ms)) == NULL) {
+       if ((argv[2] = cbor_build_uint(timo_ms)) == NULL) {
                fido_log_debug("%s: cbor encode", __func__);
                goto fail;
        }
@@ -520,7 +520,7 @@ bio_enroll_continue_wait(fido_dev_t *dev, const fido_bio_template_t *t,
        memset(&argv, 0, sizeof(argv));
 
        if ((argv[0] = fido_blob_encode(&t->id)) == NULL ||
-           (argv[2] = cbor_build_uint32(timo_ms)) == NULL) {
+           (argv[2] = cbor_build_uint(timo_ms)) == NULL) {
                fido_log_debug("%s: cbor encode", __func__);
                goto fail;
        }
```

**Comment by alpha-check** [comment]
@martelletto after above change now enrollment is working fine on our setup. 

can you tell me what is the command to verify those enrolled biometric using libfido2.
thanks

**Comment by martelletto** [comment]
Glad to hear it's working. There's a range of things you can do to verify the enrollment:

- List enrolled biometric templates using `fido2-token -Le`;
- Associate a friendly name with a given template id using `fido2-token -Se -i template_id -n name`;
- Use the bundled examples to perform registration + authentication steps using biometric UV;
- List enrolled biometric templates on Windows;
- Use a browser to perform registration + authentication steps on https://demo.yubico.com/ using biometric UV.
