### ISSUE TITLE
Add support for communication via NFC for Windows

### ISSUE THREAD

**Issue by kmenshikh** [Yubico/libfido2#481]
Inspired from: https://github.com/Yubico/libfido2/issues/249  (Add support for communication via NFC for MacOS #249)

Is it possible to do subj?
I've tried to do this (via Windows SmartCard API) and it works good on Windows 10 (on Windows 7 there are troubles).
"I've tried" means i extended functionality of libfido2.

It seems it's not hard enough.

**Comment by martelletto** [comment]
Hi, sure, that'd be a nice addition. Could you share some code?

**Comment by kmenshikh** [comment]
I need to get approval from my managers to share code.
Once i get it i'll post code here.

**Comment by kmenshikh** [comment]
JFI: I don't forget about "share some code".
Approval process is in progress (big company - big bureaucracy).

**Comment by brett-berger** [comment]
@martelletto does Yubikey have a Contributors License agreement (CLA) you can point me to?  Before @kmenshikh can share his code our legal team wants to review Yubikey's CLA. thx

**Comment by martelletto** [comment]
@brett-berger, as long as the contributed code is under the same license as libfido2, we typically don't require a CLA: https://github.com/Yubico/libfido2/blob/master/LICENSE. Should that prove unsatisfactory to your legal team, could you please reach out to me at pedro [at] yubico [dot] com? Thank you.

**Comment by kmenshikh** [comment]
@brett-berger could you answer @martelletto 's question?

**Comment by brett-berger** [comment]
@martelletto this works for us. 

/*                                                                              
 * © Copyright 2022 Micro Focus or one of its affiliates.
 * Use of this source code is governed by a BSD-style license                   
 * that can be found in the LICENSE file.                                       
 */
