### ISSUE TITLE
yubikey 5 NFC device fails during registration on windows 

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#483]
Hi,

fido library version: 1.5.0
device model:  USB-A YubiKey 5 NFC Firmware 5.4.3

During registration fido_cred_verify() fails.
On relying party here is the dump:
fido_check_flags: flags=41
fido_check_flags: up=2, uv=0
verify_sig: ECDSA_verify
fido_cred_verify: verify_sig

Iam not sure what am i missing. Can you please point me on what is wrong.

Regards
Satish.B

**Comment by martelletto** [comment]
From a first look, it seems the registration itself worked, but signature verification failed on the server. Could this be the same issue as https://github.com/Yubico/libfido2/issues/461?

**Comment by sb230132** [comment]
FYI
If i disable FIDO2 module on the device, iam able to do perform registration and authentication.
Is it the case that the device is generating attestation format in "packed" format ?

On server iam expecting a fido-u2f format.

If so can i force the device to always generate a fido-u2f format using fido_cred_set_fmt() ?

**Comment by sb230132** [comment]
No its not webauthn client.

**Comment by martelletto** [comment]
You can use [fido_dev_force_u2f()](https://developers.yubico.com/libfido2/Manuals/fido_dev_force_u2f.html) to force an application to talk U2F to a FIDO2 device. Does that help?

**Comment by sb230132** [comment]
Thanks for the help.
Should i force it during authentication as well ?

**Comment by martelletto** [comment]
If you don't need any FIDO2-specific feature (such as PINs or biometric UV) during authentication, it wouldn't make much of a difference. It should otherwise be possible to enroll using U2F and authenticate using FIDO2.

**Comment by martelletto** [comment]
Any objections to closing this issue?

**Comment by sb230132** [comment]
Yes, you can close the issue.
Another question, is there any limit on length of authenticator data generated during registration ?

**Comment by martelletto** [comment]
In theory, there are no limits other than the one imposed by the transport layer. In practice, the length of the authenticator data payload will mostly be determined by the type of the attested credential (larger for RSA, shorter for ECDSA/ED25519), but is unlikely to exceed 512 bytes.

**Comment by sb230132** [comment]
Thanks for the information.
Do you see any issues with below code where i try to force U2F.


  fido_init(0);
  size_t dev_infos_len = 0;
  fido_dev_info_t *dev_infos = fido_dev_info_new(1);
  if (fido_dev_info_manifest(dev_infos, 1, &dev_infos_len) != FIDO_OK) {
    fido_dev_info_free(&dev_infos, 1);
    return true;
  }
  const fido_dev_info_t *curr = fido_dev_info_ptr(dev_infos, 0);
  const char *path = fido_dev_info_path(curr);
  /* open the device */
  fido_dev_t *dev = fido_dev_new();
  /* force u2f */
  fido_dev_force_u2f(dev);
  if (fido_dev_open(dev, path) != FIDO_OK) {
   return true;;
  }

**Comment by martelletto** [comment]
The call to fido_dev_force_u2f() needs to happen after the device is opened. I will amend the documentation to clarify this.

**Comment by sb230132** [comment]
Oh, will check it. Thanks.
