### ISSUE TITLE
Document nullable pointers

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#49]
It's unclear to me what pointers can be NULL. I see you calling set_user with two NULL arguments. Can I NULL all of them? This holds for any parameter for any function.

**Comment by martelletto** [comment]
It is safe to assume a pointer parameter cannot be NULL unless
documented otherwise. fido_cred_set_user() is special in that not all of
the configurable user attributes are required. I will amend the
documentation to mention this.

-p.

**Comment by martelletto** [comment]
Fixed in 9bb7213; thanks!
