### ISSUE TITLE
Issue with C# wrapper

### ISSUE THREAD

**Issue by AdityaSharma21** [Yubico/libfido2#496]
Hi, The libfido2 have the C# wrapper for communicating FIDO over USB with FIDO2 and CTAP2 protocol.
So, When we are building this library on **Windows OS** following through ReadMe we are getting the error of **"failed to build libressl"** as shown below.
So, We tried with the releases(https://developers.yubico.com/libfido2/Releases/) for libfido2 library which is pre-build and with that we were able to communicate with the Fido device over USB and able to Reset device, change pin on device but when we execute the makecredential call we are getting below issue with the release library.
And with the release libraries of libfido2 why its showing the static path for cbor_isa_map(item), 
**file C:\Users\marte\libfido2\build\libcbor-0.8.0\src\cbor\maps.c, line 114**

So, Will you please suggest that what we are missing.

<img width="615" alt="libfido2-BuildError" src="https://user-images.githubusercontent.com/18227512/147724575-1ab95593-9931-48f4-9d01-7ef1a87db51a.PNG">
<img width="674" alt="MakeCredential-Error" src="https://user-images.githubusercontent.com/18227512/147724582-f0f5f248-479f-40b0-a2dd-9edfeac5241c.PNG">

**Comment by martelletto** [comment]
I honestly have no idea. Perhaps report it at https://github.com/borrrden/Fido2Net?
