### ISSUE TITLE
Requesting supported COSE protocols

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#50]
Is there a way to request the supported COSE protocols? I'm getting a runtime error because I chose an unsupported one, but have no method (afaik) to check which ones I can use.

**Comment by martelletto** [comment]
Unfortunately, there is no way to probe the algorithms supported by an
authenticator other than trying to create a credential. If the chosen
algorithm is not supported by the authenticator, fido_dev_make_cred()
will return FIDO_ERR_UNSUPPORTED_ALGORITHM.

-p.
