### ISSUE TITLE
Any UI to show user to touch the key or input pin with libfido2

### ISSUE THREAD

**Issue by c2uc2u** [Yubico/libfido2#505]
Would like to know if there is any mechanism that to show a message window to tell the user to touch the key or input the pin code when using libfido2. Or any callback helps to trigger the application process to show the message? 

Thanks!

**Comment by martelletto** [comment]
There isn't much we offer out of the box in that regard. libfido2's API functions take the PIN as a parameter and are blocking by default. The only way (that I can think of) to achieve the required level of concurrency is to fork a separate execution flow. Something we have considered in the past was exporting the various _tx() and _rx() functions in libfido2 (on top of which the synchronous API calls are built). The conclusion at the time was that, without a real use case to ground the design, it wasn't worth the effort. That said, we are definitely open to exploring solutions, provided they keep the library small and are not too complex.

-p.

**Comment by c2uc2u** [comment]
Understand! Thanks!
