### ISSUE TITLE
fido_cred_verify vs fido_assert_verify

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#51]
What is the difference between `fido_cred_verify` and `fido_assert_verify`? They seem to do the same thing, but `fido_cred_verify` only supports `ES256`.

**Comment by PvdBerg1998** [comment]
It seems `fido_cred_verify` is hardcoded to use `ES256`: https://github.com/Yubico/libfido2/blob/a098ec19fda7f3d4b7277fc662f1c5ca9e585272/src/cred.c#L390

**Comment by PvdBerg1998** [comment]
No offense but it seems to me the whole `assertion` abstraction is useless, since you could just initialize a `Credential` and verify that. It seems to duplicate all the fields of `Credential`. `Credential` can already be initialized partially, so why not take advantage of this? All the functionality for settings the fields for verification is already there, why duplicate it into another type?

**Comment by PvdBerg1998** [comment]
Also, there is no consistency between the two: assertions has 4 separate functions for user (`fido_assert_user_name` etc), while Credentials has all in one: `fido_cred_set_user`.

**Comment by martelletto** [comment]
There are two steps in CTAP2: registration and authentication. While
there is certainly an overlap of parameters and terminology between the
two, they accomplish different things and have different semantics.

Registration involves the creation of a new credential on an
authenticator. At its core, a credential is a public/private key pair
with associated metadata. When an authenticator creates a new
credential, it uses a pre-programmed key to sign the credential and
provides the platform with the newly created credential, the resulting
signature, and a certificate attesting the key that was used to sign the
credential. The intention is to ascertain that the credential was indeed
created on the authenticator. What fido_cred_verify() does is to verify
that the credential was signed with the key attested in the certificate
presented by the authenticator. Please note that verification of the
certificate itself is not done by fido_cred_verify().

Authentication involves the use of the private key of an existing
credential to sign a challenge. What fido_assert_verify() does is to
check whether the requested challenge was successfully signed by the
authenticator under the required conditions (user presence, user
verification). The use of a credential to sign a challenge is called an
assertion in FIDO2.

There is a high-level overview of FIDO2 in
https://developers.yubico.com/FIDO2/, and a more in-depth description in
https://developers.yubico.com/FIDO2/FIDO2_WebAuthn_Developer_Guide/.

-p.

**Comment by PvdBerg1998** [comment]
Thanks a lot for you explanation. I hope I haven't been annoying :sweat_smile: Still: could fido_cert_verify support the other algorithms such as RS256? Also a assertion constructor that takes a certificate and automatically adds all fields would be very useful (I will add it to my wrapper if you decide not to add here).

**Comment by PvdBerg1998** [comment]
The assertion constructor may be nice for testing, but after reading the links you sent me it seems better if they are separate entities. I'll look into it.

**Comment by PvdBerg1998** [comment]
Is the attestation statement included in `auth_data`? They are separate things in the yubico dev guide.

**Comment by PvdBerg1998** [comment]
The returned Credential flags contain the following information: `The AT indicates whether the authenticator added attested credential data, and is always 1 for registrations. The ED flag indicates if the authenticator data has extensions. The UP flag indicates if the user is present. The UV flag indicates if the user is verified (PIN or biometric).` Is there a way to retrieve these flags?

**Comment by martelletto** [comment]
User presence/consent is mandatory when creating a credential, which is
why there is no option to request it explicitly, and no need to check
the flag. If an authenticator allows credentials to be created without
user interaction, it is broken.

This is explained in more detail here:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html#authenticatorMakeCredential

"Step 8: If the authenticator has a display, show the items contained
within the user and rp parameter structures to the user. Alternatively,
request user interaction in an authenticator-specific way (e.g., flash
the LED light). Request permission to create a credential. If the user
declines permission, return the CTAP2_ERR_OPERATION_DENIED error."

-p.

**Comment by PvdBerg1998** [comment]
Quoting from https://www.w3.org/TR/webauthn/#registering-a-new-credential:

> When registering a new credential, represented by an AuthenticatorAttestationResponse structure response and an AuthenticationExtensionsClientOutputs structure clientExtensionResults, as part of a registration ceremony, a Relying Party MUST proceed as follows:

> 10. Verify that the User Present bit of the flags in authData is set.

I agree that the authenticator is broken if it does not do this, but I think it would be good to follow the explicitly required steps listed.

**Comment by martelletto** [comment]
Interesting. I see that the part of the CTAP2 spec that describes
interoperability with CTAP1 (U2F) authenticators [1] indeed says the UP
bit should be set in authdata, which is in line with the W3C document.
This information should probably be reflected in the description of
authenticatorMakeCredential as well.

-p.

[1]
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html#u2f-authenticatorMakeCredential-interoperability

**Comment by PvdBerg1998** [comment]
Could `fido_cert_verify` support the other algorithms such as RS256? It currently assumes ES256.

**Comment by PvdBerg1998** [comment]
I just tried creating a `RS256` credential, but my authenticator returns this:
```
rx: initiation frame at 000000F40799E550, len 64
  00 0c 00 25 90 00 01 2c 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
parse_cbor_reply: blob[0]=0x2c
fido_dev_make_cred_rx: parse_makecred_reply
FIDO_ERR_INVALID_OPTION
```
Any idea why?

**Comment by martelletto** [comment]
On 30/06/2019 14:03, Pim van den Berg wrote:
> Could `fido_cert_verify` support the other algorithms such as RS256? It currently assumes ES256. 

I am not aware of anything in the spec requiring the attestation
certificate to use ES256. On the other hand, I have never heard of an
authenticator using a different signature scheme.

Unless there is a real device we need to support, I'd rather keep the
code simple. And unless this hypothetical authenticator makes it to my
hands, I am unlikely to be the one to write the code to support it. :)

-p.

**Comment by PvdBerg1998** [comment]
Forgive me if I'm misunderstanding this, but is this algorithm the same as the one you'd choose in `fido_cred_set_type`? Because this would mean 2/3 possibilities can't be verified.

**Comment by martelletto** [comment]
On 30/06/2019 14:04, Pim van den Berg wrote:
> I just tried creating a `RS256` credential, but my authenticator returns this:
> ```
> rx: initiation frame at 000000F40799E550, len 64
>   00 0c 00 25 90 00 01 2c 00 00 00 00 00 00 00 00
>   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> parse_cbor_reply: blob[0]=0x2c
> fido_dev_make_cred_rx: parse_makecred_reply
> FIDO_ERR_INVALID_OPTION
> ```
> Any idea why?
> 

Can you try to make the credential resident (option -r if you are using
examples/cred.c)?

-p.

**Comment by martelletto** [comment]
On 30/06/2019 14:39, Pim van den Berg wrote:
> Forgive me if I'm misunderstanding this, but is this algorithm the same as the one you'd choose in `fido_cred_set_type`? Because this would mean 2/3 possibilities can't be verified.

That is the algorithm used by the authenticator to sign the credential,
not the algorithm of the credential itself (which you can set with
fido_cred_set_type).

-p.

**Comment by PvdBerg1998** [comment]
Indeed, that fixes it. Why is that the case? Is this also the case for EDDSA (can't test that one)?

**Comment by martelletto** [comment]
On 30/06/2019 14:43, Pim van den Berg wrote:
> Indeed, that fixes it. Why is that the case? Is this also the case for EDDSA (can't test that one)?

The short answer is that some authenticators might only support resident
credentials of a given COSE type. Unfortunately there is no "a priori"
way to know.

The slightly longer answer is that, due to the size of a 2048-bit RSA
key, it becomes impractical to wrap it in order to make it a
non-resident credential.

-p.

**Comment by martelletto** [comment]
A check for user presence was added to fido_cred_verify() in f9f34be.
