### ISSUE TITLE
Are command line tools shipped with the package? 

### ISSUE THREAD

**Issue by AntonyChiossi** [Yubico/libfido2#511]
> provides library functionality and **command-line tools** to communicate with a FIDO device over USB, and to verify attestation and assertion signatures.

I am asking because after the installation of the package libfido2-dev I could not find any tool installed in the system (ubuntu).

Thank you!

**Comment by martelletto** [comment]
The tools are part of Ubuntu's [fido2-tools](https://packages.ubuntu.com/search?keywords=fido2-tools&searchon=names&suite=all&section=all) package. Backports of the latest release can be obtained from [Yubico's PPA](https://launchpad.net/~yubico/+archive/ubuntu/stable), while documentation is available at https://developers.yubico.com/libfido2/Manuals/.
