### ISSUE TITLE
Building static library on windows

### ISSUE THREAD

**Issue by PvdBerg1998** [Yubico/libfido2#53]
Building the library myself I see the generated package is dynamic. Would it be possible to compile a static version, and if so, what would be the changes required to the `build.ps1`?

**Comment by martelletto** [comment]
The package generated by build.ps1 contains only the dynamic library,
but it produces a full installation with both static and dynamic
libraries under output/{32,64}.

-p.

**Comment by PvdBerg1998** [comment]
Off topic question: do you see what I'm doing wrong:

Define: client data hash CDH, relying party id RPID. Then:
1. Generate credential with CDH and RPID (and other metadata). Store as CRED
2. Verify credential: is ok
3. Create assertion with CDH and RPID
4. Verify assertion with CRED.pubkey: failure invalid signature

**Comment by PvdBerg1998** [comment]
> 
> The package generated by build.ps1 contains only the dynamic library, but it produces a full installation with both static and dynamic libraries under output/{32,64}.

I've tried linking them statically but my application crashes with a missing dll error.

**Comment by martelletto** [comment]
On 01/07/2019 21:40, Pim van den Berg wrote:
> I've tried linking them statically but my application crashes with a missing dll error.

It sounds like you are missing at least one of libfido2's dependencies.
Note that the dependencies are shared libraries.

-p.

**Comment by martelletto** [comment]
On 01/07/2019 21:35, Pim van den Berg wrote:
> Off topic question: do you see what I'm doing wrong:
> 
> Define: client data hash CDH, relying party id RPID. Then:
> 1. Generate credential with CDH and RPID (and other metadata). Store as CRED
> 2. Verify credential: is ok
> 3. Create assertion with CDH and RPID
> 4. Verify assertion with CRED.pubkey: failure invalid signature
> 

My unsubstantiated guess is that a non-resident credential is being
created, and the assertion produced with a resident credential. Could
you provide the output of the above steps with FIDO_DEBUG=1?

-p.

**Comment by PvdBerg1998** [comment]
For the dependencies: this is probably the case yes. About the invalid sig: haven't tested yet, but I generated a multitude of resident and non resident keys using the same user id, relying party etc. Will the resident key take priority here? That would explain the error. Is there a way to retrieve the pubkey of the resident key? What would happen if I generate another resident key using the same user data, does it copy the old one or overwrite it?

**Comment by PvdBerg1998** [comment]
> My unsubstantiated guess is that a non-resident credential is being created, and the assertion produced with a resident credential. 
Changing the user ID doesn't change the outcome.
The complete debug log is here: https://pastebin.com/2wYDvDnf. It contains some extra output from my lib.

**Comment by martelletto** [comment]
On 02/07/2019 12:27, Pim van den Berg wrote:
> For the dependencies: this is probably the case yes. About the invalid sig: haven't tested yet, but I generated a multitude of resident and non resident keys using the same user id, relying party etc. Will the resident key take priority here? That would explain the error. Is there a way to retrieve the pubkey of the resident key? What would happen if I generate another resident key using the same user data, does it copy the old one or overwrite it?
> 

If the allow list is empty (i.e fido_assert_allow_cred wasn't used) and
there is a resident credential for the RP, the authenticator will use
the resident credential to complete the assertion.

Retrieving the public key of a resident key is possible through the
Credential Management API.

If you generate another resident key using the same RP + user ID
combination as that of an existing resident credential, the credential
will be overwritten.

-p.

**Comment by PvdBerg1998** [comment]
> If you generate another resident key using the same RP + user ID
> combination as that of an existing resident credential, the credential
> will be overwritten.

I just tried it and it still gives the same error. However, it does work when I change the relying party ID.

**Comment by martelletto** [comment]
On 02/07/2019 15:09, Pim van den Berg wrote:
> I just tried it and it still gives the same error. However, it does work when I change the relying party ID.

From the pastebin I see that a non-resident credential is created,
followed by an assertion with an empty allow list. If the credential is
not resident, you need to pass it to fido_assert_allow_cred() when
making an assertion. Otherwise the authenticator will either fail to
produce an assertion, or produce an assertion using any existing
resident keys for the given RP.

-p.

**Comment by martelletto** [comment]
Hi @PvdBerg1998, can I close this issue?

-p.

**Comment by PvdBerg1998** [comment]
Yes, sorry. Though I never managed to get the static linking to work iirc.
