### ISSUE TITLE
Could I verify PIN code with any APIs of libfido2?

### ISSUE THREAD

**Issue by heilonli** [Yubico/libfido2#562]
"fido_dev_get_assert" and "fido_dev_make_cred" will return "FIDO_ERR_PIN_INVALID" when pin code is invalid.
I only need to verify the PIN code is valid or not without making credentials.
Is it possible with libfido2?
Thanks.

**Comment by martelletto** [comment]
`fido_dev_get_assert()` does not make credentials. You could use it with user presence disabled to trigger a silent assertion:

```c
fido_assert_set_up(assert, FIDO_OPT_FALSE);
fido_dev_get_assert(dev, assert, pin);
```

Alternatively, you could use `fido_dev_set_pin()` to set the PIN to itself:

```c
fido_dev_set_pin(dev, pin, pin);
```

Please note that failed PIN attempts cause the PIN retry counter to be decremented.

**Comment by heilonli** [comment]
> 
If I use fido_dev_set_pin(dev, pin, pin); to set same PIN, it will return  FIDO_OK, how about set different PIN ?
For example: my yubikey has PIN "1234", now I call  fido_dev_set_pin(dev, "5678", "5678");, what value will return ?
Thanks

**Comment by martelletto** [comment]
FIDO_ERR_PIN_INVALID (0x31), as per https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#changingExistingPin

**Comment by heilonli** [comment]
> FIDO_ERR_PIN_INVALID (0x31), as per https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#changingExistingPin

Let me try this.

**Comment by heilonli** [comment]
@martelletto 
Thank you so much~
It works now. I can know the pin is valid or not with 'fido_dev_set_pin'.
Really appreciate~
I close this question now.
