### ISSUE TITLE
Can allowCredentials list be empty ?

### ISSUE THREAD

**Issue by sb230132** [Yubico/libfido2#563]
Hi,
After u2F registration, i save public key and credential ID in RP server.
During u2F authentication, RP server passes credential ID, random challenge and RP ID to client.

Is it compulsory for RP server to send credential ID during assertion ?
In webauthN specs i see that allowCredentials can be empty. In this case what is the authenticator flow ?

Regards
Satish.B

**Comment by martelletto** [comment]
Hi,

The credential ID is optional for resident keys. Resident keys are a FIDO2 feature and do not exist in U2F. Whether a credential is resident is defined during enrollment (authenticatorMakeCredential). If the criteria for a credential's discoverability are met, an application will be able to ask a FIDO2 authenticator for signatures (authenticatorGetAssertion) with only the RP ID. Discoverability criteria for resident keys are a FIDO2.1 feature (see https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#sctn-credProtect-extension). Resident keys are discoverable by default. Should there be multiple resident keys associated with the same RP ID, the authenticator will return signatures for all of them. In this case, the application can use the user ID associated with each signature (fido_assert_user_id_{ptr,len} in libfido2) to distinguish between enrollments/accounts.

-p.

**Comment by martelletto** [comment]
Closing in the understanding that the question was answered. Please feel free to reopen and/or continue the conversation.

**Comment by sb230132** [comment]
Hi,
Iam trying out few things with resident keys support in authenticator.

echo credential challenge | openssl sha256 -binary | base64 > u1
echo mysql.com >> u1
echo u1 >> u1
dd if=/dev/urandom bs=1 count=32 | base64 >> u1

echo new credential challenge | openssl sha256 -binary | base64 > u1_1
echo mysql.com >> u1_1
echo u1 >> u1_1
dd if=/dev/urandom bs=1 count=32 | base64 >> u1_1

/* CREATE RESIDENT CREDENTIALS */
fido2-cred -M -i u1 -o u1_out -r 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

fido2-cred -M -i u1_1 -o u1_1_out -r 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

ykman fido credentials list
Enter your PIN:
mysql.com 4018433d16d872ee4cb9fccb2804d5e30b8094fd809486d6ef03f23c05c18d8a u1
mysql.com 6a9a0bb361d5a9cc98edc3b34c9a2b4b8fd561f83eba4a3d99897df55cb84e0b u1

/* VERIFY ATTESTATION */
fido2-cred -V -i u1_out -o u1_out_pub
fido2-cred -V -i u1_1_out -o u1_1_out_pub

Note iam not setting credential ID.
echo assertion challenge | openssl sha256 -binary | base64 > u1_assert
echo mysql.com >> u1_assert
tail -n +2 u1_out_pub > u1_pubkey

echo new assertion challenge | openssl sha256 -binary | base64 > u1_1_assert
echo mysql.com >> u1_1_assert
tail -n +2 u1_1_out_pub > u1_1_pubkey

/* GET ASSERTION */
fido2-assert -G -r -i u1_assert -o u1_assert_out 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

fido2-assert -G -r -i u1_1_assert -o u1_1_assert_out 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

/* VERIFY ASSERTION */
fido2-assert -V -i u1_assert_out u1_pubkey es256  <-- fails
fido2-assert: fido_assert_verify: FIDO_ERR_INVALID_SIG
fido2-assert -V -i u1_assert_out u1_1_pubkey es256 <-- success
fido2-assert -V -i u1_1_assert_out u1_1_pubkey es256 <-- success

Why signature verification failed with u1_pubkey but passes with u1_1_pubkey ?
Am i missing something or, is there some extra handling which is missing in fido2-assert ?

Regards
Satish.B

**Comment by martelletto** [comment]
Hi @sb230132,

> /* GET ASSERTION */ fido2-assert -G -r -i u1_assert -o u1_assert_out 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'
> 
> fido2-assert -G -r -i u1_1_assert -o u1_1_assert_out 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

When an assert's 'allow list' is empty, the authenticator replies with signatures for each resident key associated with the given RP. This is what is happening here. 
> 
> /* VERIFY ASSERTION */ fido2-assert -V -i u1_assert_out u1_pubkey es256 <-- fails fido2-assert: fido_assert_verify: FIDO_ERR_INVALID_SIG fido2-assert -V -i u1_assert_out u1_1_pubkey es256 <-- success fido2-assert -V -i u1_1_assert_out u1_1_pubkey es256 <-- success
> 
> Why signature verification failed with u1_pubkey but passes with u1_1_pubkey ? Am i missing something or, is there some extra handling which is missing in fido2-assert ?

fido2-assert -V expects a single assertion, so it is only looking at the first assertion.

-p.

**Comment by sb230132** [comment]
Hi Martelleto,

Ok, so if i understand correctly.
I need to loop over all public keys associated with 'u1' user, and verify the signature ?

Regards
Satish.B

**Comment by martelletto** [comment]
@sb230132, using fido2-assert, yes. In a more complex application, you could look at each assertion's associated user id (fido_assert_user_id_ptr/fido_assert_user_id_len) and look up the corresponding public key (from a database, for example).

**Comment by sb230132** [comment]
Thanks a lot.

**Comment by sb230132** [comment]
Hi Martelleto,

Iam trying to understand how to specify exclude credential list. Here is what i did.

Did registration of user (u1) for RP server (mysql.com).

fido2-cred -V -i u1_out -o u1_out_pub
head -1 u1_out_pub
hMc5fxMTQswI9fDgIXH4/wtOxf4w+01+nnOfUo7rMg66NdrWb1QS9yV5R9jeGB5l <<- i assume this credential ID

If you notice there is one credentials for user u1.
ykman fido credentials list
Enter your PIN: 
mysql.com a81de845fe751fbb1c5ad6770ff0d40950beda6437040b7d3b151c06f47c0ec2 u1

Now i want to do registration of same user (u1) for RP server (mysql.com) by specifying above credential ID in fido_cred_exclude(). To my understanding, authenticator should not generate any new credential this time.

echo new credential challenge | openssl sha256 -binary | base64 > u1_1
echo mysql.com >> u1_1
echo u1 >> u1_1
dd if=/dev/urandom bs=1 count=32 | base64 >> u1_1
head -1 u1_out_pub >> u1_1 
See that last line is the exclude credentials details.

I modified cred_make.c program to read the last line and call fido_cred_exclude().

struct blob exclude_cred_list;
memset(&exclude_cred_list, 0, sizeof(exclude_cred_list));
r |= base64_read(in_f, &exclude_cred_list);
r = fido_cred_exclude(cred, exclude_cred_list.ptr, exclude_cred_list.len);
..
free(exclude_cred_list.ptr);

fido2-cred -M -i u1_1 -o u1_1_out -r 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'
Enter PIN for IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice: 

ykman fido credentials list                                                                                                                                                                                    
Enter your PIN: 
mysql.com 919bcb1b9f2aed84897493f67b479db50f144ed661aa24768cbd9c76a3884c0a u1
mysql.com a81de845fe751fbb1c5ad6770ff0d40950beda6437040b7d3b151c06f47c0ec2 u1

I dont know why i see a new credential created for same user, same RP server.
Is my understanding correct. How do i ensure that authenticator does not generate credentials in case i specify list of credentials to be excluded ?

Regards
Satish.B

**Comment by martelletto** [comment]
Hi @sb230132,

This works for me:

```
tha:~/projects/libfido2> build/examples/cred
usage: cred [-t ecdsa|rsa|eddsa] [-k pubkey] [-ei cred_id] [-P pin] [-T seconds] [-b blobkey] [-hruv] <device>
zsh: exit 1     build/examples/cred
tha:~/projects/libfido2> build/examples/cred -k pubkey1 -i cred_id1 -P 123123 $DEV
tha:~/projects/libfido2> build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1 -P 123123 $DEV
cred: fido_makecred: FIDO_ERR_CREDENTIAL_EXCLUDED (0x19)
zsh: exit 1     build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1 -P 123123 $DEV
tha:~/projects/libfido2> build/examples/cred -k pubkey1-rk -i cred_id1-rk -r -P 123123 $DEV   
tha:~/projects/libfido2> build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1 -P 123123 $DEV
cred: fido_makecred: FIDO_ERR_CREDENTIAL_EXCLUDED (0x19)
zsh: exit 1     build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1 -P 123123 $DEV
tha:~/projects/libfido2> build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1-rk -P 123123 $DEV
cred: fido_makecred: FIDO_ERR_CREDENTIAL_EXCLUDED (0x19)
zsh: exit 1     build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1-rk -P 123123 $DEV
tha:~/projects/libfido2> build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1-rk -r -P 123123 $DEV
cred: fido_makecred: FIDO_ERR_CREDENTIAL_EXCLUDED (0x19)
zsh: exit 1     build/examples/cred -k pubkey2 -i cred_id2 -e cred_id1-rk -r -P 123123 $DEV
```

-p.

**Comment by sb230132** [comment]
Hi Martelleto,

How can i skip creation of credentials given same user name and RP server.

**Comment by martelletto** [comment]
Hi @sb230132,

Your understanding is correct. The only part that didn't register for me was this:

>    2.2 If i set exclude credential list with cred ID extracted from step 1, i think authenticator should not create any new key
>    pair. Am i right ? Instead i see FIDO_ERR_CREDENTIAL_EXCLUDED error being reported.

`FIDO_ERR_CREDENTIAL_EXCLUDED` is returned by the authenticator to indicate that a credential wasn't created.

-p.

**Comment by sb230132** [comment]
Hi Martelleto,

Thanks for clarifying my understanding.
So authenticator reporting FIDO_ERR_CREDENTIAL_EXCLUDED means credentials exists for given RP server/username ?
Is there any other possibility for authenticator to report FIDO_ERR_CREDENTIAL_EXCLUDED ?

Why cant authenticator instead return existing public key credentials for given RP server/username if exists.
Is this behaviour authenticator specific or is it as per FIDO2 standards ?

Regards
Satish.B

**Comment by martelletto** [comment]
> So authenticator reporting FIDO_ERR_CREDENTIAL_EXCLUDED means credentials exists for given RP server/username ?

For the given RP.

> Is there any other possibility for authenticator to report FIDO_ERR_CREDENTIAL_EXCLUDED ?

I don't think so, at least according to a quick glance at the spec.
 
> Why cant authenticator instead return existing public key credentials for given RP server/username if exists. Is this behaviour authenticator specific or is it as per FIDO2 standards ?

This behaviour is per spec.

**Comment by sb230132** [comment]
Hi Martelleto,

One more question.

When i perform fido2-cred -M for a given RP server (mysql.com) twice for same user name and user ID, i see that the no# of credentials generated is 1. Which i think is fine. But when i perform fido2-cred -V with output from above, i get 2 different public keys/credentials ID. Is this expected ?

My question is, if there is only 1 credential, no matter how many times we perform verify cred it should always report same public key. Right ?

Iam doing following:
dd if=/dev/urandom bs=1 count=32 | base64 > user_ID 

echo credential challenge | openssl sha256 -binary | base64 > u1
echo mysql.com >> u1
echo u1 >> u1
cat user_ID >> u1

echo new credential challenge | openssl sha256 -binary | base64 > u1_1
echo mysql.com >> u1_1
echo u1 >> u1_1
cat user_ID >> u1_1

fido2-cred -M -i u1 -o u1_out -r 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

fido2-cred -M -i u1_1 -o u1_1_out -r 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/YubiKey OTP+FIDO+CCID@14100000/IOUSBHostInterface@1/AppleUserUSBHostHIDDevice'

ykman fido credentials list                                                                                                                                                                                    
Enter your PIN: 
mysql.com 5e4e2f329a6961c5fbf271506c02a19d673ceba55456a8f951959b09a6b2b4e6 u1

Only 1 credentials exists. 

fido2-cred -V -i u1_out -o u1_out_pub
fido2-cred -V -i u1_1_out -o u1_1_out_pub

If you notice there are 2 different credential IDs and public keys for 1 single credential in the authenticator. Why ?

cat u1_out_pub 
wlneTcDjb6LFHcDsFUmDSfQElebQE7gQb+WfKsNZMHMenmfFbtiNHKFHwNqTYvVH
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwlneTcDjb6LFHcDsFcrVEcX5qdNI
z6AMMMpGEiT7TRVOE3LzgIE5NH9qaZTcGWEbOvar55DA5pzn7UngHub2Cw==
-----END PUBLIC KEY-----

cat u1_1_out_pub
+f/hfM/yqwPwOI/uGB3ApMbAkGs+PIu7fpQ15QSmiRUaJQPBq2tP+4oYWl81OXyI
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+f/hfM/yqwPwOI/uGOW8pVelOrDQ
wixNGh1v6JFLX7PM6YCW8gK0ItghvPAHk72MKZfS96hLyO+b16KLlVVsfQ==
-----END PUBLIC KEY-----

Regards
Satish.B

**Comment by martelletto** [comment]
Hi @sb230132,

The second `fido2-cred -M -r` is overwriting the credential created by the first, resulting in a different credential ID and public key. This is specified here: https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorMakeCredential (step 10) and here: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-20210615.html#op-makecred-step-rk, for FIDO 2.0 and 2.1 respectively.

Please feel free to use GitHub Discussions in the future!

-p.

**Comment by sb230132** [comment]
Hi Martelleto,
Thanks for clarification.
Regards
Satish.B
