### ISSUE TITLE
is_fido: unsupported report len

### ISSUE THREAD

**Issue by Silvercast** [Yubico/libfido2#59]
```
is_fido: unsupported report len
is_fido: unsupported report len
is_fido: unsupported report len
is_fido: unsupported report len
is_fido: unsupported report len
```

I see a lot of these in log when turn on debug info. Wonder why it happens. It works with real device however [SoftU2F](https://github.com/github/SoftU2F) doesn't work because of the following check. I'm on macOS libfido2 1.2.0

```

if (report->getLength() != sizeof(U2FHID_FRAME) || report->prepare() != kIOReturnSuccess)
    return;

```

**Comment by martelletto** [comment]
Hi Silvercast,

Apologies for the delay; I was on vacation.

These "unsupported report len" messages are the result of libfido2 sifting through available HID devices. I have changed the code to be quieter in 424c4310f. Thanks!

Please note that I haven't been able to test the code, as it seems libfido2 no longer works out of the box on Catalina. Some sort of additional incantation is needed.
