### ISSUE TITLE
What's up with fido_cred_set_fmt and fido_cred_set_type?

### ISSUE THREAD

**Issue by frozencemetery** [Yubico/libfido2#6]
Hi, I've built a [toy client and server](https://github.com/frozencemetery/u2fsperiments) using libfido2.  It's working, but there are some behaviors I don't understand:

- If I don't set cred_fmt on my client, it defaults to fido-u2f.  (Okay, but contradicts man page.)
- If I don't set cred_fmt on the server, validation fails with INVALID_ARGUMENT (Annoying, but okay.)
- If I set cred_fmt on the server to fido-u2f, validation succeeds.  (Okay.)
- If I set cred_fmt on the client explicitly to fido-u2f, and set fido-u2f on the server, validation succeeds.  (Okay.)
- If I set cred_fmt to "packed", I still get a token with format fido-u2f, as reported by `fido_cred_fmt()`.  This passes server validation with server format set to fido-u2f.  (I don't understand this.)

Also:

- If I don't `fido_cred_set_type()` on the client, the client fails `make_cred` with invalid argument. (Annoying, but okay.)
- If I set both client and server to `COSE_ES256`, validation succeeds.  (Okay.)
- If I do `fido_cred_set_type()` only on the client to `COSE_ES256`, server validation succeeds.  (Unexpected, but okay.)
- If I `fido_cred_set_type()` on the client to `COSE_RS256`, the client fails `make_cred()` with invalid argument.  (I don't understand this.)
- If I `fido_cred_set_type()` on only the server to `COSE_RS256`, the validation succeeds, despite it not matching the `COSE_ES256` on the client.  (I really don't understand this.)

I'm running git master of libfido2, and have a U2F-only YubiKey from the GitHub promotion, if that matters.

Thanks!

**Comment by frozencemetery** [comment]
Hi, thanks for the prompt reply!

> Perhaps it would make sense to have fido_dev_make_cred() return an
> error if the format chosen by authenticator does not match that of a
> previous fido_cred_set_fmt(). I would appreciate your thoughts on
> this.

I think it would make sense to have it fail rather than do something
unexpected.

In general, I'd prefer if the `fido_cred_set_fmt()` call failed - the
pattern of having `make_cred()` be the only meaningful failure means I
then have to go back with a debugger and figure out *which* argument was
INVALID.  But since this is a consistent pattern in the API, I assume
there's some obstacle to providing that kind of interface.

> What is happening right now is that, since attestation signatures are
> always ECDSA, the type of the credential is being ignored. That is
> definitely a bug.

Does that mean that the type is something I should
make the client and server agree on, even though they don't need to
right now?  Or will the server still be able to work without knowing?

(I'll submit a man page update PR once I understand that.)

Thanks,
--Robbie

**Comment by martelletto** [comment]
Hi,

>I think it would make sense to have it fail rather than do something
>unexpected.
>
>In general, I'd prefer if the `fido_cred_set_fmt()` call failed - the
>pattern of having `make_cred()` be the only meaningful failure means I
>then have to go back with a debugger and figure out *which* argument was
>INVALID.  But since this is a consistent pattern in the API, I assume
>there's some obstacle to providing that kind of interface.

The obstacle in this case is that the validation of the credential 
parameters is made by the authenticator, which we only talk to in 
fido_dev_make_cred().

What we could do is to define parameter-specific error codes and 
have fido_dev_make_cred() return them, so that it is simpler for the 
consumer of the API to identify what went wrong.

Thank you once again for your perspective on this.

>Does that mean that the type is something I should
>make the client and server agree on, even though they don't need to
>right now?  Or will the server still be able to work without knowing?

The former: the type is something that the client and server need to 
agree on, even though they don't need to right now.

With the modifications in the cred_type branch, the server will 
check the credential's actual type (retrieved from the authenticator 
data blob) against that specified by fido_cred_set_type(), and 
return an error if they don't match.

I have also added a regression test to catch the mismatch case:

        fido_cred_set_type(cred, COSE_RS256);
        (...)
        fido_cred_set_authdata(cred, es256_authdata);
        ^_ now returns FIDO_ERR_INVALID_ARGUMENT;
        (...)
        fido_cred_verify(cred);
        ^_ now returns FIDO_ERR_INVALID_ARGUMENT;

(See invalid_type() in regress/cred.c for details.)

Note to self: fix typo in commit message when rebasing.

-p.

**Comment by frozencemetery** [comment]
Thanks!  I think I understand now, so I'm going to close this ticket.
