### ISSUE TITLE
Wrong "alg" parameter in hmac-secret extension public key

### ISSUE THREAD

**Issue by andrewkozlik** [Yubico/libfido2#60]
When encoding the hmac-secret extension parameters for an authenticatorGetAssertion request (https://github.com/Yubico/libfido2/blob/master/src/cbor.c#L818) the library uses COSE_ES256 (ECDSA w/ SHA-256) as the "alg" parameter in the public key (https://github.com/Yubico/libfido2/blob/master/src/es256.c#L83). This is clearly wrong, since the algorithm it is being used for is ECDH key agreement, not ECDSA signature.

**Comment by andrewkozlik** [comment]
Related to https://github.com/Yubico/python-fido2/issues/67#issuecomment-536916484.

**Comment by martelletto** [comment]
fixed in 9d44af2c; thanks!
