### ISSUE TITLE
Authenticator data

### ISSUE THREAD

**Issue by rendaw** [Yubico/libfido2#62]
This may be just a question.

So it looks like the Webauthn spec defines the [authenticator data](https://w3c.github.io/webauthn/#sctn-authenticator-data) as a plain memory structure.

libfido2 AFAICT requires a cbor encoded structure, however the structure is just a single byte string field which is the structure referred to above.

In order to validate authenticator data from javascript more easily would it be reasonable to have a `fido_assertion_set_authdata_raw` method or somesuch?  Specifically for language bindings, this would avoid the need to depend on an additional cbor library to verify assertions.  The current method ends up just unwrapping the cbor anyway.

**Comment by martelletto** [comment]
Hi,

Sure, it makes sense. I have pushed some code to that end in c726eeac.

If you don't mind, just in order to understand your use case better: how are you obtaining authdata in Javascript? Do you have the need to manually inspect it?

Thank you,

-p.

**Comment by rendaw** [comment]
Awesome, thanks!

Here's roughly what I do:
```javascript
navigator.credentials.get({
    publicKey: {
        challenge: urlsafe_b64d(root.getAttribute("data-challenge")),
        allowCredentials: [
            {
                id: urlsafe_b64d(root.getAttribute("data-id")),
                type: "public-key"
            }
        ],
        rpId: root.getAttribute("data-domain"),
    }
}).then(result => {
    document.getElementsByName("clientDataJSON")[0].setAttribute("value", urlsafe_b64e(new Uint8Array(result.response.clientDataJSON)))
    document.getElementsByName("signature")[0].setAttribute("value", urlsafe_b64e(new Uint8Array(result.response.signature)))
    document.getElementsByName("authenticatorData")[0].setAttribute("value", urlsafe_b64e(new Uint8Array(result.response.authenticatorData)))
    document.getElementById("form").submit()
}).catch(reason => {
    document.getElementById("error").textContent = "Error attempting WebAuthn confirmation!  Reload or check your console for details."
    console.error(reason);
})
```
And then with libfido2 I:

1. Check the clientdata values
2. Pass in the received sig, clientdata (after hashing), and authdata with no other modifications
3. Set expected rpId, public key, key algorithm and validate

So I'm not parsing authdata ATM.  I'm working on a stateless server so checking the signature count isn't really possible (and my own authenticator is clonable so I'm not sure I'd want to check anyway).

Not quite sure that was what you were asking for :) but glad to answer other questions or receive any insight you might have.

**Comment by martelletto** [comment]
Thanks! Interesting to see the different ways the library is being used. I have merged the code to master. Let me know if anything else pops up!
