### ISSUE TITLE
Key for signing release tarballs has been revoked

### ISSUE THREAD

**Issue by lazka** [Yubico/libfido2#629]
```
==> Verifying source file signatures with gpg...
    libfido2-1.11.0.tar.gz ... FAILED (public key A166878817F3906C has been revoked)
```

https://keyserver.ubuntu.com/pks/lookup?search=0xA166878817F3906C&fingerprint=on&op=index

**Comment by martelletto** [comment]
Thank you for the report. I have asked my colleagues to re-sign the tarballs with a valid PGP key. Apologies for the breakage.

**Comment by lazka** [comment]
Thanks, no problem. You might also want to remove the key from the list at https://developers.yubico.com/Software_Projects/Software_Signing.html

**Comment by kongeo** [comment]
Hi! Please find the new sigs uploaded here: [https://developers.yubico.com/libfido2/Releases/](https://developers.yubico.com/libfido2/Releases/)
