### ISSUE TITLE
Is there any better way to get client data and assertion response in C-library, like python get_assertion() by a single API call? 

### ISSUE THREAD

**Issue by malateshk** [Yubico/libfido2#64]
Is there any way that in a single API call can get the client data and assertion response in C-library too like python get_assertion() API? is it possible in simple way to get these details in any of the current API's

It's really helpful in authentication if the return can be captured in some structure.

Python API example:
assertions, client_data = client.get_assertion(rp_id, challenge, allow_list)

Thanks

**Comment by martelletto** [comment]
Hi,

libfido2 is client data agnostic by design; the assumption is that the caller is either indifferent to its format (i.e the client data hash is a random challenge), in its possession, or able to reconstruct it.

-p.
