### ISSUE TITLE
Why this timeout is not used in hid?

### ISSUE THREAD

**Issue by ikimonogakari** [Yubico/libfido2#69]
https://github.com/Yubico/libfido2/blob/96cff7d74fa2dd415da16d7e5132b3ee5985b89c/src/hid_linux.c#L314

This timeout is not used throughout.
Why don't use it?
Or are we planning to use the hidapi library?
It has complete support for hid device and also more platforms, like cygwin.
https://github.com/libusb/hidapi

**Comment by martelletto** [comment]
Hi,

Timeouts tend to be application/platform specific; libfido2 does not support them out of the box. However, the library was designed to allow applications to enforce timeouts with relative ease.

The simplest way to go is to use [fido_dev_set_io_functions()](https://developers.yubico.com/libfido2/Manuals/fido_dev_set_io_functions.html) to define your own HID backend (hidapi, for example).

A more complex (but more flexible) approach is to export the [_wait() variants](https://github.com/Yubico/libfido2/blob/96cff7d74fa2dd415da16d7e5132b3ee5985b89c/src/assert.c#L253) of API functions that perform device I/O, and embed libfido2 in your application.

There are no plans to add more dependencies to libfido2.

-p.
