### ISSUE TITLE
CMake version too old

### ISSUE THREAD

**Issue by akallabeth** [Yubico/libfido2#718]
all versions of `libfido2` have ` cmake_minimum_required(VERSION 3.0)` set.

Reading https://cmake.org/cmake/help/latest/module/FindPkgConfig.html confirms the following:

The `PKG_CONFIG_PATH` search path is only updated with `CMake`  3.1 or higher. So dependencies using `pkg-config` might not be detected (depending on your installed `CMake`.

**Comment by LDVG** [comment]
Hi,

As far as I understand the documentation in your link, `PKG_CONFIG_PATH` from the environment is always honored. It is only various `CMAKE_*` variables that are not _appended_ to the `PKG_CONFIG_PATH` until CMake version 3.1 and later.

If I'm misunderstanding your issue please let me know.

**Comment by akallabeth** [comment]
@LDVG yes, that is correct. Problem for me arises as I try to build libfido2 and its dependencies as `CMake` `ExternalProject` which uses non system paths. with `CMake >= 3.1` the `PKG_CONFIG_PATH` variable does not to be manually adjusted to include the `CMAKE_INSTALL_PREFIX` as search location.
it is just an annoyance, true, but having to manually set environment variables when that specific bug was resolved long ago is not what I´d expect.

**Comment by LDVG** [comment]
Thank you for the context. I'll give bumping it a look.
