### ISSUE TITLE
Undefined symbol sk_api_version when trying OpenSSH's U2F support

### ISSUE THREAD

**Issue by thexhr** [Yubico/libfido2#80]
Hi,

I just compiled latest OpenSSH master (as of 2f95d43dc222ce194622b706682e8de07c9cfb42) from https://github.com/openssh/openssh-portable and latest libfido2 master (as of 437896dcafc67d9596774c3bb9f97bfdb4810bb1) to test OpenSSH's new U2F support. When I try to generate a new -sk keypair I get the following error:

```
$ ssh-keygen -f test-ed-key -t ed25519-sk -w /usr/local/lib/libfido2.so
Generating public/private ed25519-sk key pair.
Security key provider /usr/local/lib/libfido2.so dlsym(sk_api_version) failed: /usr/local/lib/libfido2.so: undefined symbol: sk_api_version
```
I have neither installed OpenSSH nor libfido from packages, both are compiled from latest master.

My environment:

```
$ uname -a
Linux host 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cc --version
cc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
$ ssh -V
OpenSSH_8.1p1, OpenSSL 1.1.1b  26 Feb 2019
```

Let me know if you need more information or if I should test anything.

Regards

**Comment by martelletto** [comment]
Hi,

The middleware should be under /usr/local/lib/libsk-libfido2.so; try passing -w  /usr/local/lib/libsk-libfido2.so to ssh-keygen.

-p.

**Comment by thexhr** [comment]
Uh, stupid me. You are right.
