### ISSUE TITLE
Why does fido2-assert not return and display the user information

### ISSUE THREAD

**Issue by sbweeden** [Yubico/libfido2#9]
Experimenting with the fido2-assert command-line tool, and noticed that it returns (per the man page) the following:

           1.   client data hash (base64 blob);
           2.   relying party id (UTF-8 string);
           3.   authenticator data (base64 blob);
           4.   assertion signature (base64 blob);

Per https://fidoalliance.org/specs/fido-v2.0-rd-20170927/fido-client-to-authenticator-protocol-v2.0-rd-20170927.html#authenticatorGetAssertion
there should also be available a user object available. In particular it would be needed if trying to match a resident key assertion which had an empty allowCredentials list back to a user record for the username-less login scenario. 

Is there any reason the fido2-assert tool doesn't provide this?

**Comment by martelletto** [comment]
Hi,

There is no reason; it was an overlook on my part. :) I will adjust 
fido2-assert accordingly. Thank you for bringing this to my 
attention.

-p.

Thank you

**Comment by martelletto** [comment]
fixed in 768236c; thanks for the bug report!

-p.
