### ISSUE TITLE
Please verify the PGP keys in keys.openpgp.org that are used to sign the tarballs

### ISSUE THREAD

**Issue by Frederick888** [Yubico/libfido2#93]
https://developers.yubico.com/Software_Projects/Software_Signing.html has updated the URLs to keys.openpgp.org but I noticed that some keys, for instance `EE90AE0D19774C8386628FAAB428949EF7914718` which was used to sign `libfido2-1.3.0.tar.gz`, were not verified in keys.openpgp.org.

Consequently, users who've migrated to keys.openpgp.org can not import the keys due to missing UIDs:
```sh
$ gpg --search-keys EE90AE0D19774C8386628FAAB428949EF7914718
gpg: data source: https://keys.openpgp.org:443
(1)       4096 bit RSA key B428949EF7914718
Keys 1-1 of 1 for "EE90AE0D19774C8386628FAAB428949EF7914718".  Enter number(s), N)ext, or Q)uit > 1
gpg: key B428949EF7914718: no user ID
gpg: Total number processed: 1

$ gpg -k EE90AE0D19774C8386628FAAB428949EF7914718
gpg: error reading key: No public key
```
By the way, openpgp.org requires mail servers to provide MTA-STS configurations to send out the verification emails but it seems yubico.com doesn't support it yet (https://www.hardenize.com/report/yubico.com/1575812468#email_mta_sts). This causes difficulties downstream in terms of distribution and packaging. Please fix it asap, thanks a lot!

**Comment by martelletto** [comment]
Thanks, the key has been uploaded and verified. I will pass the request for MTA-STS to Yubico's infrastructure team.
