### ISSUE TITLE
Please consider providing gpg signatures for releases

### ISSUE THREAD

**Issue by garybuhrmaster** [Yubico/libfido2#97]
Please consider creating gpg signatures for releases.  Some packaging guidelines strongly encourage verifying signatures on the released tar files.

Thank you for your consideration.

**Comment by nevun** [comment]
Hi, please see https://developers.yubico.com/libfido2/Releases/

There you have signed releases. The project's README has a link to that as well on the first page. 

I hope this helps.
Cheers.

**Comment by garybuhrmaster** [comment]
Yes, that will work.  I had hoped that the signatures would also be posted on the github release pages.
