### ISSUE TITLE
centos7

### ISSUE THREAD

**Issue by kfox1111** [Yubico/libfido2#98]
Builds are failing on centos due to 2.8.12.2 < 3.0

**Comment by martelletto** [comment]
Hi,

Given the version numbers, I am assuming you are referring to CMake. Yes, CMake 3.0 (released in June, 2014) is required to build libfido2. Older versions of CMake might work, but there is no guarantee.

-p.

**Comment by garybuhrmaster** [comment]
As I recall, you *can* get cmake > 3.0 into el7 (yum install cmake3), and then use cmake3 in your build.  However, for el7, you will also need to build (at least) libcbor.

**Comment by kfox1111** [comment]
Oh, somehow I missed that. Thank you!
