### ISSUE TITLE
yubikey 4 nist with ssh

### ISSUE THREAD

**Issue by kfox1111** [Yubico/libfido2#99]
Testing out ssh integration via the newly merged u2f feature. Its failing. I'm wondering if this is expected as the yubikey nist mentions not supporting fido2. Must the key support fido2 in addition to u2f to support ssh?

**Comment by martelletto** [comment]
The key does not need to support FIDO2 to support SSH. However, some keys advertise CTAP2 support but can only talk CTAP1. I have implemented a workaround in ba94688308.

**Comment by roycewilliams** [comment]
(Side related, but IMO important to add to this ticket for historical reasons, question: what is "YubiKey 4 NIST"?)

**Comment by kfox1111** [comment]
Sorry. I said nist when I meant fips. https://www.yubico.com/products/yubikey-fips/

I can confirm the patch works with it. Thanks!
